### ISSUE TITLE
`unused parameter` warnings for do_get_mem_info

### ISSUE THREAD

**Issue by fkallen** [rapidsai/rmm#1032]
The stream parameter in do_get_mem_info(stream) is unused for some memory resources, for example

https://github.com/rapidsai/rmm/blob/branch-22.06/include/rmm/mr/device/managed_memory_resource.hpp#L117 

```  [[nodiscard]] std::pair<std::size_t, std::size_t> do_get_mem_info(
    cuda_stream_view stream) const override
  {
    std::size_t free_size{};
    std::size_t total_size{};
    RMM_CUDA_TRY(cudaMemGetInfo(&free_size, &total_size));
    return std::make_pair(free_size, total_size);
  }
```

This leads to compiler warnings.

**Comment by harrism** [comment]
Can you share the warning? The parameter is unnamed in the line you linked specifically to avoid unused parameter warnings.

**Comment by fkallen** [comment]
I made a mistake. I don't know why I wrote cuda_memory_resource. In my program the warning is for managed memory resource and limiting resource adapter.
