### ISSUE TITLE
[QST] Hard limit on the amount of data rmm can allocate at once?

### ISSUE THREAD

**Issue by yuya737** [rapidsai/rmm#104]
**What is your question?**
In the below code snippet the last line `d_pos=pos` transfers data across main memory and GPU memory. I'm having issues with this line when vectors hold data with size over a certain a threshold (around 30GB). Is there a hard limit of data rmm can allocate/move at once?

    void initDataset (std::vector<float> *pos, size_t x, size_t y, size_t z)
	{
        int i,j,k;
	double Pe;
	std::mt19937 rng(time(NULL));
	std::uniform_real_distribution<float> gen(-4.0, 0.0);
	for (i=-(int)x/2;i<((int)x/2);++i)
	{
		for (j=-(int)y/2;j<((int)y/2);++j)
		{
			for (k=0;k<z;++k)
			{
				Pe = gen(rng);
				pos->push_back(i);
				pos->push_back(j);
				pos->push_back(k);
				pos->push_back(Pe);
			}
		}
	}
    }

    int main (int argc, char *argv[])
         {
	unsigned int i, iter = 30;
	size_t sx = 400, sy = 400, sz = 2000;
	size_t numParticles = 0;
	std::vector<float> pos; // particle positions

	rmm::device_vector<float> d_pos; // particle positions in GPU
	rmm::device_vector<float> d_posOut; // particle positions out in GPU

	// This willl be used to generate plane's normals randomly
	// between -1 to 1
	std::mt19937 rng(time(NULL));
	std::uniform_real_distribution<float> gen(-1.0, 1.0);
	numParticles = sx*sy*sz;

        // Types of allocations:
        // CudaDefaultAllocation
        // PoolAllocation
        // CudaManagedMemory

    rmmOptions_t options{rmmAllocationMode_t::PoolAllocation, 0, true};
	rmmInitialize(&options);

	initDataset(&pos, sx, sy, sz);

	// plane defined by normal and D
	float normal[3], d = 0.0f;

	for (i=0;i<iter;i++)
	{
		// Generating plane's normals randomly
		// between -1 to 1
		normal[0] = gen(rng);
		normal[1] = gen(rng);
		normal[2] = gen(rng);
	
		timer.reset();
		d_pos = pos;
       ....

**Comment by jrhemstad** [comment]
What GPU are you using? First of all you'll be limited by the size of the GPU memory you have available. 

When using RMM in pool allocation mode, RMM allocates a large chunk of memory with `cudaMalloc`. By default, the size of this pool will be half of the GPU device memory. When servicing an allocation request, it will carve out a piece of memory from this pool. If it can't satisfy the request from the pool, it will allocate more GPU memory with `cudaMalloc` to satisfy your request.

If you request an allocation that is larger than both the pool and the remaining non-pool memory, then your allocation cannot be satisfied. 

If you want to maximize the size of the allocations you can make, then you should specify the pool size to be all of the GPU memory. You can do this by setting the `rmmOptions_t::initial_pool_size` parameter to be the size of your GPU memory in bytes.

**Comment by yuya737** [comment]
Sorry, I was actually using `rmmOptions_t options{static_cast<rmmAllocationMode_t>(PoolAllocation | CudaManagedMemory), 0, true};` instead and I believe I have 16GB of GPU memory available to me.

**Comment by jrhemstad** [comment]
Ah, I see, you are using a managed memory pool. This isn't rigorously tested yet, but should enable you to do over-subscription. 

What error were you seeing?

**Comment by benjha** [comment]
Hi Jake,

Thank you for the quick response.

Extending Yuya's response, we are using a Tesla Volta (16GB), cuda cuda/10.1.105, and -likely- rmm 0.8. When setting the rmm init. option to CudaManagedMemory, we have a similar behavior.

The error we are getting is:

terminate called after throwing an instance of 'thrust::system::detail::bad_alloc'
  what():  std::bad_alloc: temporary_buffer::allocate: get_temporary_buffer failed

and happens when calling thrust::remove_if method. Now I suspect such temporary buffer remove_if method try to allocate, of course does not support rmm.


Regards,

Benjamin

**Comment by harrism** [comment]
Are you using the `rmm::exec_policy` in your `thrust::remove_if`? https://github.com/rapidsai/rmm/blob/b117d2019bffbf9d4bd27944147799e4affd8c14/include/rmm/thrust_rmm_allocator.h#L98

e.g. `thrust::remove_if(rmm::exec_policy(stream)->on(stream), ...);`

Regarding the managed pool mode -- it's experimental, and hasn't been used or tested much.

**Comment by benjha** [comment]
We are not using rmm::exec_policy yet, will do and let  you know what we found.

Thanks,

**Comment by benjha** [comment]
After adding the execution policy to remove_if when using cudaManaged mode,  this is the error we got 


```
========= CUDA-MEMCHECK
Domain size is 400 x 400 x 14000 = 2240000000 particles
Size MB: 34179.7
Iterations: 30
Before stream create
Stream initialized: 0x472dda0
Generating particles...
68533 ms
done!
Clipping domain...
Before d_pos=pos
After d_pos=pos
H to D: 9800.18 ms
Calling remove_if on 0x472dda0 stream
========= Program hit cudaErrorMemoryAllocation (error 2) due to "out of memory" on CUDA API call to cudaMallocManaged. 
=========     Saved host backtrace up to driver entry point at error
=========     Host Frame:/usr/lib/x86_64-linux-gnu/libcuda.so.1 [0x3572d3]
=========     Host Frame:/raid/e8h/Programs/cuda-10.0/lib64/libcudart.so.10.0 (cudaMallocManaged + 0x1cc) [0x4655c]
=========     Host Frame:./clippingGPU_v2_rmm [0xd8a8]
=========     Host Frame:./clippingGPU_v2_rmm [0xe238]
=========     Host Frame:./clippingGPU_v2_rmm [0x67f9]
=========     Host Frame:./clippingGPU_v2_rmm [0x4378]
=========     Host Frame:/lib/x86_64-linux-gnu/libc.so.6 (__libc_start_main + 0xf0) [0x20830]
=========     Host Frame:./clippingGPU_v2_rmm [0x4b59]
=========
terminate called after throwing an instance of 'thrust::system::system_error'
  what():  rmm_allocator::allocate(): RMM_ALLOC: unspecified launch failure
========= Error: process didn't terminate successfully
========= No CUDA-MEMCHECK results found
```

rrmlog before calling remove_if:

```
Event Type,Device ID,Address,Stream,Size (bytes),Free Memory,Total Memory,Current Allocs,Start,End,Elapsed,Location
Alloc,0,0x7f2086000000,0,35840000000,0,0,1,69.3385,69.3389,0.000469081,/raid/e8h/Programs/include/rmm/thrust_rmm_allocator.h:49
```


and our remove_if looks like this

```
thrust::remove_if(rmm::exec_policy(*stream)->on(*stream), 
thrust::make_zip_iterator ( thrust::make_tuple( X.begin(), Y.begin(), Z.begin(), W.begin() )),
thrust::make_zip_iterator ( thrust::make_tuple( X.end(),Y.end(), Z.end(), W.end() )),
clip )
```
cuda stream is passed by reference to the method calling remove_if and clip functor only evaluates a conditional.

**Comment by harrism** [comment]
Are you able to provide a minimal standalone reproducer program?

**Comment by yuya737** [comment]
https://github.com/yuya737/rmm_min_reproduce

The above repo has a program that should reproduce the issue at hand.

Thanks!

**Comment by harrism** [comment]
I was able to repro. I'm asking at NVIDIA about limits on managed allocations.

**Comment by harrism** [comment]
RMM has changed a LOT since this was filed, and since it's inactive, I'm closing. Please comment or reopen if it's still an issue.
