### ISSUE TITLE
[FEA] Add `is_pooled` method to `device_memory_resource`

### ISSUE THREAD

**Issue by achirkin** [rapidsai/rmm#1060]
**Is your feature request related to a problem? Please describe.**
When integrating an algorithm that involves some temporary allocations, I figured I could use the `pool_memory_resource` to speedup CUDA allocations (and possibly avoid them on repeated calls to the same function). I do this by getting the current device memory resource, wrapping it into the pool resource, and passing the new resource to all rmm constructors explicitly. The problem arises if the current device resource is already a pooled memory: I get multiple layers of pooled memory and excessive memory usage. https://github.com/rapidsai/raft/blob/c581fe231deb5f935e458d7dae7c157aef8c02dc/cpp/include/raft/spatial/knn/detail/ivf_flat_search.cuh#L1286-L1291

**Describe the solution you'd like**
I'd like to have an extra method at the top of the memory resource hierarchy, similar to `supports_streams` or `supports_get_mem_info`, which would tell if the current instance is already pooled, so that I wouldn't need to wrap it.

**Describe alternatives you've considered**
A temporary workaround for me is to use `dynamic_cast`, but this solution is very limited and tedious, because `pool_memory_resource` is a template.

**Comment by jrhemstad** [comment]
This is not something I think we can do.

First, it's a semantics problem. What does "pooled" mean in the query "is_pooled"? There's lots of ways to implement the nebulous concept of a "memory pool".

More pragmatically, it shouldn't be a concern what the upstream resource is. There's two options here:
- Always use a user-provided resource and its their perogative to provide a pool resource or not.
- Always internally use a pool for temporary allocations (regardless of if the user-provided resource is a pool). There should be no problems with layering a `pool_memory_resource` on top of another `pool_memory_resource`. You may need to exercise some more caution in setting the initial pool size and max pool size for the temp pool.

**Comment by harrism** [comment]
I feel the same.  Also, `supports_streams` and `supports_get_mem_info` are flaws in the interface that we should deprecate and remove (and will with `cuda::memory_resource`)
