### ISSUE TITLE
Test PyTorch's Pluggable CUDA allocator with RMM

### ISSUE THREAD

**Issue by shwina** [rapidsai/rmm#1144]
PyTorch is adding a pluggable CUDA allocator! We should test to see how well this works with RMM:

https://github.com/pytorch/pytorch/pull/86786/

**Comment by jrhemstad** [comment]
As @harrism pointed out in the issue, the biggest concern is their free function doesn't take a stream or a size.

**Comment by harrism** [comment]
Yeah, I don't see how it can work with anything but cuda_malloc_resource, or whatever it is we call it. (On mobile, can't search)

**Comment by emcastillo** [comment]
[jrhemstad](https://github.com/jrhemstad) commented [5 days ago](https://github.com/rapidsai/rmm/issues/1144#issuecomment-1294081658)
As @harrism pointed out in the issue, the biggest concern is their free function doesn't take a stream or a size.

Yeah, I will work on this :)

**Comment by emcastillo** [comment]
@shwina I added support for the stream & size in the free function and do the book keeping in the allocator object. Still WIP but you can give it a try and let me know if you find something weird!

**Comment by emcastillo** [comment]
I will build a wheel and share it here so you can easily try it

**Comment by emcastillo** [comment]
just completed the PR, (waiting for reviews though ...)
Will try to compile a wheel tomorrow

**Comment by shwina** [comment]
Hi @emcastillo -- any chance you were able to build a wheel off of your PR? Whenever that's ready, I'm happy to test it out!

**Comment by emcastillo** [comment]
Hey there!
I was hoping the PR would be merged between last/this week so you could get it on the nightly wheel.
I think I can merge it today! I talked with Alban about it, and we decided to merge it and work on docs/enhancements later!

**Comment by shwina** [comment]
Sounds great -- thanks!

**Comment by emcastillo** [comment]
All merged! should be ready to use in tomorrow's nightly.
There was an issue that required a hotfix so don't be scared if you get a segfault 😂

**Comment by shwina** [comment]
I was able to do some initial testing of using RMM with PyTorch's CUDA allocator and am happy to report that things are working: https://gist.github.com/shwina/8547f1bbcb2f73b6a095beb40a5b675f! I'll expand this notebook with a few more demos tomorrow.

However, note that the `CUDAPluggableAllocator` class isn't quite usable by RMM. We want to define our `allocate` and `deallocate` functions using Cython, and the `.so` file (Python extension) produced by building a Cython module does not seem to export any C functions. I was able to work around this by interacting with the internal `_CUDAAllocator` type instead. Feedback on the approach is welcome, but I expect we need a `CudaPluggableAllocator`-like type that either accepts function pointers directly.

**Comment by emcastillo** [comment]
@shwina probably you know this and I am missing something but
if you declare `cdef` functions as public. `cdef public` they are exported

Cython code
```cython
...
cdef public c_hello():
    # Exposes a c function to python

    hello()
....

```
$ nm wrapped.cpython-37m-x86_64-linux-gnu.so | grep c_hello
0000000000024ec0 T c_hello

$ python
Python 3.7.12 (default, Dec 20 2021, 03:22:31)
[GCC 7.5.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import ctypes
>>> ctypes.CDLL('wrapped.cpython-37m-x86_64-linux-gnu.so')
<CDLL 'wrapped.cpython-37m-x86_64-linux-gnu.so', handle 55b6b286dc90 at 0x7f7bb1322e90>
>>> a=ctypes.CDLL('wrapped.cpython-37m-x86_64-linux-gnu.so')
>>> getattr(a, 'c_hello')
<_FuncPtr object at 0x7f7bb134b2c0>
>>> getattr(a, 'c_hello')()
hello world!
```

Not sure what happens with C++ mangling and other stuff but maybe if we declare RMM functions at public it may work?

**Comment by emcastillo** [comment]
I just tried it with CuPy and it worked fine :)
https://github.com/cupy/cupy/pull/7210

**Comment by shwina** [comment]
> if you declare cdef functions as public. cdef public they are exported

Many thanks @emcastillo! That worked like a charm! #1168
