### ISSUE TITLE
[DOC] Update README to include conda install

### ISSUE THREAD

**Issue by miguelangel** [rapidsai/rmm#117]
## Report incorrect documentation
Hi!

`README.md` file mentions RMM can only be installed via source code.

Nevertheless, I have found the following conda packages:

https://anaconda.org/rapidsai/rmm

https://anaconda.org/rapidsai/librmm

I am wondering if the README.md file is up-to-date. If not, it should be great to update it mentioning conda installs.

**Location of incorrect documentation**
README.md in master branch.

https://github.com/rapidsai/rmm#install-rmm

**Describe the problems or issues found in the documentation**
(detailed above)

**Comment by jakirkham** [comment]
Seems like the Conda install instructions are here : https://github.com/rapidsai/rmm#conda

Does that help? Or is there something I'm missing?

**Comment by miguelangel** [comment]
Hi!

That info has been  added in October this year (https://github.com/rapidsai/rmm/commit/eeadf360e08215d242617d5b2c5bed57922eb7c3#diff-04c6e90faac2675aa89e2176d2eec7d8). The issue is dated from August.

Nevertheless, it covers RMM 0.7 and 0.8 versions only. It would be great to have a mention about how to install the latest version.

Finally, please let me thank you for the great work you all are doing with RAPIDS.

Regards,
Miguel

**Comment by jakirkham** [comment]
Yep issues are getting solved. 🙂

Sure do you want to try a PR? 😉

Thanks! Glad you are enjoying it. 😀
