### ISSUE TITLE
Swap argument order in RMM_EXPECTS

### ISSUE THREAD

**Issue by vyasr** [rapidsai/rmm#1172]
The three argument version of the `RMM_EXPECTS` macro is somewhat misaligned with the two argument version:
```
RMM_EXPECTS(_condition, _reason)
RMM_EXPECTS(_condition, _exception_type, _reason)  # Note that exception type comes _before_ reason
```
We should reorder the parameters so that the three argument version adds the exception type at the end of the argument list rather than in the middle.

**Comment by harrism** [comment]
I wonder how this issue didn't get any labels automatically...

**Comment by vyasr** [comment]
I'm guessing because I opened it as a blank issue instead of using one of the templates (bug/feature/etc). I think we need a new type of issue, maybe a "Task" or so, that exists across RAPIDS and captures work that developers think needs to be done that doesn't fall under the usual feature/bug categories. I end up opening a blank issue for those purposes occasionally.

**Comment by harrism** [comment]
I agree I don't like filling out the forms.

**Comment by jrhemstad** [comment]
> I'm guessing because I opened it as a blank issue instead of using one of the templates (bug/feature/etc). I think we need a new type of issue, maybe a "Task" or so, that exists across RAPIDS and captures work that developers think needs to be done that doesn't fall under the usual feature/bug categories. I end up opening a blank issue for those purposes occasionally.

This issue is really just a feature request though. I don't think it's a problem with the issue forms, I think the problem exists between chair and keyboard :slightly_smiling_face:

**Comment by harrism** [comment]
Actually I don't think RMM has the forms yet. CuSpatial does though.

**Comment by vyasr** [comment]
> This issue is really just a feature request though. I don't think it's a problem with the issue forms, I think the problem exists between chair and keyboard slightly_smiling_face

I suppose at some point this devolves into a philosophical debate on what constitutes a feature :smiley: I personally prefer more separation between changes that only affect internals/developers and changes that allow calling code to do something new. To me it's not a feature if it doesn't merit a changelog entry visible to users. I realize that we end up dumping literally everything into our changelogs anyway though, and of course Hyrum's law applies so everything could be construed as a feature.
