### ISSUE TITLE
[BUG] librmm 22.10 and 22.12 conda packages ship spdlog as part of the package

### ISSUE THREAD

**Issue by kkraus14** [rapidsai/rmm#1205]
**Describe the bug**

The 22.10 and 22.12 librmm conda packages in the `rapidsai` channel ship a `libspdlog.a` static library as well as the spdlog headers, cmake files, and pkgconfig file. I only checked the `x86_64` packages, but I assume `aarch64` is the same.

**Expected behavior**

The conda packages shouldn't ship spdlog in any way and should leverage their `spdlog` dependency to get the needed pieces.

**Comment by vyasr** [comment]
This is resolved by https://github.com/rapidsai/rmm/pull/1177, right @bdice? I'm assuming that this was happening because of the preexisting mismatch between the conda-forge spdlog pinning and the version we were using, which should now be aligned after #1177.

**Comment by bdice** [comment]
I think #1177 solves this, yes. I looked at the package contents and didn’t see any packaged headers. Resolving - feel free to reopen if needed.

**Comment by vyasr** [comment]
Yup I checked the recent packages as well and didn't find any spdlog.
