### ISSUE TITLE
[QST]about MR and DEVICE_BUFFER runtime problem for old RMM versions

### ISSUE THREAD

**Issue by Loneseven** [rapidsai/rmm#1234]
Hello. I am new to to rapidsai repos. Recently I have tried to build old versions of cuML/cuDF/RMM from source. I cannot use python 3.7-3.10 or conda due to development environment restrictions.  After compiling RMM (tag v0.15.0) successfully, the make tests failed:
1 DEVICE_MR_TEST (SEGFAULT): 
/rmm/tests/mr/device/mr_test.hpp:92: Failure
Expected: p = rmm::mr::get_current_device_resource()->allocate(1_MiB) doesn't throw an exception.
  Actual: it throws.
/rmm/tests/mr/device/mr_test.hpp:93: Failure
Expected: (nullptr) != (p), actual: 8-byte object <00-00 00-00 00-00 00-00> vs NULL
/rmm/tests/mr/device/mr_test.hpp:95: Failure
Value of: is_device_memory(p)
  Actual: false
Expected: true
/rmm/tests/mr/device/mr_test.hpp:104: Failure
Expected: p = mr->allocate(bytes) doesn't throw an exception.
  Actual: it throws.
/rmm/tests/mr/device/mr_test.hpp:106: Failure
Expected: (nullptr) != (p), actual: 8-byte object <00-00 00-00 00-00 00-00> vs NULL
/rmm/tests/mr/device/mr_test.hpp:108: Failure
Value of: is_device_memory(p)
  Actual: false
Expected: true
2 DEVICE_MR_PTDS_TEST (SEGFAULT)
3 DEVICE_BUFFER_TEST (Failed):
[ RUN      ] DeviceBufferTest/1.ExplicitMemoryResource
unknown file: Failure
C++ exception with description "std::bad_alloc: CUDA error at: /rmm/tests/../include/rmm/mr/device/managed_memory_resource.hpp:72: cudaErrorNotSupported operation not supported" thrown in the test body.
[  FAILED  ] DeviceBufferTest/1.ExplicitMemoryResource, where TypeParam = rmm::mr::managed_memory_resource (0 ms)

I know it's 2-3 yeas now from this branch, can you kindly point out the key problem if possible? As far as I can see it may be CUDA runtime problem, but I can run numba or torch using CUDA. My envs are as follows, docker container with CUDA 10.1 running on host with CUDA 11 and corresponding driver installed:
***OS Information***
CentOS Linux release 7.2
***GPU Information***
Fri Mar 17 17:14:23 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 450.102.04   Driver Version: 450.102.04   CUDA Version: 11.0     |
|-------------------------------+----------------------+----------------------+
***CMake***
/usr/bin/cmake
cmake version 3.23.1

CMake suite maintained and supported by Kitware (kitware.com/cmake).

***g++***
/usr/local/gcc7/bin/g++
g++ (GCC) 7.5.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

***nvcc***
/usr/local/cuda/bin/nvcc
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Sun_Jul_28_19:07:16_PDT_2019
Cuda compilation tools, release 10.1, V10.1.243

***Python***
/usr/bin/python
Python 3.6.8
***Environment Variables***
PATH                            : /usr/local/gcc7/bin:/usr/local/nvidia/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/cuda/bin:/usr/local/cmake-3.23.1-linux-x86_64/bin:/usr/local/thrift/bin
LD_LIBRARY_PATH                 : /root/boost/lib:/usr/local/gcc7/lib64:/usr/local/nvidia/lib:/usr/local/nvidia/lib64:/usr/local/cuda/lib64:/usr/local/lib:/usr/local/cuda/extras/CUPTI/lib64:/usr/local/thrift/lib:/arrow/dist/lib:/soft/rmm/lib

**Comment by harrism** [comment]
It's hard to tell what is causing the CUDA_ERROR_UNSUPPORTED. This, as you say, is a very old branch, which we don't really have the resources to support. If you want you could try to narrow the error down more by running a debug build, then looking at the source lines where the error occurs.
