### ISSUE TITLE
[BUG] getting UnsupportedCUDAError in conda env with cuda-python=11.8

### ISSUE THREAD

**Issue by rpeys** [rapidsai/rmm#1235]
I installed cuml into a conda env using `pip install cuml-cu11 --extra-index-url=https://pypi.nvidia.com`. However, when I run `import cuml` in python, I get the following error: 
```
File "/opt/conda/rpeyser/envs/scset3/lib/python3.8/site-packages/cudf/utils/gpu_utils.py", line 101, in validate_setup
    raise UnsupportedCUDAError( 
cudf.errors.UnsupportedCUDAError: Detected CUDA Runtime version is 10.0. Please update your CUDA Runtime to 11.0 or above`.
```

The server I am on indeed has cuda 10 installed in /usr/local/cuda-10.1/, however, my conda environment shows that I have cuda-python version 11.8 installed. Do you know how I can get cuml to recognize the cuda toolkit version installed in my conda env, and avoid this error? Thanks!

Here is a summary of my system settings, including all the packages installed in my conda environment (notably, cuda-python 11.8):
<details><summary>Click here to see environment details</summary><pre>
     **git***
     Not inside a git repository

     ***OS Information***
     DISTRIB_ID=Ubuntu
     DISTRIB_RELEASE=20.04
     DISTRIB_CODENAME=focal
     DISTRIB_DESCRIPTION="Ubuntu 20.04.3 LTS"
     NAME="Ubuntu"
     VERSION="20.04.3 LTS (Focal Fossa)"
     ID=ubuntu
     ID_LIKE=debian
     PRETTY_NAME="Ubuntu 20.04.3 LTS"
     VERSION_ID="20.04"
     HOME_URL="https://www.ubuntu.com/"
     SUPPORT_URL="https://help.ubuntu.com/"
     BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
     PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
     VERSION_CODENAME=focal
     UBUNTU_CODENAME=focal
     Linux hera 5.4.0-110-generic #124-Ubuntu SMP Thu Apr 14 19:46:19 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

     ***GPU Information***
     Sat Mar 18 23:31:01 2023
     +-----------------------------------------------------------------------------+
     | NVIDIA-SMI 470.161.03   Driver Version: 470.161.03   CUDA Version: 11.4     |
     |-------------------------------+----------------------+----------------------+
     | GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
     | Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
     |                               |                      |               MIG M. |
     |===============================+======================+======================|
     |   0  NVIDIA GeForce ...  Off  | 00000000:3B:00.0 Off |                  N/A |
     | 23%   30C    P8    15W / 250W |   1353MiB / 11178MiB |      0%      Default |
     |                               |                      |                  N/A |
     +-------------------------------+----------------------+----------------------+
     |   1  NVIDIA GeForce ...  Off  | 00000000:5E:00.0 Off |                  N/A |
     | 34%   58C    P2   115W / 250W |   9313MiB / 11178MiB |     43%      Default |
     |                               |                      |                  N/A |
     +-------------------------------+----------------------+----------------------+
     |   2  NVIDIA GeForce ...  Off  | 00000000:AF:00.0 Off |                  N/A |
     | 23%   33C    P8     9W / 250W |      2MiB / 11178MiB |      0%      Default |
     |                               |                      |                  N/A |
     +-------------------------------+----------------------+----------------------+
     |   3  NVIDIA GeForce ...  Off  | 00000000:D8:00.0 Off |                  N/A |
     | 23%   33C    P8     8W / 250W |      2MiB / 11178MiB |      0%      Default |
     |                               |                      |                  N/A |
     +-------------------------------+----------------------+----------------------+

     +-----------------------------------------------------------------------------+
     | Processes:                                                                  |
     |  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
     |        ID   ID                                                   Usage      |
     |=============================================================================|
     |    0   N/A  N/A    462567      C   ...vs/cuml-scanpy/bin/python     1351MiB |
     |    1   N/A  N/A    984349      C   python                           9311MiB |
     +-----------------------------------------------------------------------------+

     ***CPU***
     Architecture:                    x86_64
     CPU op-mode(s):                  32-bit, 64-bit
     Byte Order:                      Little Endian
     Address sizes:                   46 bits physical, 48 bits virtual
     CPU(s):                          48
     On-line CPU(s) list:             0-47
     Thread(s) per core:              2
     Core(s) per socket:              12
     Socket(s):                       2
     NUMA node(s):                    2
     Vendor ID:                       GenuineIntel
     CPU family:                      6
     Model:                           85
     Model name:                      Intel(R) Xeon(R) Gold 6126 CPU @ 2.60GHz
     Stepping:                        4
     CPU MHz:                         1000.066
     CPU max MHz:                     3700.0000
     CPU min MHz:                     1000.0000
     BogoMIPS:                        5200.00
     Virtualization:                  VT-x
     L1d cache:                       768 KiB
     L1i cache:                       768 KiB
     L2 cache:                        24 MiB
     L3 cache:                        38.5 MiB
     NUMA node0 CPU(s):               0-11,24-35
     NUMA node1 CPU(s):               12-23,36-47
     Vulnerability Itlb multihit:     KVM: Mitigation: Split huge pages
     Vulnerability L1tf:              Mitigation; PTE Inversion; VMX conditional cache flushes, SMT vulnerable
     Vulnerability Mds:               Mitigation; Clear CPU buffers; SMT vulnerable
     Vulnerability Meltdown:          Mitigation; PTI
     Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
     Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
     Vulnerability Spectre v2:        Mitigation; Retpolines, IBPB conditional, IBRS_FW, STIBP conditional, RSB filling
     Vulnerability Srbds:             Not affected
     Vulnerability Tsx async abort:   Mitigation; Clear CPU buffers; SMT vulnerable
     Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 cdp_l3 invpcid_single pti intel_ppin ssbd mba ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm mpx rdt_a avx512f avx512dq rdseed adx smap clflushopt clwb intel_pt avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm ida arat pln pts hwp hwp_act_window hwp_epp hwp_pkg_req pku ospke md_clear flush_l1d

     ***CMake***
     /usr/bin/cmake
     cmake version 3.16.3

     CMake suite maintained and supported by Kitware (kitware.com/cmake).

     ***g++***
     /usr/bin/g++
     g++ (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
     Copyright (C) 2019 Free Software Foundation, Inc.
     This is free software; see the source for copying conditions.  There is NO
     warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

     ***nvcc***

     ***Python***
     /opt/conda/rpeyser/envs/scset3/bin/python
     Python 3.8.15

     ***Environment Variables***
     PATH                            : /home/rpeyser/bin:/home/rpeyser/.local/bin:/home/rpeyser/google-cloud-sdk/bin:/opt/conda/rpeyser/envs/scset3/bin:/opt/conda/rpeyser/condabin:/usr/local/cuda-11.4/bin:/usr/local/csail/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:.:/software/jdk1.8.0_191/bin:/home/rpeyser/software/hadoop-3.1.1/bin:/home/rpeyser/software/apache-hive-3.1.1-bin/bin
     LD_LIBRARY_PATH                 : /usr/local/cuda-11.4/lib64:
     NUMBAPRO_NVVM                   :
     NUMBAPRO_LIBDEVICE              :
     CONDA_PREFIX                    : /opt/conda/rpeyser/envs/scset3
     PYTHON_PATH                     :

     ***conda packages***
     /opt/conda/rpeyser/condabin/conda
     # packages in environment at /opt/conda/rpeyser/envs/scset3:
     #
     # Name                    Version                   Build  Channel
     _libgcc_mutex             0.1                 conda_forge    conda-forge
     _openmp_mutex             4.5                       2_gnu    conda-forge
     absl-py                   1.3.0                    pypi_0    pypi
     addict                    2.4.0                    pypi_0    pypi
     anndata                   0.8.0                    pypi_0    pypi
     asttokens                 2.2.1              pyhd8ed1ab_0    conda-forge
     attrs                     22.2.0                   pypi_0    pypi
     backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
     backports                 1.0                pyhd8ed1ab_3    conda-forge
     backports.functools_lru_cache 1.6.4              pyhd8ed1ab_0    conda-forge
     bzip2                     1.0.8                h7f98852_4    conda-forge
     ca-certificates           2022.12.7            ha878542_0    conda-forge
     cachetools                4.2.4                    pypi_0    pypi
     certifi                   2022.12.7                pypi_0    pypi
     chardet                   3.0.4                    pypi_0    pypi
     charset-normalizer        2.1.1                    pypi_0    pypi
     click                     8.1.3                    pypi_0    pypi
     cloudpickle               2.2.1                    pypi_0    pypi
     comm                      0.1.2              pyhd8ed1ab_0    conda-forge
     configargparse            1.5.3                    pypi_0    pypi
     contourpy                 1.0.6                    pypi_0    pypi
     cubinlinker-cu11          0.3.0.post1              pypi_0    pypi
     cuda-python               11.8.1                   pypi_0    pypi
     cudf-cu11                 23.2.0                   pypi_0    pypi
     cuml-cu11                 23.2.0                   pypi_0    pypi
     cupy-cuda11x              11.6.0                   pypi_0    pypi
     cycler                    0.11.0                   pypi_0    pypi
     cython                    0.29.21                  pypi_0    pypi
     dash                      2.8.1                    pypi_0    pypi
     dash-core-components      2.0.0                    pypi_0    pypi
     dash-html-components      2.0.0                    pypi_0    pypi
     dash-table                5.0.0                    pypi_0    pypi
     dask                      2023.1.1                 pypi_0    pypi
     dask-cuda                 23.2.1                   pypi_0    pypi
     dask-cudf-cu11            23.2.0                   pypi_0    pypi
     debugpy                   1.6.5            py38h8dc9893_0    conda-forge
     decorator                 5.1.1              pyhd8ed1ab_0    conda-forge
     deepspeed                 0.3.13                   pypi_0    pypi
     distributed               2023.1.1                 pypi_0    pypi
     entrypoints               0.4                pyhd8ed1ab_0    conda-forge
     executing                 1.2.0              pyhd8ed1ab_0    conda-forge
     fastjsonschema            2.16.2                   pypi_0    pypi
     fastrlock                 0.8.1                    pypi_0    pypi
     flask                     2.2.2                    pypi_0    pypi
     fonttools                 4.38.0                   pypi_0    pypi
     fsspec                    2023.3.0                 pypi_0    pypi
     future                    0.18.2                   pypi_0    pypi
     google-auth               1.35.0                   pypi_0    pypi
     google-auth-oauthlib      0.4.6                    pypi_0    pypi
     grpcio                    1.51.1                   pypi_0    pypi
     h5py                      3.7.0                    pypi_0    pypi
     heapdict                  1.0.1                    pypi_0    pypi
     idna                      2.10                     pypi_0    pypi
     igraph                    0.10.4                   pypi_0    pypi
     imageio                   2.9.0                    pypi_0    pypi
     imgaug                    0.4.0                    pypi_0    pypi
     importlib-metadata        6.0.0                    pypi_0    pypi
     importlib-resources       5.10.2                   pypi_0    pypi
     ipykernel                 6.20.1             pyh210e3f2_0    conda-forge
     ipython                   8.8.0              pyh41d4057_0    conda-forge
     ipywidgets                8.0.4                    pypi_0    pypi
     itsdangerous              2.1.2                    pypi_0    pypi
     jedi                      0.18.2             pyhd8ed1ab_0    conda-forge
     jinja2                    3.1.2                    pypi_0    pypi
     joblib                    1.2.0                    pypi_0    pypi
     jsonschema                4.17.3                   pypi_0    pypi
     jupyter_client            7.4.9              pyhd8ed1ab_0    conda-forge
     jupyter_core              5.1.3            py38h578d9bd_0    conda-forge
     jupyterlab-widgets        3.0.5                    pypi_0    pypi
     kiwisolver                1.4.4                    pypi_0    pypi
     ld_impl_linux-64          2.39                 hcc3a1bd_1    conda-forge
     leidenalg                 0.9.1                    pypi_0    pypi
     libffi                    3.4.2                h7f98852_5    conda-forge
     libgcc-ng                 12.2.0              h65d4601_19    conda-forge
     libgomp                   12.2.0              h65d4601_19    conda-forge
     libnsl                    2.0.0                h7f98852_0    conda-forge
     libsodium                 1.0.18               h36c2ea0_1    conda-forge
     libsqlite                 3.40.0               h753d276_0    conda-forge
     libstdcxx-ng              12.2.0              h46fd767_19    conda-forge
     libuuid                   2.32.1            h7f98852_1000    conda-forge
     libzlib                   1.2.13               h166bdaf_4    conda-forge
     llvmlite                  0.39.1                   pypi_0    pypi
     locket                    1.0.0                    pypi_0    pypi
     markdown                  3.4.1                    pypi_0    pypi
     markupsafe                2.1.1                    pypi_0    pypi
     matplotlib                3.6.2                    pypi_0    pypi
     matplotlib-inline         0.1.6              pyhd8ed1ab_0    conda-forge
     msgpack                   1.0.5                    pypi_0    pypi
     natsort                   8.2.0                    pypi_0    pypi
     nbformat                  5.5.0                    pypi_0    pypi
     ncurses                   6.3                  h27087fc_1    conda-forge
     nest-asyncio              1.5.6              pyhd8ed1ab_0    conda-forge
     networkx                  2.8.8                    pypi_0    pypi
     ninja                     1.10.0.post2             pypi_0    pypi
     numba                     0.56.4                   pypi_0    pypi
     numpy                     1.23.5                   pypi_0    pypi
     nvtx                      0.2.5                    pypi_0    pypi
     oauthlib                  3.2.2                    pypi_0    pypi
     open3d                    0.16.0                   pypi_0    pypi
     opencv-python             4.3.0.36                 pypi_0    pypi
     openssl                   3.0.7                h0b41bf4_1    conda-forge
     ordered-set               4.0.2                    pypi_0    pypi
     packaging                 22.0                     pypi_0    pypi
     pandas                    1.5.2                    pypi_0    pypi
     parso                     0.8.3              pyhd8ed1ab_0    conda-forge
     partd                     1.3.0                    pypi_0    pypi
     patsy                     0.5.3                    pypi_0    pypi
     pexpect                   4.8.0              pyh1a96a4e_2    conda-forge
     pickleshare               0.7.5                   py_1003    conda-forge
     pillow                    9.4.0                    pypi_0    pypi
     pip                       22.3.1             pyhd8ed1ab_0    conda-forge
     pkgutil-resolve-name      1.3.10                   pypi_0    pypi
     platformdirs              2.6.2              pyhd8ed1ab_0    conda-forge
     plotly                    5.13.0                   pypi_0    pypi
     prompt-toolkit            3.0.36             pyha770c72_0    conda-forge
     protobuf                  4.21.0                   pypi_0    pypi
     psutil                    5.9.4            py38h0a891b7_0    conda-forge
     ptxcompiler-cu11          0.7.0.post1              pypi_0    pypi
     ptyprocess                0.7.0              pyhd3deb0d_0    conda-forge
     pure_eval                 0.2.2              pyhd8ed1ab_0    conda-forge
     pyarrow                   10.0.0                   pypi_0    pypi
     pyasn1                    0.4.8                    pypi_0    pypi
     pyasn1-modules            0.2.8                    pypi_0    pypi
     pygments                  2.14.0             pyhd8ed1ab_0    conda-forge
     pylibraft-cu11            23.2.0                   pypi_0    pypi
     pynndescent               0.5.8                    pypi_0    pypi
     pynvml                    11.4.1                   pypi_0    pypi
     pyparsing                 3.0.9                    pypi_0    pypi
     pyquaternion              0.9.9                    pypi_0    pypi
     pyrsistent                0.19.3                   pypi_0    pypi
     python                    3.8.15          h4a9ceb5_0_cpython    conda-forge
     python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
     python_abi                3.8                      3_cp38    conda-forge
     pytz                      2022.7                   pypi_0    pypi
     pywavelets                1.4.1                    pypi_0    pypi
     pyyaml                    6.0                      pypi_0    pypi
     pyzmq                     25.0.0           py38he24dcef_0    conda-forge
     raft-dask-cu11            23.2.0                   pypi_0    pypi
     readline                  8.1.2                h0f457ee_0    conda-forge
     requests                  2.23.0                   pypi_0    pypi
     requests-oauthlib         1.3.0                    pypi_0    pypi
     rmm-cu11                  23.2.0                   pypi_0    pypi
     rsa                       4.9                      pypi_0    pypi
     scanpy                    1.9.2                    pypi_0    pypi
     scikit-image              0.17.2                   pypi_0    pypi
     scikit-learn              0.23.2                   pypi_0    pypi
     scipy                     1.10.0                   pypi_0    pypi
     seaborn                   0.12.2                   pypi_0    pypi
     session-info              1.0.0                    pypi_0    pypi
     setuptools                65.6.3             pyhd8ed1ab_0    conda-forge
     shapely                   2.0.0                    pypi_0    pypi
     six                       1.14.0                   pypi_0    pypi
     sortedcontainers          2.4.0                    pypi_0    pypi
     stack_data                0.6.2              pyhd8ed1ab_0    conda-forge
     statsmodels               0.13.5                   pypi_0    pypi
     stdlib-list               0.8.0                    pypi_0    pypi
     tblib                     1.7.0                    pypi_0    pypi
     tenacity                  8.1.0                    pypi_0    pypi
     tensorboard               2.11.2                   pypi_0    pypi
     tensorboard-data-server   0.6.1                    pypi_0    pypi
     tensorboard-plugin-wit    1.8.1                    pypi_0    pypi
     tensorboardx              1.8                      pypi_0    pypi
     texttable                 1.6.7                    pypi_0    pypi
     threadpoolctl             3.1.0                    pypi_0    pypi
     tifffile                  2022.10.10               pypi_0    pypi
     tk                        8.6.12               h27826a3_0    conda-forge
     toolz                     0.12.0                   pypi_0    pypi
     torch                     1.12.1+cu113             pypi_0    pypi
     torchaudio                0.12.1+cu113             pypi_0    pypi
     torchvision               0.13.1+cu113             pypi_0    pypi
     tornado                   6.2              py38h0a891b7_1    conda-forge
     tqdm                      4.43.0                   pypi_0    pypi
     traitlets                 5.8.1              pyhd8ed1ab_0    conda-forge
     treelite                  3.1.0                    pypi_0    pypi
     treelite-runtime          3.1.0                    pypi_0    pypi
     typing-extensions         4.4.0                hd8ed1ab_0    conda-forge
     typing_extensions         4.4.0              pyha770c72_0    conda-forge
     ucx-py-cu11               0.30.0                   pypi_0    pypi
     umap-learn                0.5.3                    pypi_0    pypi
     urllib3                   1.25.8                   pypi_0    pypi
     wcwidth                   0.2.5              pyh9f0ad1d_2    conda-forge
     werkzeug                  2.2.2                    pypi_0    pypi
     wheel                     0.38.4             pyhd8ed1ab_0    conda-forge
     widgetsnbextension        4.0.5                    pypi_0    pypi
     xz                        5.2.6                h166bdaf_0    conda-forge
     zeromq                    4.3.4                h9c3ff4c_1    conda-forge
     zict                      2.2.0                    pypi_0    pypi
     zipp                      3.11.0                   pypi_0    pypi
</pre></details>

**Comment by vyasr** [comment]
Unfortunately the cuda-python package simply provides Python bindings to the underlying CUDA C++ libraries, it does not provide a full CTK by itself. You still need a sufficiently new toolkit installed. The most important thing is having a sufficiently new driver installed, because after that you should be able to manage the toolkit version by installing it with conda. I see that you are already inside a conda environment, is there any reason you can't install cudf with conda as well? That would automatically ensure that you are pulling in the necessary dependencies.

**Comment by vyasr** [comment]
Unrelated tip, putting the triple backticks outside of the HTML `<detail>` tag causes the tags not to be interpreted. You get the dropdown by removing that (I've edited your original description accordingly 🙂)

**Comment by vyasr** [comment]
I'm going to close this issue as addressed for now, but please reopen if there are further issues to address here.
