### ISSUE TITLE
[FEA] Is there any pip installation choice?

### ISSUE THREAD

**Issue by zhimin-z** [rapidsai/rmm#1253]
**Is your feature request related to a problem? Please describe.**
I see that we need to have conda to install rmm, wondering if we can use pip to install otherwise. My lab server fails to ship with conda as the default package manager.

**Describe the solution you'd like**
Maybe a feature enhancement?

**Comment by shwina** [comment]
Yes, you can use pip to install RMM:

```
pip install --extra-index-url https://pypi.nvidia.com rmm_cu11
```

I see that the RAPIDS [website ](https://docs.rapids.ai/install#pip-install)  does not include RMM in the list of packages that support pip installs and we will fix that. Thank you for reporting!

**Comment by vyasr** [comment]
I'm going to transfer this issue to the website repo for better tracking

**Comment by vyasr** [comment]
Opened https://github.com/rapidsai/rapids.ai/issues/320 to track.
