### ISSUE TITLE
[FEA] Supporting cuDF Series in device_array_like

### ISSUE THREAD

**Issue by jakirkham** [rapidsai/rmm#129]
**Is your feature request related to a problem? Please describe.**

I'd like to run the following code.

```python
from librmm_cffi import librmm as rmm
import cudf

s = cudf.Series([0, 1, 2])
a = rmm.device_array_like(s)
```

Currently this fails with the following error.

```python
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-3-917a74c3463e> in <module>
----> 1 rmm.device_array_like(s)

~/miniconda/envs/rapids9/lib/python3.7/site-packages/librmm_cffi/wrapper.py in device_array_like(self, ary, stream)
    227             ary = ary.reshape(1)
    228 
--> 229         return self.device_array(ary.shape, ary.dtype, ary.strides,
    230                                  stream=stream)
    231 

AttributeError: 'Series' object has no attribute 'strides'
```

**Describe the solution you'd like**

It would be great if `rmm.device_array_like` worked with Series objects. No strong feelings about how that is accomplished.

**Describe alternatives you've considered**

We could special case handling of `Series` objects, but this shifts the burden to other libraries to solve this problem.

Alternatively cuDF `Series` objects could gain a `strides` attribute. This could be reasonable.

**Additional context**

This came up when trying to better handle GPU array-like objects in cuML ( https://github.com/rapidsai/cuml/pull/1086 ), which is part of the Grid Search effort.

Edit: More specifically, we tried to use `librmm_cffi.librmm.to_device` instead of `numba.cuda.to_device`, but were unable to as Series are not supported.

**Comment by jakirkham** [comment]
Hmm...the doc label here is a bit unexpected. Unfortunately I don't seem able to fix that. Should be flagged as an enhancement or possibly a bug depending.

**Comment by jakirkham** [comment]
FWIW if I perform this operation with Numba's `to_device`, it works without issues.

```python
import numba
import numba.cuda

numba.cuda.to_device(s)
```

cc @kkraus14 ( in response to this comment https://github.com/rapidsai/cuml/pull/1086#issuecomment-530496825 )

**Comment by kkraus14** [comment]
I'm guessing numba is using `__cuda_array_interface__` here, whereas RMM doesn't since it assumes it should allocate memory.

**Comment by jakirkham** [comment]
Yeah that makes sense. Using `__cuda_array_interface__` here would be great (assuming others agree).

**Comment by kkraus14** [comment]
Removing array functionality in RMM in future so closing this issue.

**Comment by jakirkham** [comment]
For future readers, please see issue ( https://github.com/rapidsai/rmm/issues/180 ) for context.
