### ISSUE TITLE
[BUG] Error when using RMM: parallel_for failed: out of memory

### ISSUE THREAD

**Issue by vilmara** [rapidsai/rmm#130]
**Environment details (please complete the following information):**
 - Environment location: Docker
 - Method of RMM install: Docker
   - Docker pull: d`ocker pull rapidsai/rapidsai-dev:0.9-cuda10.0-devel-ubuntu16.04-py3.7`
   - Docker run: `docker run --runtime=nvidia --rm -it --net=host -p 8888:8888 -p 8787:8787 -p 8786:8786 -v /home/rapids/notebooks-extended/:/rapids/notebooks/extended/ -v /home/rapids/data/:/home/rapids/data/ rapidsai/rapidsai-dev:0.9-cuda10.0-devel-ubuntu16.04-py3.7`

**Describe the bug**
 I am using the Jupyter notebook NYCTaxi-E2E.ipynb and have added the RMM functionality; however, the system crashes at the XGBoost training step. See below the error:
```
terminate called after throwing an instance of 'thrust::system::system_error'
  what():  parallel_for failed: out of memory
```

**Steps/Code to reproduce bug**
Added methods:
```
def initialize_rmm_pool():
    rmm_cfg.use_pool_allocator = True
    return cudf.rmm.initialize()

def initialize_rmm_no_pool():
    rmm_cfg.use_pool_allocator = False
    return cudf.rmm.initialize()

def finalize_rmm():
    return cudf.rmm.finalize()
```

**Comment by harrism** [comment]
@vilmara is this still an issue with recent RAPIDS versions? If not we can close.
