### ISSUE TITLE
[FEA] Manual Managed memory

### ISSUE THREAD

**Issue by Destranix** [rapidsai/rmm#1325]
**Is your feature request related to a problem? Please describe.**
Some Graphics cards (even newer ones like Turing series) might not support oversubscription for managed memory. It would be nice to have an API that allows automatic swapping of memory to requested devices.

**Describe the solution you'd like**
Memory would be allocated normally using allocate and deallocate, but before usage on a specific device memory must be acquired, what causes memory transfer to the desired device if necessary. After usage the memory shell be released.
(Also calls for acquiring multiple locations at once could be very benifical, as it can speed up the allocation an defragmentation process.)

A default implementation would simply proxy Managed Memory and prefetch.

**Describe alternatives you've considered**
Maybe someone can also do some Virtual Memory magic on machines that do not support oversubscription somehow.

**Comment by harrism** [comment]
So you are suggesting RMM should implement managed memory for devices that don't support it? I think managed memory is supported by the Turing GPU architecture.

**Comment by Destranix** [comment]
>  I think managed memory is supported by the Turing GPU architecture.

See
https://cuda-tutorial.github.io/part3.pdf
In connection with
https://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__MEMORY.html#group__CUDART__MEMORY_1gd228014f19cc0975ebe3e0dd2af6dd1b

"Even Turing GPUs and newer may not support concurrent access"
"Device memory oversubscription is possible for GPUs that have a non-zero value for the device attribute [cudaDevAttrConcurrentManagedAccess](https://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__TYPES.html#group__CUDART__TYPES_1gg49e2f8c2c0bd6fe264f2fc970912e5cdc88178f29891f2c18fe67361cc80de09)."

Also on my RTX 2080 on Windows 10 I get a zero-value for that flag and I cannot oversubscribe ManagedMemory.
(Maybe though there is some other issue, if you have any suggestions I would be happy. But I couldn't yet find anything regarding this except for the source linked above tahat stats that ConcurrentMemoryAccess might not be supported on some Turing cards.)

> So you are suggesting RMM should implement managed memory for devices that don't support it?
Yes. Unfortunatly nobody else does implement that yet and your library seems to be best suited for it.
With the feature people could use managed memory without having to worry about their code not working on older machines or newers that do not support ConcurrentMemoryAccess.

**Comment by jrhemstad** [comment]
It is not possible for RMM to implement the equivalent of `ConcurrentMemoryAccess` for managed memory on Windows machines. This is a known limitation of managed memory on Windows and stems from issues in the interaction between the OS and the CUDA driver that would require changes in Windows itself.

**Comment by Destranix** [comment]
That's why I suggest manually managed memory. But thanks for the clearification about the limitations in Windows.

**Comment by harrism** [comment]
Implementing managed memory is a very large undertaking. I don't think it's in scope for RMM. The Windows limitations are unfortunate. Is Linux an option for you?

**Comment by Destranix** [comment]
> Implementing managed memory is a very large undertaking.

Well, yes and no. Yes if you wanna make it very performant and adjustable for different situations, no if you just implement a minimal version. And of course there is something inbetween.

> Is Linux an option for you?

I already implemented some very basic Manual Managed Memory for my application. I'm just suggesting this for future if anyone has a similiar problem. Your library seems most fitting for implementing something like that.

(A link here, but it's not yet fully tested and it's more like a fast written solution:
https://github.com/OaSiS-Masterthesis/OaSiS/blob/dev/Projects/OaSiS/managed_memory.hpp
)

**Comment by harrism** [comment]
Realistically, with RMM's limited resources, we aren't going to implement a non-performant manual managed memory in RMM unless there's a significant community or business justification.  We do welcome external contributions (PRs). I'm going to close this but please reopen if there is a more pressing justification.  (Note RMM does not yet work on Windows, and that work is not scheduled.)
