### ISSUE TITLE
[FEA] Add array shape and order options for device_array_from_ptr

### ISSUE THREAD

**Issue by tfeher** [rapidsai/rmm#135]
**Is your feature request related to a problem? Please describe.**

Currently device_array_from_ptr in librmm_cffi/wrapper.py assumes 1D array. Some cuML algorithms return higher dimensional arrays, and we need to wrap them as DeviceNDArray.

**Describe the solution you'd like**
Add shape and order options to wrap multi dimensional device arrays. 

Here is an implementation from cuML SVM:
https://github.com/tfeher/cuml/blob/97d2c00d538a2799db7b42b584b8006aee1633ed/python/cuml/utils/numba_utils.py#L145-L185

**Comment by kkraus14** [comment]
Closing as we have agreed to reduce scope of RMM to remove array functionality.

**Comment by jakirkham** [comment]
For future readers, please see issue ( https://github.com/rapidsai/rmm/issues/180 ) for context.
