### ISSUE TITLE
[FEA] Update to spdlog 1.12 and fmt 10

### ISSUE THREAD

**Issue by kkraus14** [rapidsai/rmm#1356]
Conda-forge has an ongoing migration in moving the pinning to spdlog 1.12 and fmt 10: https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/main/recipe/migrations/fmt10.yaml

An attempt was made to build the RMM 23.08 tests with those versions here https://github.com/conda-forge/librmm-feedstock/pull/58, but it fails due to a compilation issue (that doesn't look to have RMM code in the trace 🙃).

As the migrator continues to run, other packages will only be built with spdlog 1.12 / fmt 10 where it will cause problems in solving environments if there isn't builds of RMM (and other RAPIDS packages) with spdlog 1.12 + fmt 10.

**Comment by kkraus14** [comment]
Issue seems to be this: https://github.com/gabime/spdlog/issues/2856

**Comment by harrism** [comment]
Thanks for alerting us to this @kkraus14 . Looks like we need to wait for a fix in spdlog and then adopt the fixed version.

**Comment by kkraus14** [comment]
Got the fix merged upstream in spdlog in https://github.com/gabime/spdlog/pull/2901.

Will backport that to a patch for the conda-forge 1.12 build as well as a patch for rapids-cmake to unblock this.
