### ISSUE TITLE
[FEA] Add a pinned memory resource

### ISSUE THREAD

**Issue by jrhemstad** [rapidsai/rmm#136]
**Is your feature request related to a problem? Please describe.**

There's currently no memory resource for allocating pinned memory (e.g., `cudaHostAlloc`). 

**Describe the solution you'd like**

There should be a `pinned_memory_resource`. 

**Additional context**
Inspired by https://github.com/rapidsai/cudf/pull/2872#issuecomment-535702380

**Comment by UmashankarTriforce** [comment]
I would like to work on this issue. May I know more details on this issue?

**Comment by jrhemstad** [comment]
You can look at the [`cuda_device_resource`](https://github.com/rapidsai/rmm/blob/branch-0.10/include/rmm/mr/cuda_memory_resource.hpp) as an example. 

The `pinned_memory_resource` should be similar to this, but use `cudaHostAlloc` and `cudaFreeHost` instead of `cudaMalloc/cudaFree`. 

Then update the tests to test the new resource: https://github.com/rapidsai/rmm/blob/branch-0.10/tests/mr/mr_tests.cpp#L88

**Comment by UmashankarTriforce** [comment]
Alright thanks for the information! I'll work on it and send a PR :smile:

**Comment by jakirkham** [comment]
This was done in PR ( https://github.com/rapidsai/rmm/pull/272 ), right?

**Comment by jrhemstad** [comment]
> This was done in PR ( #272 ), right?

The difference is in a `host_memory_resource` vs. a `device_memory_resource`. Pinned memory (like managed) is kind of an oddball in that it can be host or device memory.

**Comment by jakirkham** [comment]
Oh, I didn't realize pinned memory could be treated like device memory. Had assumed it was just page locked host memory. Is that not right? What am I missing here?

**Comment by harrism** [comment]
It is just that, but CUDA devices are able to access it directly. 
https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#page-locked-host-memory

**Comment by jakirkham** [comment]
Would it make sense to use `pool_memory_resource` with a `pinned_memory_resource` then? Or am I getting carried away? 😅

**Comment by harrism** [comment]
Conceptually yes. However as Jake pointed out in another issue/PR, the problem is we have specific device_memory_resource tests which check that the returned pointer is a device pointer. I think we could actually expand that to instead  just check that the memory is device accessible. To do that we would just check that the type is NOT `cudaMemoryTypeUnregistered`, and then device MRs could be used with device memory, managed memory, or registered (pinned) host memory.

**Comment by harrism** [comment]
Superseded by #618
