### ISSUE TITLE
[FEA] Move error.hpp out of detail

### ISSUE THREAD

**Issue by vyasr** [rapidsai/rmm#1369]
**Is your feature request related to a problem? Please describe.**
Currently the header error.hpp is in the detail directory. However, it contains user-facing error definitions, which should not be coming from a detail header.

**Describe the solution you'd like**
The header should be moved out of the detail directory.

**Describe alternatives you've considered**
None

**Additional context**
There are some pieces of the header (such as the macros) that may not belong in a publicly visible header. If so, we may need to refactor a bit to avoid exposing those.

**Comment by lamarrr** [comment]
i'd like to take on this once triaged

**Comment by harrism** [comment]
@lamarrr go for it, your help is welcome! I have been making related changes lately (part of #1417). Note that step one is to search all of RAPIDS repos for uses of the detail functions and if any exist, then we have to do a first PR like 1417 that removes nothing and adds public API versions of the functions. Then PRs to update the RAPIDS repos that use the detail functions / types to the new public functions / types should be submitted and merged before a final PR that removes the old detail functions / types. This is the only way to avoid breaking downstream builds.

**Comment by lamarrr** [comment]
@harrism  there is no detail namespaced type/function in the error.hpp header. so I suppose it should be okay to move them out to a public header and leave the internal macros in the detail folder.

**Comment by harrism** [comment]
That's good. There are 5 files across cuDF, cuGraph and RAFT that `#include <rmm/detail/error.hpp>` that will need to be fixed quickly once the file is moved.

**Comment by harrism** [comment]
@lamarrr I think you can consider this triaged. If you open your PR after today, you should target `branch-24.04` as we are entering burndown for 24.02 tonight (no new non-urgent PRs once burndown starts). See https://docs.rapids.ai/maintainers

**Comment by lamarrr** [comment]
> @lamarrr I think you can consider this triaged. If you open your PR after today, you should target `branch-24.04` as we are entering burndown for 24.02 tonight (no new non-urgent PRs once burndown starts). See https://docs.rapids.ai/maintainers

noted!

**Comment by lamarrr** [comment]
Once merged, I'll refractor the upstream repost to use the public API
