### ISSUE TITLE
[FEA] Disable doxygen documentation publication

### ISSUE THREAD

**Issue by vyasr** [rapidsai/rmm#1372]
**Is your feature request related to a problem? Please describe.**
After #1324 the C++ APIs of rmm are documented within the Sphinx documentation along with the Python APIs. As a result, there is no longer a need for publication of the doxygen docs. However, they were left in place to allow easy comparison during the remainder of the 23.12 development cycle.

**Describe the solution you'd like**
We should stop publishing the doxygen docs before the release.

**Comment by ajschmidt8** [comment]
Linking this comment in particular that identify the necessary follow-up tasks

https://github.com/rapidsai/rmm/pull/1324#pullrequestreview-1710741054

**Comment by harrism** [comment]
Hope you don't mind, I'm assigning you @ajschmidt8 and @vyasr. Do you think it's reasonable to finish this in 24.02? We can push to 24.04 if not.

**Comment by vyasr** [comment]
Yup assigning us is fine. We've already stopped building the doxygen HTML, so I think we should be good to go for this release. Perhaps a website update is still needed though, @ajschmidt8 should I modify https://github.com/rapidsai/docs/pull/464 to just remove rmm and get that merged, then come back to cudf when we remove it?

**Comment by harrism** [comment]
@ajschmidt8 @vyasr is this going to happen in 24.04 or should I move to 24.06?

**Comment by ajschmidt8** [comment]
As far as I can tell, this was completed in the PRs below:

- https://github.com/rapidsai/rmm/pull/1415
- https://github.com/rapidsai/docs/pull/478

@vyasr, any remaining items here? or can we close it? I think that should be everything.

**Comment by ajschmidt8** [comment]
Confirmed with Vyas offline that it is complete. Closing.
