### ISSUE TITLE
[BUG] rmm.finalize not releasing memory (pool mode)

### ISSUE THREAD

**Issue by ayushdg** [rapidsai/rmm#144]
**Describe the bug**
Calling `rmm.finalize()` after rmm has been initialized in pool mode should/used to free up the memory pool. This no longer happens.

**Steps/Code to reproduce bug**
```
import rmm
from rmm import rmm_config as rmm_cfg

rmm_cfg.use_pool_allocator = True
rmm.initialize()
```
Pool allocated with 1/2 the cpu memory
```
 NVIDIA-SMI 410.104      Driver Version: 410.104      CUDA Version: 10.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:3B:00.0 Off |                    0 |
| N/A   38C    P0    27W /  70W |   7669MiB / 15079MiB |      0%      Default 
```

```
rmm.finalize()
```

Gpu memory usage is still 1/2 gpu memory.
```
| NVIDIA-SMI 410.104      Driver Version: 410.104      CUDA Version: 10.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:3B:00.0 Off |                    0 |
| N/A   43C    P0    28W /  70W |   7669MiB / 15079MiB |      0%      Default |
```

**Expected behavior**
Gpu memory should be freed 

**Environment details (please complete the following information):**
 - Environment location: Conda
 - Method of RMM install: Conda install nightly rmm=0.10.*
librmm-0.10.0a191007
rmm-0.10.0a191007
 - Please run and attach the output of the `rmm/print_env.sh` script to gather relevant environment details

**Additional context**

**Comment by harrism** [comment]
Hmmm, it appears now that RMM uses `memory_resource`s it initializes the pool memory resource but never finalizes it...

See https://github.com/rapidsai/rmm/blob/7f368705c8adced83e5c54195dff46e8dbbfc1d1/src/rmm.cpp#L60-L86

We need to urgently fix this before 0.10 code freeze.

CC @felipeblazing
