### ISSUE TITLE
Deprecate rmm::polymorphic_allocator::resource and remove that functionality after deprecation

### ISSUE THREAD

**Issue by harrism** [rapidsai/rmm#1453]
A search shows that this function is unused in RAPIDS outside of RMM tests and so I expect it is completely unused.

**Comment by miscco** [comment]
Closing this in favor of #1455 where we just add a `get_upstream_resource` method that will be consistent throughout all memory adaptors

**Comment by harrism** [comment]
Reopening because `polymorphic_allocator::resource()` still exists and doesn't need to now.
