### ISSUE TITLE
[BUG] RMM finalizes before all RMM objects are freed

### ISSUE THREAD

**Issue by shwina** [rapidsai/rmm#148]
## What's the problem?

The following code exits with an `RMM_ERROR_NOT_INITIALIZED` error because `rmm.finalize()` is called *before* the memory underlying the device array is freed.

```
import rmm
import numpy as np
a = rmm.to_device(np.array([1, 2, 3]))
```

```
Traceback (most recent call last):
  File "/home/ashwint/miniconda3/envs/cudf_dev/lib/python3.7/site-packages/numba/utils.py", line 746, in _exitfunc
    f()
  File "/home/ashwint/miniconda3/envs/cudf_dev/lib/python3.7/site-packages/numba/utils.py", line 670, in __call__
    return info.func(*info.args, **(info.kwargs or {}))
  File "/home/ashwint/workspace/github/shwina/rmm/python/rmm/rmm.py", line 216, in finalizer
    return librmm.rmm_free(handle, stream)
  File "rmm/_lib/lib.pyx", line 229, in rmm._lib.lib.rmm_free
  File "rmm/_lib/lib.pyx", line 218, in rmm._lib.lib.c_free
  File "rmm/_lib/lib.pyx", line 49, in rmm._lib.lib.check_error
rmm.rmm.RMMError: RMM_ERROR_NOT_INITIALIZED
```

## Why this is happening

We use [atexit](https://docs.python.org/3/library/atexit.html) to ensure that `rmm.finalize()` is called when the Python interpreter shuts down. In `rmm/__init__.py` we have:

```python
atexit.register(finalize)
```

The call to `rmm.to_device` creates a Numba `DeviceNDArray` with a custom "finalizer".

```python
def _array_helper(addr, datasize, shape, strides, dtype, finalizer=None):
    ctx = cuda.current_context()
    ptr = ctypes.c_uint64(int(addr))
    mem = cuda.driver.MemoryPointer(ctx, ptr, datasize, finalizer=finalizer)
    return cuda.cudadrv.devicearray.DeviceNDArray(
        shape, strides, dtype, gpu_data=mem
    )
```

Numba uses (a backported version of) [weakref.finalize](https://docs.python.org/3/library/weakref.html#weakref.finalize) to call this finalizer whenever the object goes out of scope (or at exit, if the objects are still alive during shutdown).

atexit executes functions in the reverse order that they are registered. Since we register `rmm.finalize` with atexit *before* the creation of any device arrays, I was sure that all the objects would be finalized *before* RMM is finalized.

However, Numba creates a dummy `finalize` object [here](https://github.com/numba/numba/blob/master/numba/utils.py#L765-L766) which registers the classmethod [_exitfunc](https://github.com/numba/numba/blob/master/numba/utils.py#L730) with atexit *on import*. `_exitfunc` calls the finalizers of any objects that are still alive at shutdown.

Since numba is imported before `rmm.finalize` is registered with atexit, RMM ends up being finalized before `_exitfunc` is run, which explains the error.

## Possible solutions

1. In [`__init__.py`](https://github.com/rapidsai/rmm/blob/branch-0.10/python/rmm/__init__.py) we could rearrange things so that numba is imported *after* registering `rmm.finalize` with atexit. I don't like this very much since there's still the possibility that the user imports `numba` before `rmm`.

2. We could make our exit function something like this:

```python
def rmm_atexit():
    from numba.utils import finalize  # numba defines its own `weakref.finalize`
    finalize._exitfunc()
    rmm_finalize()

atexit.register(rmm_atexit)
```

**Comment by jrhemstad** [comment]
I recalled this issue: https://github.com/rapidsai/rmm/issues/85

Is this the same problem?

**Comment by shwina** [comment]
Possibly. It looks very similar..
