### ISSUE TITLE
[DOC] Correct active device requirements for deallocation of `device_buffer`, `device_vector` and friends

### ISSUE THREAD

**Issue by wence-** [rapidsai/rmm#1523]
## Report incorrect documentation

Since #1370, it is no longer necessary for the user to ensure that the currently active device matches the device used during allocation for a `device_buffer` when the destructor runs. However, we still say that one must in the README documentation.

Conversely, since the _initialized_ `device_vector` is just a wrapper around a `thrust::device_vector`, those objects _do still_ have the previous restriction that the active device during deallocation must be the same as the active device during allocation (and this must be arranged by the user).

**Comment by harrism** [comment]
Aside: @jrhemstad has suggested that maybe RMM should remove the `rmm::device_vector` alias, because of inconsistencies like this...

**Comment by wence-** [comment]
I think the last time we went through this (https://github.com/rapidsai/rmm/pull/1370#issuecomment-1801135763) we decided (based on usages throughout rapids) that we wouldn't remove it.
