### ISSUE TITLE
[QST]Version matching problem about python3.7+cuda11.6

### ISSUE THREAD

**Issue by sugerkiller** [rapidsai/rmm#1548]
I found that many rmm versions are not suitable for python3.7+cuda11.6, so I tried to install rmm22.08, but the following error occurred：
```
An error occurred while building with CMake.
  Command:
    'E:\Anaconda\envs\gaussian_splatting_ori\Lib\site-packages\cmake\data\bin/cmake.exe' --build . --target install --config Release --
  Install target:
    install
  Source directory:
    D:\Pycharm\cuml\rmm-branch-22.08\rmm-branch-22.08\python
  Working directory:
    D:\Pycharm\cuml\rmm-branch-22.08\rmm-branch-22.08\python\_skbuild\win-amd64-3.7\cmake-build
Please check the install target is valid and see CMake's output for more information.
```
Is this caused by a python version issue?

**Comment by jakirkham** [comment]
We dropped Python 3.7 in 22.04 (~2 years ago) in PR: https://github.com/rapidsai/rmm/pull/982

We did not add CUDA 11.6 until 22.04 with PR: https://github.com/rapidsai/rmm/pull/964

So there is not a version of RMM that supports Python 3.7 + CUDA 11.6 as 22.04 as Python 3.7 was only supported before that release and CUDA 11.6 starting in that release and later

More generally it is worth noting that [Python 3.7 has already reached EOL]( https://devguide.python.org/versions/ )
