### ISSUE TITLE
[FEA] Cython wrappers/extension types for `device_buffer` and `device_scalar`

### ISSUE THREAD

**Issue by shwina** [rapidsai/rmm#156]
Add Cython bindings for `device_buffer` and `device_scalar` and expose them as Cython extension types.

**Comment by jakirkham** [comment]
So I guess `device_buffer` is done with PR ( https://github.com/rapidsai/rmm/pull/163 ). Is `device_scalar` still needed?

**Comment by shwina** [comment]
It's not clear to me yet whether or not we will need an `rmm.DeviceScalar` extension type. I recall @kkraus14 and I having a brief discussion about it and we figured we could probably get by just working with `rmm:device_scalar` directly in Cython.

So for now, I'd say we can close this issue out and open a new one for `DeviceScalar` if it becomes necessary
