### ISSUE TITLE
[DOC] Add documentation for usage with CPM

### ISSUE THREAD

**Issue by pauleonix** [rapidsai/rmm#1594]
## Report needed documentation

**Report needed documentation**
As a header-only library RMM is a prime candidate for usage with the CMake Package Manager (CPM). CPM includes headers as system headers by default when using the short-hand notation (https://github.com/cpm-cmake/CPM.cmake/pull/449):
```cmake
CPMAddPackage("gh:rapidsai/rmm@24.06.00")
```
While this is not problematic for the RMM headers themselves (as far as I know), the `SYSTEM` property seems to be added to CCCL as well which causes it to be of lower priority than the version of CCCL included with the CUDA SDK which in turn can cause compilation errors (See [this remark in the CCCL README.md](https://github.com/NVIDIA/cccl/blob/82d74afed1c24ec0a1933d138adc70a2b55971b7/README.md?plain=1#L137-L138)). What works is to use the full notation (which annoyingly has the opposite default concerning `SYSTEM`):
```cmake
CPMAddPackage(
  NAME rmm
  VERSION 24.06.00
  GITHUB_REPOSITORY rapidsai/rmm
)
```

CCCL could also do better about documenting this issue (I plan to write an issue there next), but at least they use the full notation in their [example](https://github.com/NVIDIA/cccl/blob/82d74afed1c24ec0a1933d138adc70a2b55971b7/examples/example_project/CMakeLists.txt#L31-L35).

**Steps taken to search for needed documentation**
Read the README.md

**Comment by harrism** [comment]
Hi @pauleonix thanks for reporting this. We would welcome a PR if you are interested in submitting one.
