### ISSUE TITLE
[BUG] Consistently define equality test for adaptors

### ISSUE THREAD

**Issue by vyasr** [rapidsai/rmm#1619]
**Describe the bug**
While reviewing https://github.com/rapidsai/cudf/pull/16187/files, I noticed a change to how `equals` is defined for the stream checking mr. This rang a bell, so [I looked for similar behavior in rmm](https://github.com/search?q=repo%3Arapidsai%2Frmm%20%22cast%20%3D%3D%20nullptr%22&type=code). We turn out to be a bit inconsistent in whether adaptors can be considered equal if their upstreams are equal even if the adaptors themselves are not. I don't think it's terribly important to be able to perform this comparison, so it's not surprising that nobody has reported any issues here yet, but we should aim to make sure that we're making the same decision everywhere.

**Comment by harrism** [comment]
Unless `cuda::mr` namespace adds a concept for adaptors, then we will have to change the semantics of equality completely anyway. See https://github.com/orgs/rapidsai/projects/60?pane=issue&itemId=46738196

**Comment by vyasr** [comment]
Feel free to close this issue if you'd prefer to just track in #1402

**Comment by harrism** [comment]
Good idea, let's track in #1402.
