### ISSUE TITLE
[FEA] device_scalar.set_value()

### ISSUE THREAD

**Issue by devavret** [rapidsai/rmm#166]
**Is your feature request related to a problem? Please describe.**
`device_scalar` needs a `set_value` method

**Describe the solution you'd like**
```c++
  void set_value(T value) {
    auto status = cudaMemcpyAsync(buff.data(), &value, sizeof(T),
                             cudaMemcpyDefault, buff.stream());
    if (cudaSuccess != status) {
      throw std::runtime_error{"Device memcpy failed."};
    }
    status = cudaStreamSynchronize(buff.stream());
    if (cudaSuccess != status) {
      throw std::runtime_error{"Stream sync failed."};
    }
  }
```

**Describe alternatives you've considered**
Using `device_scalar.get()` and setting the value using the returned pointer. This has two side effects:
1. The copy doesn't happen in the stream set in the underlying `device_buffer`
2. The value setting code is duplicated on the client side wherever it's needed.

**Additional context**
This is needed for https://github.com/rapidsai/cudf/pull/3068

**Comment by cwharris** [comment]
Taking a look.

**Comment by cwharris** [comment]
So far we have:
```
T value() const {
T *get() noexcept { ... }
T const *get() const noexcept { ... }
```
@devavret 's proposed addition is
```
 void set_value(T value) { ... }
```
Do we want consistency between host=>device device=>host copy naming? What if we did either of these two instead:
```
T get_value() const { ... }
void set_value(T value) const { ... }
```
or
```
T value() const { ... }
void value(T value) const { ... }
```

**Comment by harrism** [comment]
Why not `void set(T value);`  (And why would set be `const`)?

**Comment by cwharris** [comment]
It wouldn't be const. I was typing too fast.

As for `void set(T value);`, I dislike `set` because it is not isomorphic to `get`, which returns a pointer to device memory. The method we're introducing is more inversely related to `value(T)`

**Comment by harrism** [comment]
I see. I prefer the name `set_value`, then. And either keep `value` or call it `get_value`. Alternatively rename `value` to `pointer` or `get_pointer`. @jrhemstad ?

**Comment by cwharris** [comment]
`device_scalar::get` is similar to `std::unique_ptr::get`, in that both are immutable and return a pointer to the memory they represent. Just an observation.

**Comment by jrhemstad** [comment]
I guess `get` should be renamed to `data` in corollary to `std::vector::data`. Then we can have `value` and `set_value`.

**Comment by cwharris** [comment]
Merged!
