### ISSUE TITLE
[BUG] pool_memory_resource with pinned_memory_resource fails to allocate full capacity

### ISSUE THREAD

**Issue by AKSoftCode** [rapidsai/rmm#1664]
**pool_memory_resource with pinned_memory_resource fails to allocate full capacity**
Hi,

I have encountered an issue when using `pinned_memory_resource` with `pool_memory_resource` in RMM. The pool is unable to allocate its full capacity, failing on the second large allocation even when the total requested memory is equal to the pool's max size.

Steps to reproduce:

1. Create a `pinned_memory_resource`
2. Create a `pool_memory_resource` using the `pinned_memory_resource`, with both initial and max size set to 64MB
3. Attempt to allocate two 32MB blocks

Expected behavior:
Both 32MB allocations should succeed, as they fit within the 64MB max pool size.

Actual behavior:
The first 32MB allocation succeeds, but the second fails with an error indicating that the max pool size has been exceeded.

Example code:

```
TEST(PinnedPoolTest, InitialAndMaxPoolAllcoateMemory)
{
  EXPECT_NO_THROW([]() {
    constexpr size_t max_pool_size = 1024 * 1024 * 64; //64MB
    constexpr size_t block_size = 1024 * 1024 * 8;
    constexpr size_t num_blocks = max_pool_size / block_size;
    rmm::mr::pinned_memory_resource pinned_mr{};
    pool_mr mr(pinned_mr, 1000192, max_pool_size);

    for(size_t i = 0; i < num_blocks; ++i) {
      mr.allocate(block_size);
    }
    
  }());
}
```

**Comment by harrism** [comment]
I just tested on a V100 with CUDA 12.2 and your test above passes. Can you provide full details of the system on which if fails?

**Comment by AKSoftCode** [comment]
I am using NVIDIA GeForce RTX 4090 with CUDA Version: 12.5.

Please find below logs:

Logs:
```
[ RUN      ] PinnedPoolTest.InitialAndMaxPoolAllcoateMemory
unknown file: Failure
C++ exception with description "std::bad_alloc: out_of_memory: RMM failure at:/home/abkhairnar/Workspace/rmm/include/rmm/mr/device/pool_memory_resource.hpp:257: Maximum pool size exceeded" thrown in the test body.
```

**Comment by harrism** [comment]
OK, this reproduces. BTW, you don't need `EXPECT_NO_THROW`, as gtests fail if there is an uncaught exception.

```
TEST(PinnedPoolTest, InitialAndMaxPoolAllocateMemory)
{
  constexpr size_t max_pool_size = 1024 * 1024 * 64;  // 64MB
  constexpr size_t block_size    = 1024 * 1024 * 8;
  constexpr size_t num_blocks    = max_pool_size / block_size;
  rmm::mr::pinned_memory_resource pinned_mr{};
  pool_mr mr(pinned_mr, 1000192, max_pool_size);

  for (size_t i = 0; i < num_blocks; ++i) {
    mr.allocate(block_size);
  }
}```

**Comment by harrism** [comment]
OK, this is simple fragmentation. The reason is because you set your max size to exactly the size you want to allocate, but your initial size is smaller than any block you want to allocate. The pool is not a virtual memory manager, so when it grows, it grows by allocating another block. You can't merge the blocks allocated from upstream, so you have fragmentation.

This is not a bug, it's simply a limitation. The advice is to always set your pool initial size to a large fraction (50% or more) of the maximum size.

`cudaMallocAsync` does use the CUDA low level virtual memory API and therefore does not suffer from this "pool growth" fragmentation.
