### ISSUE TITLE
[BUG] Bad documentation link for device_scalar

### ISSUE THREAD

**Issue by Kh4ster** [rapidsai/rmm#1680]
When typing "rmm device scalar" on Google, the first link is https://docs.rapids.ai/api/librmm/24.02/classrmm_1_1device__scalar which is a "Page Not Found".

Shouldn't it automatically redirect to https://docs.rapids.ai/api/rmm/stable/librmm_docs/data_containers/#_CPPv4I0EN3rmm13device_scalarE ?

**Comment by harrism** [comment]
Thanks @Kh4ster. I'm going to close this for now as the docs.rapids.ai site and indexing issues are known and being worked on. This is not an RMM docs content issue.
