### ISSUE TITLE
[BUG] Doc build failures due to cuda-python namespace rewrite

### ISSUE THREAD

**Issue by wence-** [rapidsai/rmm#1698]
**Describe the bug**

Recently, the low-level cuda-python bindings were reorganised (see nvidia/cuda-python#137). Since the documentation is not versioned, and we cross-link a reference to `cudaCpuDeviceId`, it no longer resolves and the doc build breaks.

We should update the reference.

**Comment by leofang** [comment]
Hmmm this is unexpected as we meant to keep things fully backward compatible. The old modules still exist. @wence- do you have a CI log for the doc build issue that we can take a look at?

**Comment by charlesbluca** [comment]
> do you have a CI log for the doc build issue that we can take a look at?

Here's an example:

https://github.com/rapidsai/rmm/actions/runs/11248565164/job/31274194449

In particular the failure is

```
/__w/rmm/rmm/python/rmm/docs/docstring of rmm.pylibrmm.device_buffer.DeviceBuffer.prefetch:10: WARNING: py:attr reference target not found: cuda.cudart.cudaCpuDeviceId
```

**Comment by wence-** [comment]
> Hmmm this is unexpected as we meant to keep things fully backward compatible. The old modules still exist. [@wence-](https://github.com/wence-) do you have a CI log for the doc build issue that we can take a look at?

Although the modules are backwards compatible, the intersphinx mapping only has the new module names in it.

**Comment by leofang** [comment]
> Although the modules are backwards compatible, the intersphinx mapping (objects.inv) only has the new module names in it.

Yeah seems to be the case
```shell
$ python -m sphinx.ext.intersphinx https://nvidia.github.io/cuda-python/objects.inv | grep cudaCpuDeviceId
    cuda.bindings.runtime.cudaCpuDeviceId                                            : module/runtime.html#cuda.bindings.runtime.cudaCpuDeviceId
```
and it seems to be a known limitation of Sphinx with aliased objects (maybe https://github.com/sphinx-doc/sphinx/issues/10794 & https://github.com/sphinx-doc/sphinx/issues/10151 are relevant). 

We'll keep an eye on it, if it breaks too widely we'll need to figure out a workaround.
