### ISSUE TITLE
[FEA] Remove usage of fmt

### ISSUE THREAD

**Issue by vyasr** [rapidsai/rmm#1717]
Currently rmm has some usage of the fmt library. While fmt is convenient, it causes us significant headaches due to the need to keep our fmt dependency in sync with conda-forge, and because fmt's support for header-only usage makes it very easy to accidentally leak its symbols into public DSO symbol tables (which can cause serious runtime issues if multiple libraries do this with incompatible symbols, e.g. with wheels). Most of RAPIDS's fmt usage comes transitively via spdlog, so not exposing spdlog symbols in public APIs (see https://github.com/rapidsai/build-planning/issues/104) is sufficient to remove a public fmt dependency, but rmm is a special case because it also has direct usage of fmt. Fortunately, fmt can be replaced relatively easily with `std::snprintf` in the short term, and with std::format in the future [when we upgrade to building with C++20](https://github.com/rapidsai/build-planning/issues/113). We should replace all existing use cases of fmt so that we can remove our public reliance on the library.

**Comment by harrism** [comment]
So, for example in this code: 

```
logger_->info("allocate,{},{},{}", ptr, bytes, fmt::ptr(stream.value()));
```

I assume it is sufficient to just drop the usage of `fmt::ptr(stream.value()))` and instead manually format the pointer with snprintf?

I'm trying to remember what this is for: https://github.com/rapidsai/rmm/blob/dbae8c08b0bed1d14ff1b5fe1bc5332b0c175cf8/include/rmm/logger.hpp#L141-L142

It was added by @bdice in #1177
