### ISSUE TITLE
[FEA] Allow setting `pool_size` with human-readable string

### ISSUE THREAD

**Issue by shwina** [rapidsai/rmm#173]
It would be nice to be able to set the `initial_pool_size` with a string like `"500mb"` or `"2gb"` as opposed to integer sizes like 500000000. We could vendor the code Dask uses to accomplish this:

https://github.com/dask/dask/blob/31af7f7040643c447a72c87a8f12457094ec15ff/dask/utils.py#L1171

**Comment by harrism** [comment]
@shwina still relevant?

**Comment by shwina** [comment]
Yes - it's a nice to have. Also probably `good first issue` and labeled as such :)
