### ISSUE TITLE
[DOC] Python API

### ISSUE THREAD

**Issue by jakirkham** [rapidsai/rmm#176]
## Report needed documentation

This may very well exist and I'm just having trouble finding it. Also am aware there is ongoing work here. So may be asking for something that is still in progress, in which case that context would be very helpful. 🙂

**Report needed documentation**

Am looking for Python documentation about the API and intended usage.

**Steps taken to search for needed documentation**

Looked at [the stable]( https://docs.rapids.ai/api/rmm/stable/ ) and [the nightly]( https://docs.rapids.ai/api/rmm/nightly/ ) docs. These appear to be the C++ API though. Not exactly sure how it relates to the Python API though.

**Comment by harrism** [comment]
There are Python docs in readme.md. Is that sufficient?

**Comment by kkraus14** [comment]
Python docs are now published. Closing this.
