### ISSUE TITLE
[QST] __reduce__ implementation of DeviceBuffer includes pointer

### ISSUE THREAD

**Issue by jakirkham** [rapidsai/rmm#179]
**What is your question?**

Currently the `DeviceBuffer` implementation includes a `__reduce__` method. However this appears to include a pointer as part of the data. I'm a little confused as to how this is expected to work. In particular what happens when one uses `pickle.dump` to write the object to disk and read it later? Also what happens if it is pickled and shipped to a machine that doesn't have access to this pointer? Any thoughts on these use cases?

https://github.com/rapidsai/rmm/blob/71b7f35db3b193d30271b8966a43787c61ed6656/python/rmm/_lib/device_buffer.pyx#L26-L27

cc @kkraus14 @shwina

**Comment by kkraus14** [comment]
This is erroneous. We should likely just return a `bytes` object or `bytearray` object. And allow reconstructing the DeviceBuffer from that.

**Comment by jakirkham** [comment]
That seems reasonable. What about dropping this method in the short term?

**Comment by jakirkham** [comment]
Ok added PR ( https://github.com/rapidsai/rmm/pull/189 ) to drop `__reduce__` for now. We can revisit implementing this later.

**Comment by jakirkham** [comment]
Have reimplemented pickling behavior for `DeviceBuffer` using `bytes` as an intermediate representation in PR ( https://github.com/rapidsai/rmm/pull/258 ).
