### ISSUE TITLE
[QST] Dropping `device_array`, etc.?

### ISSUE THREAD

**Issue by jakirkham** [rapidsai/rmm#180]
**What is your question?**

Currently we have some functions `device_array`, `device_array_like`, etc. that all live in Numba. Am curious whether it makes sense to keep these.

AIUI it was designed to supply downstream libraries with an interface that let's them get an array of bytes that they can use as they wish. However it appears cuDF is moving away from them in favor of the newer and simpler `DeviceBuffer`. ( https://github.com/rapidsai/cudf/pull/3254 )

If `__cuda_array_interface__ ` is added to `DeviceBuffer` ( https://github.com/rapidsai/rmm/pull/177 ), we will easily be able to build any array object we want from it anyways.

Plus `DeviceBuffer` is lower maintenance for us.

Not to mention it is orders of magnitude faster for us to construct a `DeviceBuffer` (see short example below).

What are our thoughts on segueing away from `device_array`, `device_array_like`, etc. towards `DeviceBuffer`?

```python
In [1]: import rmm                                                              

In [2]: rmm.reinitialize(pool_allocator=True, 
   ...:                  initial_pool_size=int(2**30))                          
Out[2]: 0

In [3]: %timeit rmm.device_array((10,), dtype="u1")                             
32.2 µs ± 93.7 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)

In [4]: %timeit rmm.DeviceBuffer(size=10)                                       
341 ns ± 1.52 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
```

**Comment by kkraus14** [comment]
cc @dantegd how big of an impact would this have on cuML if we remove the numba compatible APIs?

**Comment by dantegd** [comment]
It is not possible to drop it or cuML will simply just not work at all for 0.11. Our roadmap has adopting `DeviceBuffer` early in 0.12

**Comment by dantegd** [comment]
Just linked the issue I had opened some time ago to track this for cuML

**Comment by jakirkham** [comment]
Mainly raised to see if there was interest. 😉 Agree dropping them in the 0.12 release may make more sense.

Given this, should we add a `DepreciationWarning`?

**Comment by dantegd** [comment]
I don't think a `DeprecationWarning` would be a good idea. Literally every algorithm in cuML would throw a deprecation warning for internal use of `DeviceArray` that would have nothing to do with the user.

**Comment by harrism** [comment]
Some background. I gave RMM a numba-compatible Python API because when I created RMM, I needed to make sure that ALL device memory allocation in cuDF used the pool allocator.  At that stage, cuDF allocated all memory for columns on the Python side using Numba `device_array`, and then passed the device pointer into C++ via the bindings.  So I needed a way to change the allocator used by Numba. Since Numba doesn't have pluggable memory management (see https://github.com/numba/numba/issues/3247) I basically had to spoof the Numba API.

I would be happy to eliminate this API. However: `rmm::device_buffer` in C++ is NOT the same thing. `device_buffer` is an untyped buffer in device memory. It's just an RAII wrapper around an RMM allocation.  Numba `device_array` is much more than that.  Note there's also `rmm::device_vector` which is just a typedef of a `thrust::device_vector` with a custom allocator that uses RMM. `device_vector` is a *typed* array in device memory, similar to `std::vector`.

**Comment by jakirkham** [comment]
Thanks for the background. That all makes sense.

As to creating meaningful arrays from `DeviceBuffer`, it should be possible to use `__cuda_array_interface__` to construct a CuPy (or other) array from it that we can call `.view(...)` and `.reshape(...)` to cast and shape the array as needed. So am not too worried about recovering this functionality through other means.

**Comment by harrism** [comment]
I don't think we can remove it until everything is switched over to libcudf++ APIs.

**Comment by jakirkham** [comment]
Yep agreed. As mentioned earlier, mainly wanted to see if people were on-board with this change. Sounds like you are, which is great. 🙂

Thus far it is sounding like this makes sense for 0.12 as both cuDF and cuML are working on moving to `DeviceBuffer` by then. Does that assessment sound right to everyone?

**Comment by jakirkham** [comment]
Does this still seem reasonable for 0.12? If so, should we be tracking this somehow?

**Comment by harrism** [comment]
Suggest assigning someone to negotiate with all dependent libraries to determine if and when to remove it. @jakirkham do you want to be that someone?

**Comment by gmarkall** [comment]
I'm hoping that once the [Numba Enhancement Proposal for External Memory Management Plugins](https://github.com/gmarkall/nbep-7) is completed / merged, it will remove the need for any code in RMM that creates Numba arrays (e.g. `rmm.device_array()`, etc.)

In my [NBEP 7 branch of RMM](https://github.com/gmarkall/rmm/tree/grm-numba-nbep-7) I have deleted the functions that create these Numba arrays - instead, all arrays that Numba creates should use data allocated from the RMM pool via the RMM External Memory Management plugin (prototype implemented at https://github.com/gmarkall/rmm/blob/grm-numba-nbep-7/python/rmm/rmm.py#L161-L216)

**Comment by jakirkham** [comment]
Now that PR ( https://github.com/rapidsai/rmm/pull/317 ) and PR ( https://github.com/rapidsai/cudf/pull/5042 ) are in. It should be possible for downstream libraries to switch to using Numba directly (instead of using these RMM helper functions), which in turn should allow us to drop the helper functions.

**Comment by harrism** [comment]
@jakirkham do you know what downstream libraries use those APIs?

**Comment by jakirkham** [comment]
Ah I meant downstream in RAPIDS. I’m assuming they are not used by third parties (as they are likely building cuDF or CuPy objects instead). Though maybe that is not a safe assumption? Do you think we need a depreciation cycle first?

**Comment by harrism** [comment]
If it's just in rapids we can just do a search and replace. :)

**Comment by jakirkham** [comment]
I've put up PRs to fix cuML and cuGraph. Could use another look if anyone has a chance 🙂

xref: https://github.com/rapidsai/cuml/pull/2336
xref: https://github.com/rapidsai/cugraph/pull/913

**Comment by harrism** [comment]
I guess it would be safe to remove these APIs from RMM now?
