### ISSUE TITLE
[BUG] New DeviceBuffer has invalid shape

### ISSUE THREAD

**Issue by quasiben** [rapidsai/rmm#183]
While the DeviceBuffer implements the `__cuda_array_interface__` the shape is invalid:

```python
In [10]: rmm.DeviceBuffer(10).__cuda_array_interface__
Out[10]:
{'data': (0, False),
 'shape': (<cyfunction __Pyx_CFunc_size__t____DeviceBuffer___to_py.<locals>.wrap at 0x7fe75d6b5f60>,),
 'strides': (1,),
 'typestr': '|u1',
 'version': 0}
```

cc @jakirkham

**Comment by quasiben** [comment]
apologies, I was didn't have the latest update.

**Comment by quasiben** [comment]
Sorry, for the back and forth.  The `shape` is incorrect:


```python
In [15]: rmm.DeviceBuffer(10).__cuda_array_interface__
Out[15]:
{'data': (0, False),
 'shape': (0,),
 'strides': (1,),
 'typestr': '|u1',
 'version': 0}
```

shape should be `(10,)`

**Comment by jakirkham** [comment]
We just made this change ( https://github.com/rapidsai/rmm/pull/182 ) can you please retest once there are nightlies?

**Comment by jakirkham** [comment]
Ah actually there is a syntax error here too. The keyword must also be specified. Please try this...

```python
rmm.DeviceBuffer(size=10).__cuda_array_interface__
```

**Comment by jakirkham** [comment]
@kkraus14, what do you think about either forcing keyword arguments or switching the order of them in [`__cinit__`]( https://github.com/rapidsai/rmm/blob/8c1a5c4178d36f423a4db43b490a55f1a44f4099/python/rmm/_lib/device_buffer.pyx#L12 )?

**Comment by shwina** [comment]
Perhaps `DeviceBuffer(data=None, size=None)`, where if only `data` is provided, and it is an integer, it's interpreted as the size of the new allocation to be made?

**Comment by quasiben** [comment]
Thanks @jakirkham, with `size=` the shape is correct.  @shwina do you want to leave this issue open for your suggestion  or file another one ?

**Comment by shwina** [comment]
Thanks @quasiben! I think here is fine for continued discussion

**Comment by kkraus14** [comment]
@shwina What situations do we construct the `DeviceBuffer` by passing a pointer?

Unless we want to make `DeviceBuffer` able to handle constructing from host inputs, I don't see a strong reason to change the signature. I imagine we'd want to do that with a higher level `Buffer` object that could be backed by a `DeviceBuffer` or other GPU memory under the hood, where if a host object is passed we copy it to device memory using `DeviceBuffer`.

@shwina should we move the `Buffer` class from cuDF to RMM? I think it more naturally lives here.

**Comment by jakirkham** [comment]
As to the signature, the point is users like Ben and myself (and likely others in the future) mainly want to allocate a fixed sized buffer. So passing a `ptr` wouldn’t even occur to us. We would assuming we could pass the size first. However this is not the case as it takes a `ptr` first. So a keyword argument is needed for this common case, but users will easily miss this as it is not intuitive. The result is users can easily create an invalid `DeviceBuffer`. It would be good to fix this. I would suggest one of the following:

1. Flip the constructor argument order so size comes first
2. Force only keyword arguments so passing a positional argument fails
3. Take `*args` and `**kwargs` that are parsed in some resonable way similar to what Ashwin has suggested
4. Move the `ptr` case into a factory function/static method

**Comment by jrhemstad** [comment]
>Unless we want to make DeviceBuffer able to handle constructing from host inputs

Just a drive-by comment. `rmm::device_buffer` automatically handles construction from a pointer to either host or device memory.

**Comment by kkraus14** [comment]
> Just a drive-by comment. `rmm::device_buffer` automatically handles construction from a pointer to either host or device memory.

Yea we use it internally in our `Buffer` class, but unsure if we wanted to have that exposed through the `DeviceBuffer` class as this class isn't user facing whereas the `Buffer` class is.

**Comment by jakirkham** [comment]
> As to the signature, the point is users like Ben and myself (and likely others in the future) mainly want to allocate a fixed sized buffer. So passing a `ptr` wouldn’t even occur to us. We would assume we could pass the `size` first. However this is not the case as it takes a `ptr` first. So a keyword argument is needed for this common case, but users will easily miss this as it is not intuitive. The result is users can easily create an invalid `DeviceBuffer`. It would be good to fix this. I would suggest one of the following:
> 
> 1. Flip the constructor argument order so `size` comes first
> 2. Force only keyword arguments so passing a positional argument fails
> 3. Take `*args` and `**kwargs` that are parsed in some resonable way similar to what Ashwin has suggested
> 4. Move the `ptr` case into a factory function/static method

To move things forward here, added PR ( https://github.com/rapidsai/rmm/pull/188 ), which implements option 2. Not to say we can't change to a different option. Simply it is easy to add and improves usability.
