### ISSUE TITLE
[FEA] Add flag to use RMM with CuPy in reinitialize

### ISSUE THREAD

**Issue by jakirkham** [rapidsai/rmm#191]
**Is your feature request related to a problem? Please describe.**

It would be useful to hook into CuPy's memory allocator and have it use RMM under-the-hood. This would ensure when users mix CuPy and cuDF that only one memory allocator is in use for managing the memory allocated by both.

**Describe the solution you'd like**

To make this simple for users, it would be handy to have a flag (like `use_rmm_with_cupy`) in `rmm.reinitialize` that would hook RMM into CuPy's allocator under-the-hood. As `rmm.reinitialize` is already being used in workflows to enable the RMM memory pool and set its initial size, this should be a relatively small change for users already doing this.

**Describe alternatives you've considered**

Alternatives might be a global function from RMM that users run. Or RMM might supply an allocator API analogous to CuPy's (though this could be done in support of the ask here too).

**Additional context**

It's not uncommon for users to work with libraries like CuPy and cuDF in conjunction. However being able to manage memory and avoid OOM becomes a bit complex in these cases. To simplify things, it would help to push all allocations through one memory manager (like RMM) to make it easier to understand where the memory is coming from. This would be a nice step in this direction.

Some related discussion in issue ( https://github.com/cupy/cupy/issues/2635 ). Also [CuPy docs]( https://docs-cupy.chainer.org/en/latest/reference/memory.html#changing-memory-pool ) on changing the allocator used.

**Comment by jakirkham** [comment]
(Not sure how we got a `doc` label. Should be `enhancement` 😉)

**Comment by jakirkham** [comment]
cc @madsbk @pentschev @quasiben

**Comment by madsbk** [comment]
Should I add a `rmm.reinitialize(..., use_rmm_with_cupy=False)` argument to RMM that sets the cupy allocator like in https://github.com/rapidsai/dask-cuda/pull/194?
@kkraus14 @harrism @jrhemstad?

**Comment by jakirkham** [comment]
That's what I'm thinking. Though agree we should check with others to see what they think of this idea. 🙂

**Comment by kkraus14** [comment]
@jakirkham I'm not a fan of the flag on the reinitialize function. Imagine we wanted to add Numba and PyTorch in the future, are those then two additional kwarg flags?

I'm more in favor of it being explicit function calls or even more in favor of it being implicit.

**Comment by jakirkham** [comment]
Honestly I don't have strong feelings on the approach. If we would prefer something else like `rmm.enable_alloc_backends` (function name can be workshopped), that would be fine.

There is some value gained in keeping this compact given this is something we will effectively to any notebook they have, but it may not matter much as long as we have that documented well with examples (users can then copy-paste).

Side note: I think what Mads is proposing is explicit (users must opt-in to enable it). It's just a flag, not a function. Though please let me know if I'm missing something here.
