### ISSUE TITLE
[BUG] -Werror=catch-value made warnings as errors, then build failed.

### ISSUE THREAD

**Issue by kaigai** [rapidsai/rmm#213]
It happened during software build of cuDF, and reported at #3613 of rapidsai/cudf.
Then @harrism suggested to move this report here.

**Describe the bug**

During the cuDF module build from the source code, it generates terrible amount of compilation errors, like:
```
/home/kaigai/anaconda3/envs/cudf_dev/include/rmm/rmm.hpp: In instantiation of 'rmmError_t rmm::alloc(T**, size_t, cudaStream_t, const char*, unsigned int) [with T = char; size_t = long unsigned int; cudaStream_t = CUstream_st*]':
/home/kaigai/repo/cudf/cpp/custrings/strings/../regex/../util.inl:96:29:   required from 'T* device_alloc(size_t, cudaStream_t) [with T = char; size_t = long unsigned int; cudaStream_t = CUstream_st*]'
/home/kaigai/repo/cudf/cpp/custrings/strings/replace_backref.cu:155:93:   required from here
/home/kaigai/anaconda3/envs/cudf_dev/include/rmm/rmm.hpp:139:3: error: catching polymorphic type 'class std::exception' by value [-Werror=catch-value=]
   } catch(std::exception e) {
```
Although I could not check all the error message (build script had been generated error message for 20 minutes...), it looks to me c/c++ compiler detected a warning related to catch exceptions, and a compiler option: `-Werror=catch-value` treated it as error.

**Steps/Code to reproduce bug**

https://github.com/rapidsai/cudf/blob/branch-0.12/CONTRIBUTING.md#script-to-build-cudf-from-source

We followed the steps described above.
`make -j` kicks a series of build chains, then raised this problem.

**Environment overview (please complete the following information)**

- OS: CentOS 8 with latest packages
- gcc-8.2.1-3.5.el8.x86_64
- cuda-nvcc-10-1-10.1.243-1.x86_64
- cmake-3.14.5-1.fc29.x86_64
    - RHEL8/CentOS8 distributed cmake-3.11, so we picked up from Fedora29
- boost-devel-1.66.0-6.el8.x86_64
- boost169-devel-1.69.0-4.el8.x86_64

**Comment by jrhemstad** [comment]
Duplicate with https://github.com/rapidsai/rmm/issues/205
