### ISSUE TITLE
[FEA] Method to copy `device_buffer` to host

### ISSUE THREAD

**Issue by jakirkham** [rapidsai/rmm#216]
**Is your feature request related to a problem? Please describe.**

Currently `device_buffer` is able to construct itself using memory on the host. It would be useful to do the opposite. Namely have a method to copy data back to the host in some buffer.

**Describe the solution you'd like**

A method like `copy_to_host` that  returns something (maybe `std::string`?) that has a copy of the data from the `device_buffer` now on the host.

**Describe alternatives you've considered**

Users could probably do this themselves using `device_buffer` directly.

**Additional context**

This would be helpful not only at the C++ level, but also in Python where we would want an analogous feature (maybe `tobytes`?).

cc @kkraus14 @shwina

**Comment by jrhemstad** [comment]
The biggest impediment to this would be what would this return? `std::string` isn't really appropriate. Neither is `std::vector<char>`. So it probably requires creating a new class in RMM like `host_buffer`, which opens a sizable can of worms, similar to the issues I described here: https://github.com/rapidsai/rmm/pull/141#issuecomment-537951066

**Comment by harrism** [comment]
Well, the expedient thing would be to add a method like:

```
device_buffer::copy_to_host( void* host_buffer);
```

It's a kind of halfway-between-C-and-C++ solution that basically is just a wrapper around cudaMemcpy. The user is responsible for allocating and owning `host_buffer` to the size returned by `device_buffer::size()`.

**Comment by jakirkham** [comment]
If it's non-trivial to add in the C++ layer, we can workaround its absence in the Python layer. Just would be nice to have a plan for alignment so they don't get too far apart.

**Comment by harrism** [comment]
Look, I'm OK with adding my suggested API (which is trivial) because it is congruent with the constructor that takes a void pointer (as you mentioned in the initial request, @jakirkham ). But I want to give @jrhemstad the opportunity to oppose that approach if he has a strong opinion.

**Comment by jrhemstad** [comment]
> Look, I'm OK with adding my suggested API (which is trivial) because it is congruent with the constructor that takes a void pointer (as you mentioned in the initial request, @jakirkham ). But I want to give @jrhemstad the opportunity to oppose that approach if he has a strong opinion.

I have no problem with a free function that looks like:
```c++
void to_host(rmm::device_buffer const& b, void * host_buffer);
```
It would be a pretty minimal wrapper around `cudaMemcpy`, but if people think that's useful, then I've no quarrel with that.

**Comment by jakirkham** [comment]
That would be great. Would it be possible for it to perform error handling as well?

**Comment by jrhemstad** [comment]
> That would be great. Would it be possible for it to perform error handling as well?

Yes, it can throw an exception if `host_buffer` is null or if the `cudaMemcpy` fails.

**Comment by harrism** [comment]
@jakirkham how about submitting a PR? :)

**Comment by jakirkham** [comment]
Happy to. Submitted PR ( https://github.com/rapidsai/rmm/pull/219 ) to start the conversation.

Am a bit rusty on my C++, so advice welcome there. In particular could use some help on figuring out where tests should go.
