### ISSUE TITLE
[BUG] Need to sync to default stream in `DeviceBuffer`

### ISSUE THREAD

**Issue by jakirkham** [rapidsai/rmm#263]
**Describe the bug**

Currently we are not synchronizing on the default stream in `DeviceBuffer`. According to the discussion in issue ( https://github.com/numba/numba/issues/4933 ) and write-up in PR ( https://github.com/numba/numba/pull/5162 ) we should be doing this.

**Comment by jrhemstad** [comment]
Note that just synchronizing the default stream isn't sufficient to ensure that a `device_buffer` is safe to use. See my comment: https://github.com/numba/numba/pull/5162#issuecomment-579904027

**Comment by jakirkham** [comment]
This was effectively solved by PR ( https://github.com/rapidsai/rmm/pull/309 ).
