### ISSUE TITLE
[FEA] Automatically set CuPy memory allocator to RMM

### ISSUE THREAD

**Issue by pentschev** [rapidsai/rmm#271]
**Is your feature request related to a problem? Please describe.**
cuDF calls to CuPy may incur in additional `cudaMalloc`s if we don't explicitly set it to use the RMM allocator when it is set to pool mode.

**Describe the solution you'd like**
If we set RMM to pool mode, RMM should automatically set CuPy's memory allocator to RMM.

**Describe alternatives you've considered**
The current alternative in Dask is to do as below, but it is very error-prone.
```python
client.run(cudf.set_allocator, pool=True, allocator="default")
client.run(cupy.cuda.set_allocator, rmm.rmm_cupy_allocator)
```

**Comment by pentschev** [comment]
cc @kkraus14 @quasiben @jrhemstad

**Comment by jakirkham** [comment]
It sounds like we are stuck with the first line unless we solve issue ( https://github.com/rapidsai/dask-cuda/issues/233 ). Or am I missing something?

As to the second line, the challenge is this would be a surprise to the user who hasn't intentionally changed this. Perhaps we can add a flag to `rmm.set_allocator` to additionally replace CuPy's allocator (thus folding this into the first line). Thoughts?

**Comment by jrhemstad** [comment]
> Perhaps we can add a flag to rmm.set_allocator to additionally replace CuPy's allocator (thus folding this into the first line). Thoughts?

That sounds kinda clunky. Continuing with that we'd end up adding a parameter for replacing every potential CUDA Python library that has a pool allocator.

**Comment by kkraus14** [comment]
We could also make this implicit under the `cudf.set_allocator` call, implicit only on RMM reinitialization with a pool, or just implicit for RMM in general. I'm in favor of option 2 currently with possibly moving it to option 3 in the future.

**Comment by jakirkham** [comment]
>> Perhaps we can add a flag to rmm.set_allocator to additionally replace CuPy's allocator (thus folding this into the first line). Thoughts?
>
> That sounds kinda clunky. Continuing with that we'd end up adding a parameter for replacing every potential CUDA Python library that has a pool allocator.

If we do it in general, true. However we are pretty closely tied to CuPy. Perhaps it's fine for this to be the exception 😉

In the long run, we might consider a plugin architecture to make this library agnostic.

**Comment by harrism** [comment]
@pentschev still relevant?

**Comment by jakirkham** [comment]
I think PR ( https://github.com/rapidsai/cudf/pull/4351 ) may have addressed this. Basically cuDF configures CuPy to use the same RMM allocator it uses on `import cudf`

**Comment by kkraus14** [comment]
Going to close this and someone can open a new issue if they'd like to make the case for making RMM usage for CuPy / Numba automatic when doing `import rmm`.
