### ISSUE TITLE
[FEA] Create device_memory_resource adaptor to Thrust pool resources

### ISSUE THREAD

**Issue by jrhemstad** [rapidsai/rmm#276]
**Is your feature request related to a problem? Please describe.**

Thrust provides a memory pool/caching sub-allocator resource. It would be nice to test performance comparisons of this sub-allocator against the CNMEM pool and any other pools (such as the custom one @harrism is working on https://github.com/rapidsai/rmm/pull/162)

https://github.com/thrust/thrust/blob/master/thrust/mr/disjoint_pool.h

Since the design of `thrust::memory_resource` and `rmm::device_resource` are largely compatible, it should be fairly straightforward to create an `rmm::device_memory_resource` that wraps the Thrust pool resources. 

**Describe the solution you'd like**

Create new `rmm::device_memory_resource`s:

- `rmm::thrust_synchronized_pool` to wrap [`synchronized_pool_resource`](https://github.com/thrust/thrust/blob/master/thrust/mr/sync_pool.h)
- `rmm::thrust_unsynchronized_pool` to wrap [`unsynchronized_pool_resource` ](https://github.com/thrust/thrust/blob/master/thrust/mr/pool.h)

**Additional Context**

One issue that may impact the Thrust pool performance is that they are not stream aware.

Furthermore, the Thrust pool resources are only available in CUDA 10.1 and above.

**Comment by jrhemstad** [comment]
I believe we actually want to use the [`disjoint_pool`s](https://github.com/thrust/thrust/blob/master/thrust/mr/disjoint_pool.h).

The documentation describes this as:

> The disjoint version of the pool resources uses a separate upstream memory resource, \p Bookkeeper, to allocate memory necessary to manage the cached memory. There may be many reasons to do that; the canonical one is that \p Upstream allocates memory that is inaccessible to the code of the pool resource, which means that it cannot embed the necessary information in memory obtained from \p Upstream; for instance, \p Upstream can be a CUDA non-managed memory  resource, or a CUDA managed memory resource whose memory we would prefer to not migrate back and forth between host and device when executing bookkeeping code.

> This is not the only case where it makes sense to use a disjoint pool resource, though. In a multi-core environment it may be beneficial to avoid stealing cache lines from other cores by writing over bookkeeping information embedded in an allocated block of memory. In such a case, one can imagine wanting to use a disjoint pool where both the upstream and the bookkeeper are of the same type, to allocate memory consistently, but separately for those two purposes.

The regular `*pool_resource`s store bookkeeping information within the memory blocks themselves. This doesn't work for device memory because it would require accessing device memory from host code.

With a `disjoint_pool` resource, it uses a separate upstream for allocating the actual blocks (device memory) and another for allocating bookkeeping information (host memory).

**Comment by harrism** [comment]
@jrhemstad think this is still needed?

**Comment by jrhemstad** [comment]
> @jrhemstad think this is still needed?

There's no pressing need for it, no. However, since Thrust also implements a very similar interface to `std::pmr::memory_resource` I think it makes sense to eventually have wrappers around their resources.

**Comment by harrism** [comment]
Only if it is requested. Otherwise it's just code to maintain without a need.

**Comment by jrhemstad** [comment]
> Only if it is requested. Otherwise it's just code to maintain without a need.

I don't see any harm in keeping the issue open as a point of reference.

**Comment by harrism** [comment]
Closing. The issue serves as a point of reference when closed, too.
