### ISSUE TITLE
[FEA] Create `device_memory_resource` to wrap CUB caching allocator

### ISSUE THREAD

**Issue by jrhemstad** [rapidsai/rmm#290]
**Is your feature request related to a problem? Please describe.**

Similar to https://github.com/rapidsai/rmm/issues/276, it would be straightforward and interesting to add a `device_memory_resource` that wraps [CUB's caching allocator](https://nvlabs.github.io/cub/structcub_1_1_caching_device_allocator.html#a00d55d2fb072b4675ab49090a28ba715).

**Describe the solution you'd like**

Create `cub_memory_resource` to wrap `cub::CachingDeviceAllocator`.

**Comment by harrism** [comment]
@jrhemstad can/should this be closed?

**Comment by jrhemstad** [comment]
Closing. No longer needed. https://github.com/dmlc/xgboost/issues/5861#issuecomment-654433991 showed that the CUB caching allocator is much slower than the pool.
