### ISSUE TITLE
[BUG] Errors compiling benchmark after PR 287

### ISSUE THREAD

**Issue by trxcllnt** [rapidsai/rmm#293]
Seeing compilation errors building RMM after https://github.com/rapidsai/rmm/pull/287. Seems to be caused by the [`cuda_event_timer` destructor](https://github.com/rapidsai/rmm/blob/6eec65a16a12c1dcf14423ee1522cf0f5f2ae94e/benchmarks/synchronization/synchronization.cpp#L63) throwing.

<details>
<summary>Click to expand compilation errors</summary><pre>
FAILED: benchmarks/CMakeFiles/RANDOM_ALLOCATIONS_BENCH.dir/synchronization/synchronization.cpp.o 
/usr/local/bin/ccache /usr/bin/g++-7   -Igoogletest/install/include -Igooglebenchmark/install/include -I/usr/local/cuda-10.1/targets/x86_64-linux/include -Iinclude -I../../../../include -I../../../../ -I../../../../src -I../../../../benchmarks -Werror -O3 -DNDEBUG -fPIE   -std=gnu++11 -MD -MT benchmarks/CMakeFiles/RANDOM_ALLOCATIONS_BENCH.dir/synchronization/synchronization.cpp.o -MF benchmarks/CMakeFiles/RANDOM_ALLOCATIONS_BENCH.dir/synchronization/synchronization.cpp.o.d -o benchmarks/CMakeFiles/RANDOM_ALLOCATIONS_BENCH.dir/synchronization/synchronization.cpp.o -c ../../../../benchmarks/synchronization/synchronization.cpp
../../../../benchmarks/synchronization/synchronization.cpp: In destructor 'cuda_event_timer::~cuda_event_timer()':
../../../../benchmarks/synchronization/synchronization.cpp:24:44: error: throw will always call terminate() [-Werror=terminate]
       throw std::runtime_error("CUDA error");                     \
                                            ^
../../../../benchmarks/synchronization/synchronization.cpp:63:3: note: in expansion of macro 'CUDA_TRY'
   CUDA_TRY(cudaEventRecord(stop, stream));
   ^~~~~~~~
../../../../benchmarks/synchronization/synchronization.cpp:24:44: note: in C++11 destructors default to noexcept
       throw std::runtime_error("CUDA error");                     \
                                            ^
../../../../benchmarks/synchronization/synchronization.cpp:63:3: note: in expansion of macro 'CUDA_TRY'
   CUDA_TRY(cudaEventRecord(stop, stream));
   ^~~~~~~~
../../../../benchmarks/synchronization/synchronization.cpp:24:44: error: throw will always call terminate() [-Werror=terminate]
       throw std::runtime_error("CUDA error");                     \
                                            ^
../../../../benchmarks/synchronization/synchronization.cpp:64:3: note: in expansion of macro 'CUDA_TRY'
   CUDA_TRY(cudaEventSynchronize(stop));
   ^~~~~~~~
../../../../benchmarks/synchronization/synchronization.cpp:24:44: note: in C++11 destructors default to noexcept
       throw std::runtime_error("CUDA error");                     \
                                            ^
../../../../benchmarks/synchronization/synchronization.cpp:64:3: note: in expansion of macro 'CUDA_TRY'
   CUDA_TRY(cudaEventSynchronize(stop));
   ^~~~~~~~
../../../../benchmarks/synchronization/synchronization.cpp:24:44: error: throw will always call terminate() [-Werror=terminate]
       throw std::runtime_error("CUDA error");                     \
                                            ^
../../../../benchmarks/synchronization/synchronization.cpp:67:3: note: in expansion of macro 'CUDA_TRY'
   CUDA_TRY(cudaEventElapsedTime(&milliseconds, start, stop));
   ^~~~~~~~
../../../../benchmarks/synchronization/synchronization.cpp:24:44: note: in C++11 destructors default to noexcept
       throw std::runtime_error("CUDA error");                     \
                                            ^
../../../../benchmarks/synchronization/synchronization.cpp:67:3: note: in expansion of macro 'CUDA_TRY'
   CUDA_TRY(cudaEventElapsedTime(&milliseconds, start, stop));
   ^~~~~~~~
../../../../benchmarks/synchronization/synchronization.cpp:24:44: error: throw will always call terminate() [-Werror=terminate]
       throw std::runtime_error("CUDA error");                     \
                                            ^
../../../../benchmarks/synchronization/synchronization.cpp:69:3: note: in expansion of macro 'CUDA_TRY'
   CUDA_TRY(cudaEventDestroy(start));
   ^~~~~~~~
../../../../benchmarks/synchronization/synchronization.cpp:24:44: note: in C++11 destructors default to noexcept
       throw std::runtime_error("CUDA error");                     \
                                            ^
../../../../benchmarks/synchronization/synchronization.cpp:69:3: note: in expansion of macro 'CUDA_TRY'
   CUDA_TRY(cudaEventDestroy(start));
   ^~~~~~~~
../../../../benchmarks/synchronization/synchronization.cpp:24:44: error: throw will always call terminate() [-Werror=terminate]
       throw std::runtime_error("CUDA error");                     \
                                            ^
../../../../benchmarks/synchronization/synchronization.cpp:70:3: note: in expansion of macro 'CUDA_TRY'
   CUDA_TRY(cudaEventDestroy(stop));
   ^~~~~~~~
../../../../benchmarks/synchronization/synchronization.cpp:24:44: note: in C++11 destructors default to noexcept
       throw std::runtime_error("CUDA error");                     \
                                            ^
../../../../benchmarks/synchronization/synchronization.cpp:70:3: note: in expansion of macro 'CUDA_TRY'
   CUDA_TRY(cudaEventDestroy(stop));
   ^~~~~~~~
cc1plus: all warnings being treated as errors
</pre></details>

**Comment by trxcllnt** [comment]
Comment from jrhemstad in slack:
> I'm not sure we even need cuda_event_timer in RMM

**Comment by jrhemstad** [comment]
I may have spoken too soon about not needing cuda_event_timer. If an asynchronous allocator is being benchmarked, then it's necessary to do a stream sync to ensure correct timings.

The easier, more direct fix would be to just remove the `CUDA_TRY` from the destructors.
