### ISSUE TITLE
[FEA] Investigate C++ Logging libraries

### ISSUE THREAD

**Issue by jrhemstad** [rapidsai/rmm#295]
**Is your feature request related to a problem? Please describe.**

It would be nice to use a dedicated logging library for RMM logging. 

**Describe the solution you'd like**

Investigate C++ logging library solutions.

**Comment by harrism** [comment]
Some links: 

Some analysis:
https://kjellkod.wordpress.com/2015/06/30/the-worlds-fastest-logger-vs-g3log/

g3log: https://github.com/KjellKod/g3log
spdlog: https://github.com/gabime/spdlog
glog: https://github.com/google/glog

I think that we should discuss requirements / desires. Speed is important, but also simplicity, and very important is impact on installation of RMM (I think we would like RMM to become header-only). I think a logger that is header-only and mature, so we could vendor it directly into RMM rather than submoduling it. 

I haven't thought about whether overall latency is important, as discussed in the first link above.

**Comment by jrhemstad** [comment]
> I think a logger that is header-only and mature, so we could vendor it directly into RMM rather than submoduling it. 

Agreed. I generated table to summarize these things

|        |         Header only?         | C++ Version | GitHub stars (maturity) | License            | Notes                              |
|:------:|:----------------------------:|:-----------:|-------------------------|--------------------|------------------------------------|
| spdlog | Yes (static lib reccomended) |    C++11    | 7800                    | MIT                | More features than we really need. |
|  g3log |              No              |    C++14    | 550                     | Public Domain      |                                    |
|  glog  |              No              | ?           | 3600                    |                    |                                    |
| loguru |              Yes             | C++11       | 831                     | Public Domain      |                                    |
|  plog  |              Yes             |    C++03    | 819                     | Mozilla Public 2.0 | Very simple                        |

Some requirements I've been thinking about:
- Simple
- Header-only
- Output to CSV
- Info we care about logging:
   - Allloc/Free + Size
   - Timestamp
   - Pool state (total free, in used)
   - Call stack?

**Comment by harrism** [comment]
Info: also # active allocations and allocation strategy-specific data like fragmentation metrics could come in handy.

**Comment by jakirkham** [comment]
I believe Glog is BSD-3-Clause. It included some third-party BSD-3-Clause code as well.

As to minimum C++ version it may C++03 or C++98, but wasn't sure either. Raised issue ( https://github.com/google/glog/issues/527 ) to see if they could provide some guidance 🙂

**Comment by teju85** [comment]
I've seen some logging implementations need access to `argc` and `argv` for initializing the underlying "state" of the logger. IMO, that's particularly not great for libraries, and also especially when trying to access those libraries via python layer. Probably, this would also be something that we'd need to consider.

**Comment by jrhemstad** [comment]
> I've seen some logging implementations need access to `argc` and `argv` for initializing the underlying "state" of the logger. IMO, that's particularly not great for libraries, and also especially when trying to access those libraries via python layer. Probably, this would also be something that we'd need to consider.

Yikes, yeah, that would definitely disqualify any logging library that required something like this.

**Comment by harrism** [comment]
spdlog chosen and implemented in #297. Closing.
