### ISSUE TITLE
[FEA][Discussion] Make RMM header-only and remove initialization/finalize

### ISSUE THREAD

**Issue by jrhemstad** [rapidsai/rmm#301]
**Is your feature request related to a problem? Please describe.**

Currently, RMM is built and distributed as a shared library object. 

The only functionality not exposed entirely in a header are the [`Manager`](https://github.com/rapidsai/rmm/blob/branch-0.13/src/memory_manager.cpp#L97)/[`Logger`](https://github.com/rapidsai/rmm/blob/branch-0.13/src/memory_manager.cpp#L36) objects. 

The logger will soon be superseded by the work in https://github.com/rapidsai/rmm/pull/297 and will be removed.

Which leaves the `Manager` object. The purpose of the `Manager` is primarily to implement the functionality of `rmmInitialize` and `rmmFinalize`. Today, `rmmInitialize` allows selecting how memory gets allocated (CUDA, managed, pool, etc.) and pool parameters (size of initial pool). This made sense back when RMM only had 3 different ways of allocating memory. However, with the new design of RMM that makes use of `device_memory_resource`s, it no longer makes sense to provide `rmmInitialize/rmmFinalize` APIs. 

Briefly, [`device_memory_resource`](https://github.com/rapidsai/rmm/blob/branch-0.13/include/rmm/mr/device/device_memory_resource.hpp) is a pure virtual base class that defines an interface for allocating/deallocating memory. Classes derive from `device_memory_resource` and implement the `do_allocate/do_deallocate` functions for allocating and freeing memory, e.g., [`cuda_memory_resource`](https://github.com/rapidsai/rmm/blob/branch-0.13/include/rmm/mr/device/cuda_memory_resource.hpp) just uses `cudaMalloc/cudaFree`. 

By having this interface base class, we can pass around any derived type memory resource via a `device_memory_resource*` and call the `allocate/deallocate` virtual functions which will be dispatched to the derived class.  For example,
```c++
void some_function(..., device_memory_resource * mr){
   void * p = mr->allocate(...);
}
```
Any class that derives from `device_memory_resource` can be passed in to `some_function` and then `p` will be allocated using whatever implementation that derived type provides. This allows us to conveniently abstract away the details of memory allocation and easily "plug-in" different allocator implementations without having to change any code in `some_function`. 

RMM also provides a concept of a "default" memory resource. This can be accessed via the [`get_default_resource()` ](https://github.com/rapidsai/rmm/blob/branch-0.13/include/rmm/mr/device/default_memory_resource.hpp#L35) and modified via the [`set_default_resource()`](https://github.com/rapidsai/rmm/blob/branch-0.13/include/rmm/mr/device/default_memory_resource.hpp#L54) APIs. 

By default `get_default_resource()` will return a pointer to an instance of `cuda_memory_resource` which just allocates memory using normal `cudaMalloc/cudaFree`. `set_default_resource()` allows a user to pass a pointer to their own `device_memory_resource` derived class such that future calls to `get_default_resource()` will return a pointer to the custom one. 

Which brings us back to `rmmInitialize`, which calls `Manager::initialize`. Currently, [`manager::initialize`](https://github.com/rapidsai/rmm/blob/branch-0.13/src/memory_manager.cpp#L97) is just a very thin wrapper around constructing one of `cuda_memory_resource`, `managed_memory_resource`, or `cnmem_memory_resource` and setting it to the default with `set_default_resource()`. 

@harrism and I have been working to add several new memory resource implementations:
https://github.com/rapidsai/rmm/pull/162
https://github.com/rapidsai/rmm/pull/297 
https://github.com/rapidsai/rmm/pull/285 
https://github.com/rapidsai/rmm/pull/291 

All of which have their own unique configuration parameters, e.g., some pool implementations have more knobs than just "initial pool size". As such, it will no longer be feasible to try and hide the choice of memory resource behind a simple API like `rmmInitialize`. 

**Describe the solution you'd like**

For the reasons above, I propose that we remove the `rmmInitialize`/`rmmFinalize` APIs all together. Likewise, remove the `Manager`/`Logger` objects. (As an indirect consequence, this would also make RMM a header only library and no longer have a need to distribute a `.so`.)

Instead, _direct_(*) consumers of RMM will be responsible for constructing and managing instances of `device_memory_resource` objects themselves and call `set_default_memory_resource()` accordingly. For example, if you wanted to use the cnmem memory pool implementation:
```c++
auto initial_pool_size = ...;
cnmem_memory_resource mr{initial_pool_size}; // This object needs to stay alive for as long as it is the default resource
set_default_resource(&mr);
```

To be clear, I fully expect direct consumers of RMM (such as cuDF) to provide their own layer of abstraction that manages creating the resources and setting the default. The point is that cuDF provides the layer of abstraction that makes sense for it's direct consumers while other RMM consumers can provide the layer of abstraction that makes sense for their users (such as Spark cuDF). 

Furthermore, for advanced users of libraries that use RMM, it allows managing and setting the default resource to whatever resource they want. This currently isn't possible in cuDF Python because it interfaces only with the `rmmInitialize/finalize` APIs instead of directly with the `device_memory_resource` constructs. This makes it difficult to try new experimental allocators like https://github.com/rapidsai/rmm/pull/162.

(*) By _direct_ consumer, I mean libraries like cuDF, Spark, cuML, etc. Users of cuDF/Spark/cuML would be insulated from these changes.

**Comment by harrism** [comment]
This requires direct consumers of RMM also to not call rmmAlloc and friends. @jrhemstad can you link the issues you filed in other RAPIDS libraries for this purpose here?

I wholeheartedly support this approach. I love working with the memory_resource classes. They provide easy composition to create new allocator strategies; layering to add functionality like logging and thread safety, etc. They are a massive productivity enhancement.

The question is the right way to expose this to Python. For this I think @kkraus14 and @jakirkham should comment.

**Comment by jrhemstad** [comment]
> @jrhemstad can you link the issues you filed in other RAPIDS libraries for this purpose here?

[Deprecate/remove alloc/free in RMM.
](https://github.com/rapidsai/rmm/issues/302)

[cuML](https://github.com/rapidsai/cuml/issues/1720)

[cuDF](https://github.com/rapidsai/cudf/issues/4212)

[cuGraph](https://github.com/rapidsai/cugraph/issues/727)

[cuSpatial](https://github.com/rapidsai/cuspatial/issues/127)

**Comment by jakirkham** [comment]
> The question is the right way to expose this to Python.

On the Python side, I think we are largely using (or trying to use) `rmm.DeviceBuffer`, which wraps the C++ `rmm::device_buffer`.

There may be more work to do to get things off of the `device_array` API ( https://github.com/rapidsai/rmm/issues/180 ). However under-the-hood those also are using `rmm.DeviceBuffer` ( https://github.com/rapidsai/rmm/pull/249 ).

Not sure what libraries are using `rmm_alloc`. [A quick search]( https://github.com/search?l=Cython&q=org%3Arapidsai+rmm_alloc&type=Code ) seems to indicate none?

cc @kkraus14 @dantegd (in case I'm missing things)

**Comment by jrhemstad** [comment]
> > The question is the right way to expose this to Python.
> 
> On the Python side, I think we are largely using (or trying to use) `rmm.DeviceBuffer`, which wraps the C++ `rmm::device_buffer`.
> 
> There may be more work to do to get things off of the `device_array` API ( #180 ). However under-the-hood those also are using `rmm.DeviceBuffer` ( #249 ).
> 
> Not sure what libraries are using `rmm_alloc`. [A quick search](https://github.com/search?l=Cython&q=org%3Arapidsai+rmm_alloc&type=Code) seems to indicate none?
> 
> cc @kkraus14 @dantegd (in case I'm missing things)

I believe @harrism was asking about the right way to expose the `device_memory_resource`s and `get/set_default_resource()` to Python for configuring how the memory of a `device_buffer` actually gets allocated. One of the arguments to a `device_buffer` is a `device_memory_resource`.

**Comment by jakirkham** [comment]
Yeah sorry I missed that somehow.

This is tricky. Thus far most use cases assume RMM is configured. Being able to fall back to some sort of default may help.

We may also want a context manager to configure the `device_memory_resource` used for some block of code to ensure all operations in that block use a different resource than the default. Some of this can be done on the Python level, but a C++ design that keeps this possibility open would help.

**Comment by jrhemstad** [comment]
> Being able to fall back to some sort of default may help.

`get_default_resource()` returns `cuda_memory_resource` by default. I assume that is what you mean? 

> We may also want a context manager to configure the device_memory_resource used for some block of code to ensure all operations in that block use a different resource than the default. Some of this can be done on the Python level, but a C++ design that keeps this possibility open would help.

I'm not clear on what you need from the C++ design to enable this other than the `get/set_default_resource()`.

**Comment by jakirkham** [comment]
Sure. Let's look at this another way 🙂

How would one configure the `device_memory_resource` used by an `rmm::device_buffer`? What would happen if one did not specify a `device_memory_resource` for an `rmm::device_buffer`?

Maybe we can figure out the rest once we know those things 😉

**Comment by jrhemstad** [comment]
> How would one configure the device_memory_resource used by an rmm::device_buffer?

Depending on what resource you want, it would need to be constructed with whatever constructor arguments it expects, e.g., for `cnmem_memory_resource`
```
auto initial_pool_size = ...;
cnmem_memory_resource mr{initial_pool_size}; // This object needs to stay alive for as long as it is the default resource
set_default_resource(&mr);

...

auto buffer = rmm::device_buffer(100, &mr); // set resource explicitly

auto buffer2 = rmm::device_buffer(100); // use default resource returned from `get_default_resource()`

```



> What would happen if one did not specify a device_memory_resource for an rmm::device_buffer?

It already defaults to `get_default_memory_resource()`. 

https://github.com/rapidsai/rmm/blob/750d8654d55fab0b7409846749fb2945318b62e6/include/rmm/device_buffer.hpp#L95

**Comment by harrism** [comment]
Note that in the example, you don't *have* to call `set_default_resource` with the cnmem resource. You would only do that if you want every device_buffer that doesn't set a resource from there on to use that resource.

**Comment by dantegd** [comment]
CC @teju85 @cjnolet for visibility

**Comment by jrhemstad** [comment]
As of https://github.com/rapidsai/rmm/pull/396 the only thing preventing RMM from going fully header-only is CNMeM. I'll create a new issue to deprecate usage of CNMeM. Closing.
