### ISSUE TITLE
[FEA] Deprecate and remove rmm::alloc/free APIs 

### ISSUE THREAD

**Issue by jrhemstad** [rapidsai/rmm#302]
**Is your feature request related to a problem? Please describe.**

RMM provides [`alloc`](https://github.com/rapidsai/rmm/blob/branch-0.13/include/rmm/rmm.hpp#L107) and [`free`](https://github.com/rapidsai/rmm/blob/branch-0.13/include/rmm/rmm.hpp#L192) APIs that mirror traditional `malloc/free` or `cudaMalloc/cudaFree` APIs. This made sense when the only modes of allocation RMM supported was CUDA/managed/cnmem.

However, with the transition to using `device_memory_resource`s, it no longer makes sense to provide `alloc/free` APIs. 

The `free` API is especially problematic as it only accepts the pointer to the allocation to free (it doesn't include the size of the allocation). In contrast, [`device_memory_resource::deallocate`](https://github.com/rapidsai/rmm/blob/branch-0.13/include/rmm/mr/device/device_memory_resource.hpp#L103) expects to be told the size of the allocation to be free'd. This breaks from the traditional `free` API because it makes it much easier to implement efficient pool allocators if you know the size of the allocation at deallocation rather than having to track it through some other means. 

Additionally, best practice in modern C++ is to avoid "raw" alloc/free calls and instead use a RAII construct such as [`rmm::device_buffer`](https://github.com/rapidsai/rmm/blob/branch-0.13/include/rmm/device_buffer.hpp) which makes it trivial to track the allocation size and pass to `deallocate`. 

The only reason we haven't been bitten by this issue so far is because all of the existing resources simply ignore the `bytes` argument in `deallocate`. However, as we continue to add new resources (#162 #297 #285 #291), this will no longer be true. Therefore, in order to prevent problems we should remove the `alloc/free` APIs all together. 

**Describe the solution you'd like**

We should add a drepcation warning to `alloc/free` in the near future and then remove the APIs all together shortly thereafter.

If we're comfortable moving RMM to C++14, we can use the [`[[deprecated]]` attribute ](https://en.cppreference.com/w/cpp/language/attributes/deprecated) which will give a warning at compile time if the function is being used.

Otherwise, we could simply add a print statement to `rmm::alloc/free` warning at runtime that the APIs are deprecated. 

**Describe alternatives you've considered**

Alternatively, alloc/free could track every pointer and it's size in something like a `std::map<void*, size_t>` but that adds complexity and overhead to preserve users of alloc/free that should really just transition to using RAII objects.

**Comment by jakirkham** [comment]
No strong feelings on most of this, but am a big fan of `rmm::device_buffer`. So moving to that (or equivalent RAII objects) sounds good to me 😄

cc @kkraus14 @dantegd (in case you have more thoughts and/or know others that will 😉)

**Comment by harrism** [comment]
> This breaks from the traditional free API because it makes it much easier to implement efficient pool allocators if you know the size of the allocation at deallocation rather than having to track it through some other means.

Can you explain this? I don't see how this eliminates any pool allocator from having to track sizes of active allocations. The user is free to pass an incorrect value for the size (perhaps in attempt to free only part of the allocation. :) ), and the allocator must be able to detect their error.

**Comment by jrhemstad** [comment]
> Can you explain this? I don't see how this eliminates any pool allocator from having to track sizes of active allocations.

Take for example your `hybrid_memory_resource`. In [`do_deallocate(p, bytes)`](https://github.com/rapidsai/rmm/pull/162/files?file-filters%5B%5D=.hpp#diff-ecffef5995b85c54768c5d28c9463716R131) it uses `bytes` to call `get_allocator(bytes)` to return the appropriate resource that was used to allocate that memory in order to free it. This is a common pattern I've seen in several pool implementations.  How else could you do this if `deallocate` isn't told the size of the allocation? 

We can't do the usual trick of storing the size of the allocation in some slack bytes immediately preceding the allocation pointer `p` because `p` points to device memory. If we wanted to read/write to that from the host code of `hybrid_memory_resource` that would incur a host -> device memcpy on allocation and a device -> host memcpy on free. That would be inordinately expensive.

Now then, the implementation of `hybrid_memory_resource` could instead keep something like a `map<void*,size_t>` to map every pointer it's allocated to it's size. But that would also cause a non-trivial amount of overhead and the whole point of pool allocators is to be fast.

Therefore, in order to allow memory resources to be fast and avoid having to track the sizes of allocations internally, they require the caller to tell them how big the allocation was. 

> The user is free to pass an incorrect value for the size (perhaps in attempt to free only part of the allocation. :) ), and the allocator must be able to detect their error.

That's definitely not what the documentation says. 

https://github.com/rapidsai/rmm/blob/branch-0.13/include/rmm/mr/device/device_memory_resource.hpp#L88

>   * `p` must have been returned by a prior call to `allocate(bytes,stream)` on
>   * a `device_memory_resource` that compares equal to `*this`, and the storage
>   * it points to must not yet have been deallocated, otherwise behavior is
>   * undefined.

It is undefined behavior to pass in _anything_ other than a pointer `p` and a size `bytes` returned from a previous call to `p = allocate(bytes)` that hasn't already been deallocated. There is _no_ requirement for the allocator to detect the error. This is the same requirement as [`std::pmr::memory_resource`](https://en.cppreference.com/w/cpp/memory/memory_resource/deallocate).

**Comment by harrism** [comment]
Thanks!  BTW I wasn't arguing against the suggestion in this issue. I just was thinking that in my pool allocator (sub_memory_resource), I need to store the sizes of blocks internally whether they are passed to me or not. So it wasn't obvious at first glance why having the size would make it easier to deallocate.

**Comment by zhangjianting** [comment]
I am in the process of replacing rmm::alloc/free with rmm::device_buffer. A question is that with alloc/free, I can control when to free the allocated memory to  minimize peak memory usage. Is there a way to explicitly destroy device_buffer and release the memory?

**Comment by zhangjianting** [comment]
It seems that I can call the destructor explicitly for this purpose. But this is still a bad choice, as I have learnt in the past?

**Comment by jakirkham** [comment]
Can use RAII to allow it be cleaned up for you like so

```cpp
{
    rmm::device_buffer b(10);
    ...
    // b gets cleaned up here
}
```
