### ISSUE TITLE
[BUG] `device_buffer` default ctor does not call allocate, but dtor calls deallocate

### ISSUE THREAD

**Issue by jrhemstad** [rapidsai/rmm#307]
**Describe the bug**

The [default ctor](https://github.com/rapidsai/rmm/blob/branch-0.13/include/rmm/device_buffer.hpp#L76) for `device_buffer` does not call `allocate`, which is intentional as `mr->allocate(0)` could potentially allocate memory. The `data` pointer is just set to nullptr. 

However, when the destructor is invoked for a default constructed `device_buffer`, it _will_ invoke `mr->deallocate`. This is undefined behavior as it is illegal to call deallocate on something that was not returned from a matching call to `mr->allocate`. 

This also messes up RMM logging as it will show more deallocations than allocations.

**Comment by jakirkham** [comment]
Ah ok! This explains a lot. Thanks for isolating this Jake! 😄
