### ISSUE TITLE
[FEA] Provide a `uninitialized_vector` that doesn't initialize the allocation

### ISSUE THREAD

**Issue by jrhemstad** [rapidsai/rmm#33]
**Is your feature request related to a problem? Please describe.**
`rmm::device_vector` is an alias for a `thrust::device_vector` that uses RMM as the allocator. By default, `thrust::device_vector` will invoke the default constructor for each element in the vector. This is oftentimes unnecessary overhead as it requires invoking a kernel to initialize the elements of the vector.

**Describe the solution you'd like**
Provide `rmm::uninitialized_device_vector` that simply allocates the memory of the specified size and sets the `.size()` appropriately.

See https://github.com/thrust/thrust/blob/master/examples/uninitialized_vector.cu for reference.

**Comment by jrhemstad** [comment]
Alternative name could be `rmm::device_buffer` to indicate that it's just a piece of uninitialized memory that can be used as a buffer.

**Comment by jrhemstad** [comment]
`device_buffer` fills this need.

**Comment by jrhemstad** [comment]
I'm going to reopen this and link it to https://github.com/rapidsai/rmm/issues/120

`device_buffer` provides a half-measure solution, but is not a fully solution because it is still untyped. A full solution would be a typed `device_uvector<T>` class.

**Comment by jrhemstad** [comment]
The reason vector-like classes need to default initialize the contained objects is a result of supporting the dynamic growth that vectors provide. For example:
```
std::vector<foo> f(128);
f.push_back(foo{...}); // This incurs a new allocation and copy
```

Let's assume `vector` initially allocates space for 128 `foo` objects. When adding a new object with `push_back`, it will need to allocate new storage and copy the old `foo`s to the new storage. 

This copy must be done via the copy constructor. If the original `foo` objects weren't default initialized, you would be calling the copy constructor from an uninitialized object and you get undefined behavior. 

This is why a "uninitialized" vector (`uvector`) can only support trivially copyable types (types that can be simply memcpy'd instead of needing to use a copy constructor). I can't think of a usecase for `rmm::device_vector<T>` where `T` isn't trivially copyable. 

There is another option, which would be to provide a new class that doesn't allow dynamic growth (i.e., no `push_back/emplace_back/resize`, etc.). It would have a fixed size to whatever it was set to at construction. Something like a `device_array<T>` that doesn't initialize at construction and doesn't  allow growing larger.

**Comment by harrism** [comment]
My gut feeling is that the former (only trivially copyable T, but still resizeable) would be more useful in RAPIDS. 

Also remember that we need the interface to be different from `thrust::device_vector` in other ways -- namely to take streams in some members where device_vector doesn't.

**Comment by jrhemstad** [comment]
> There's also a third option, which is to adopt both limitations to keep it really simple: only trivially copyable T, not resizeable.

Yeah, that's what I'm planning to start with.
