### ISSUE TITLE
[FEA] add ability to statically link against libcudart

### ISSUE THREAD

**Issue by revans2** [rapidsai/rmm#342]
**Is your feature request related to a problem? Please describe.**
We are trying to fix some issues with packaging the java API for cudf.

nvcc by default will statically link libraries and executables against libcudart.  This prevents a number of problems but the things we really care about are 
1) Not releasing multiple versions of the package each tied to a specific cudart version.
2) avoiding negative interactions with other cuda enabled libraries in the JVM. 

If we can statically link in libcudart, but keep libcuda dynamically linked we can have a single jar that runs on all modern versions of Linux that have a minimum supported cuda driver version.

It also avoids our users having to figure out what version of cudart is installed on a specific host and try to match it. Or what is worse also have to match it with other ML libraries also in the JVM.

**Describe the solution you'd like**
It would be nice to have an option when building rmm that would stop dynamically linking against libcudart and statically link instead.

**Describe alternatives you've considered**
We thought about compiling and shipping N different versions of the libraires and having our customers pick the one that matches what they are using, but that is painful for them.  We thought about having a single package that can pick the version of the libraires it should load based off of the cuda runtime installed, but that would make the released package very large, and in most distributed systems where the code moves to the data the code might actually be larger than the data it was going to process.

**Comment by jakirkham** [comment]
I think we may have discussed this offline, but I believe CMake recently added this option to do this.

https://gitlab.kitware.com/cmake/cmake/-/issues/17559

**Comment by revans2** [comment]
@jakirkham https://gitlab.kitware.com/cmake/cmake/-/issues/17559 is a great feature and we might be able to use it for https://github.com/rapidsai/cudf/issues/4759, but I don't think it is going to help in this situation.  The documentation for it states that 

>   This property has effect only when the ``CUDA`` language is enabled. To
>   control the CUDA runtime linking when only using the CUDA SDK with the
>   ``C`` or ``C++`` language we recommend using the :module:`FindCUDAToolkit`
>   module.

It looks like CMake will link in cudart if there are .cu files compiled as part of the build for a particular dynamic library or executable.  RMM has no .cu files as part of the build.  So the RMM build is using the CUDA language really just to find libcuda and libcudart, the tests use it though. Even if we change one of the files to a .cu for no good reason we would also need to remove libcudart from the linking options because the default for linking is still static linking unless cudart is given as a linking dependency.  If cudart is a dependency it ends up being dynamically linked.

I was able to hack up the build to statically link against cudart with the following patch.

```patch
diff --git a/CMakeLists.txt b/CMakeLists.txt
index ee85019..8a37099 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -152,7 +152,7 @@ endif(USE_NVTX)
 ###################################################################################################
 # - link libraries --------------------------------------------------------------------------------
 
-target_link_libraries(rmm cudart cuda)
+target_link_libraries(rmm cudart_static cuda)
 
 ###################################################################################################
 # - install targets -------------------------------------------------------------------------------
diff --git a/tests/CMakeLists.txt b/tests/CMakeLists.txt
index 4eba631..94db1fa 100644
--- a/tests/CMakeLists.txt
+++ b/tests/CMakeLists.txt
@@ -29,7 +29,7 @@ set(CMAKE_CUDA_STANDARD_REQUIRED ON)
 function(ConfigureTest CMAKE_TEST_NAME CMAKE_TEST_SRC)
     add_executable(${CMAKE_TEST_NAME} ${CMAKE_TEST_SRC})
     set_target_properties(${CMAKE_TEST_NAME} PROPERTIES POSITION_INDEPENDENT_CODE ON)
-    target_link_libraries(${CMAKE_TEST_NAME} gmock gtest gmock_main gtest_main pthread rmm)
+    target_link_libraries(${CMAKE_TEST_NAME} gmock gtest gmock_main gtest_main pthread cudart rmm)
     set_target_properties(${CMAKE_TEST_NAME} PROPERTIES
                             RUNTIME_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}/gtests")
     add_test(NAME ${CMAKE_TEST_NAME} COMMAND ${CMAKE_TEST_NAME})
@@ -128,6 +128,6 @@ set(RANDOM_ALLOCATE_SRC
 
 add_executable(random_allocate ${RANDOM_ALLOCATE_SRC})
 set_target_properties(random_allocate PROPERTIES POSITION_INDEPENDENT_CODE ON)
-target_link_libraries(random_allocate rmm)
+target_link_libraries(random_allocate cudart rmm)
 set_target_properties(random_allocate PROPERTIES
                       RUNTIME_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}/bench")

```

So for this feature to work I think all we need to do is to select based off of some configs if we link against `cudart` or `cudart_static` in RMM we can keep the tests dynamically linking against cudart as it will not cause any issues in either situation.

**Comment by revans2** [comment]
I forgot to add that if this sounds like a good option I am happy to try to come up with a patch to make it work.  If someone else wants an alternative approach I am also happy to give it a try.

**Comment by revans2** [comment]
I put up a PR just because it was simple to do and would let you see what I was thinking.  If we want to go a different route that is fine.
