### ISSUE TITLE
[BUG] Crash with basic_string::_M_construct null not valid on startup

### ISSUE THREAD

**Issue by jlowe** [rapidsai/rmm#344]
**Describe the bug**
Attempting to initialize RMM via `rmmInitialize` with logging configured can cause a crash with the error message: `basic_string::_M_construct null not valid`

**Steps/Code to reproduce bug**
Initialize RMM with logging without setting the RMM_LOG_FILE environment variable.  The issue is this code in the logging resource adaptor:
```
  logging_resource_adaptor(Upstream* upstream, std::string const& filename =
                                                   std::getenv("RMM_LOG_FILE"))
```
Note that `getenv` will return `null` if the environment variable is not set, but `std::string` cannot be constructed with a `null` argument.

**Expected behavior**
Software does not crash on startup with an uncaught exception.

**Comment by jrhemstad** [comment]
Is this a bug? You're enabling logging but not specifying a file to log to. What behavior would you expect instead?

**Comment by jlowe** [comment]
Yes, this is a bug.  Otherwise we're saying it's OK for software to emit `basic_string::_M_construct null not valid" when the user failed to set a required environment variable.  How is the user supposed to diagnose that error?  And will they be pleased with the software when the eventually find out what was wrong?  We can always say, "well, you should have known better."

If we don't think it's the logging adaptor's responsibility to handle this case, then the logging adaptor should not default to blindly referencing an environment variable the user has not set.  It should always take a string argument, and it's the app's responsibility to always produce a valid string.

**Comment by jlowe** [comment]
> What behavior would you expect instead?

I would expect an exception to be thrown by the adaptor with a useful error message like, "RMM logging requested but RMM_LOG_FILE is unset" or something similar.  Then if that bubbles to the top uncaught, at least the user gets a clue as to what they need to do to fix the issue.

**Comment by jrhemstad** [comment]
> then the logging adaptor should not default to blindly referencing an environment variable the user may not have set.

To be fair, this is a highly temporary state of affairs. The only reason it uses an environment variable is because `rmmInitialize` doesn't accept a filename parameter and I didn't want to add one since the whole API is being removed. 

> > What behavior would you expect instead?
> 
> I would expect an exception to be thrown by the adaptor with a useful error message like, "RMM logging requested but RMM_LOG_FILE is unset" or something similar. Then if that bubbles to the top uncaught, at least the user gets a clue as to what they need to do to fix the issue.

Ah, okay, I thought the ask was for "don't throw an exception" as opposed to "this exception message isn't helpful".

I certainly agree that a more helpful error message is necessary.

**Comment by jlowe** [comment]
> The only reason it uses an environment variable is because rmmInitialize doesn't accept a filename parameter and I didn't want to add one since the whole API is being removed.

Understood, and it's that exact scenario that bit us.  We had some unit tests that verified if the Java API to initialize RMM asked for logging that it would do so (and not crash).  Then it started crashing, because RMM used to log to stdout or stderr (I forget which) and no longer does.  Took a bit to track down where the weird error message was coming from, but the fact that it was our logging unit test and it smelled just like https://github.com/rapidsai/cudf/issues/3722 helped track it down faster.

So anyone that was using the old API and logging not to a file is likely to hit this issue.
