### ISSUE TITLE
[BUG] Allocation beyond initial pool size does not reuse freed memory

### ISSUE THREAD

**Issue by davidwendt** [rapidsai/rmm#35]
**Describe the bug**
After allocation pool size of X is consumed (and freed). New memory allocations (and frees) cause additional memory to be allocated from the GPU in increments of X.
Memory allocations/frees below the initial pool size X work fine until a new allocate goes above the initial size. This causes rmm to allocate a new chunk of memory on top of the initial pool size to accommodate the request. Caller frees all memory and requests new memory which again goes over the initial pool size. This causes rmm now to allocate yet another chunk of memory. The first extra chunk is not reused although it has been entirely been freed. There are now 3X of GPU memory allocated though < 2X memory has been requested. Continuing this pattern causes additional chunks of X memory until the GPU resources are used up. 

**Steps/Code to reproduce bug**
Created simple test to show this problem here:
https://github.com/davidwendt/rmmtest/blob/master/explode.cu
The program allocates increasing memory 2 at time (each followed by 2 frees) and requests no more that 4GB total at any one time. Again, all memory is freed almost immediately after allocating.
With an initial pool size set to 4GB, this works well. The rmm allocates 4GB and never goes above.
With an initial pool size set to 2GB, rmm ends up allocating  24GB of GPU memory for the same code.
The intermediate new chunks of memory do not seem to be reused.

**Expected behavior**
Requesting memory beyond the initial pool size should be able to reuse freed memory in the new chunks.

**Environment details (please complete the following information):**
 - Environment location: created on Ubuntu 16.04 desktop
 - Method of RMM install: built from source -- repo for example above has cmake

[rmmenv.txt](https://github.com/rapidsai/rmm/files/2823226/rmmenv.txt)

**Comment by harrism** [comment]
@davidwendt thanks for the careful issue report. 

I experimented with your example for a while and I believe that this is working as expected. CNMem, which is the underlying pool allocator, does not and cannot merge allocations across cudaMalloc boundaries. So even though you are freeing everything before each new allocation, one of each pair of allocations is always bigger than the previously largest-ever-allocation. Once the allocations exceed the initial pool size, this causes the pool to be expanded each time a new larger-than-ever-encountered allocation is encountered.  

When you start with an initial pool of 4GiB, it is larger than the total of all pairs of allocations, so another cudaMalloc is never called.

To verify this, try reversing the list of sizes in your example so the largest is first. This results in just two cudaMalloc calls: one of 2GiB (the pool initial size), and one of 3158384640 bytes (the first size).

**Comment by harrism** [comment]
Closing. Recommend using the default pool size (Which uses 1/2 total GPU memory). Or at least a pool size larger than your largest potential allocation.
