### ISSUE TITLE
[FEA] Include spdlog headers in conda package

### ISSUE THREAD

**Issue by jrhemstad** [rapidsai/rmm#359]
**Is your feature request related to a problem? Please describe.**

The librmm conda package doesn't ship the spdlog headers. This is a problem for anyone who wants to use the `logging_resource_adaptor`.

The spdlog headers currently live in the `thirdparty` dir https://github.com/rapidsai/rmm/tree/branch-0.14/thirdparty/spdlog

**Describe the solution you'd like**
Ship the `spdlog` headers in a way that RMM conda users can access them.

**Comment by rongou** [comment]
Shouldn't the user just install the `spdlog` conda package? https://anaconda.org/conda-forge/spdlog

**Comment by harrism** [comment]
If there's a conda package, does that mean we can just remove the source from RMM, @jrhemstad ?

**Comment by jrhemstad** [comment]
> If there's a conda package, does that mean we can just remove the source from RMM, @jrhemstad ?

I don't like unnecessarily forcing users to use conda if it's not needed. It's perfectly normal in C++ libraries to package header-only libraries along with your own library.

**Comment by jakirkham** [comment]
Sure, but the suggestion here is to include the vendored headers in Conda packages, which is a bit more unnatural.

**Comment by jrhemstad** [comment]
> Sure, but the suggestion here is to include the vendored headers in Conda packages, which is a bit more unnatural.

It wouldn't be unnatural if `spdlog` were just in `rmm/include` instead of the `thirdparty` directory. That's where it lived originally until it moved to `thirdparty`. 

Because it's vendored, as far as any user should be concerned, `spdlog` is _part of_ RMM. 

Perhaps I should just move `spdlog` back to `include` from `thirdparty`.

**Comment by harrism** [comment]
We can't do that, I think NVIDIA policy requires it.

**Comment by harrism** [comment]
Why not just leave them where they are (for from-source builders), and make spdlog a dependency of the RMM conda package?

(Although I still think a submodule or a cmake module make more sense for the C++ side -- it's not hard to update submodules, and it avoids involving the dependency in the git history of the dependent.)

**Comment by jrhemstad** [comment]
> Why not just leave them where they are (for from-source builders), and make spdlog a dependency of the RMM conda package?

Yep, agreed.

**Comment by jakirkham** [comment]
How do we specify to RMM where to look for spdlog today? Or is that something that would still need to be done?

**Comment by jrhemstad** [comment]
> How do we specify to RMM where to look for spdlog today? Or is that something that would still need to be done?

Nothing special. It just expects to be able to find `<spdlog/*>` in the standard include paths.
