### ISSUE TITLE
[BUG] rmm.get_info() removed from python api in v0.15

### ISSUE THREAD

**Issue by benfred** [rapidsai/rmm#390]
**Describe the bug**
The ```rmm.get_info``` function was removed from rmm with this commit: https://github.com/rapidsai/rmm/commit/15a3d5fef6d78b39cc4c04387e8a1772f9596670

We're using this function to view how much memory RMM is currently managing, so that we can manage larger than gpu memory datasets effectively with cudf. 

The README still references this function https://github.com/rapidsai/rmm#memory-info as a way to view memory info managed by rmm , but it doesn't seem to be possible any more.

**Steps/Code to reproduce bug**

call ```rmm.get_info()``` from python

**Comment by jrhemstad** [comment]
Not all resources support the ability to query how much memory was in use, hence why this API was removed.

**Comment by benfred** [comment]
Thanks for the quick response! I just saw the thread in the rapidsdev-rmm room, and think I understand the rationale here.

I'm wondering if we can still expose this functionality, and just throw a 'NotImplementedError' for memory resources that don't have this ability? Alternatively we could add cython bindings for do_get_mem_info and supports_get_mem_info on the memory_resource class once #391 is merged?

**Comment by jakirkham** [comment]
Maybe? cc @shwina

What are you using this feature for?

**Comment by jrhemstad** [comment]
I'm going to close this issue. I opened https://github.com/rapidsai/rmm/issues/415 with a proposed solution/replacement for `get_info`.

**Comment by jrhemstad** [comment]
I'd also note that attempting to allocate too much memory is a recoverable event that throws a `rmm::bad_alloc` exception. That exception can be caught and you can try allocating less memory.
