### ISSUE TITLE
[DOC] Intro guide / FAQ / top use cases

### ISSUE THREAD

**Issue by lmeyerov** [rapidsai/rmm#395]
## Report needed documentation

Happy to help on this one -- we're looking into using & exposing RMM for unified memory / out-of-core cudf/cugraph use within an M-to-N process architecture, and had basic questions that are likely 101 intro docs issues. Maybe a 10 minutes to RMM?

Happy to jump on a call if easier.

**Report needed documentation**

* How do you get the `rmm` associated with `cudf.set_allocator(...)`, just `import rmm; rmm.get_info()`? 

* M-to-N scenarios: Can you have multiple cudf/rmm allocators in the same process for improved isolation? What is the behavior when multiple processes use RMM? Can/should they share RMM? (It sounds like they're fully independent, similar to cuMalloc by diff processes.)

* ... What are the plans around A100 / MIG?

* Introspection: In managed mode, how do you inspect device vs host memory consumption? The current pool/managed config?

* Policies: Is there a way to implement/guide policies like LRU? Can you set a max pool size? Can you set max differently for host vs. device?

* Commands: How do you compact a live pool, just reinitialize? What does that do / any limitations? There is an unclear reference to "finalizing" in the readme

* https://docs.rapids.ai/api/rmm/stable/ seems to be empty - should we be looking elsewhere? We are currently going off of the main `README.md`, https://devblogs.nvidia.com/unified-memory-cuda-beginners/, and a GTC talk from a few years ago on unified memory / RMM

**Comment by jrhemstad** [comment]
>Can you have multiple cudf/rmm allocators in the same process for improved isolation?

Yes.

> What is the behavior when multiple processes use RMM? Can/should they share RMM?

They are independent and cannot be shared. We have no intentions to ever make it so they can be shared among processes. 

> What are the plans around A100 / MIG?

You'll have to be more specific. RMM currently has no plans specific to A100 or MIG. 

> In managed mode, how do you inspect device vs host memory consumption? The current pool/managed config?

This isn't something that can be queried. 

>  Is there a way to implement/guide policies like LRU? 

For managed memory? No. 

> Can you set a max pool size? 

Depends on the resource you're using. 

> Can you set max differently for host vs. device?

There are no host pools yet. 

> How do you compact a live pool, just reinitialize?

No resource supports compaction or defragmentation yet. 

> https://docs.rapids.ai/api/rmm/stable/ seems to be empty

The main page is empty, but if you look at the class documentation you'll find the documentation, e.g., 

https://docs.rapids.ai/api/rmm/stable/classrmm_1_1mr_1_1device__memory__resource.html

**Comment by lmeyerov** [comment]
Thanks, this is a good start!

Some follow-on q's below. I'm guessing these feel frustratingly basic, so again, happy to see about helping w/ a 10min to RMM or 10min to RAPIDS memory management type of doc that covers them.

======


Multiple allocators: ... How?

Multiple processes: ... What does it mean to be independent? What happens during oversubscription, RMM out of memory exceptions, RMM crashes, ...?

MIG/A100: AFAICT, MIG is about supporting a limited level of physical partitioning, both at the compute unit & (I assume) memory level. In terms of OS/driver -> docker -> process -> RMM, will RMM be able to run on a MIG-partitioned unit, esp. in managed mode? Can RMM do the partitioning? How might this look like if there are say 2 jupyter lab docker containers, and several users on each?

Max pool size: What resources can be set & how? (We're thinking more about overall GPU/CPU memory allocation, not explicit hierarchy levels like scratchpad/L1/..)

For answers with "no" (cross-process sharing, LRU policies, memory consumption): Are these roadmapped or explicitly intended to never be doable, punted to some specific non-RMM projects, ...? For compaction.... so what is 'reinitialize' / 'finalize', how do we use them?

**Comment by lmeyerov** [comment]
@kkraus14 Any word? It's still entirely unclear for me (+ others I've discussed this with) on how to use RMM for basic stuff like separate pools and setting bounds.

**Comment by kkraus14** [comment]
This isn't being prioritized currently. If you'd like to contribute I'd suggest just doing it via a PR as a markdown file for now and we can review and request changes as we have bandwidth.

Just to lay some things out though:
- MIG: out of scope of RMM, that's at the GPU driver level and makes a GPU just look / feel like multiple GPUs.
- Multiple processes: out of scope of RMM, another library / project should wrap RMM to provide that functionality if desired.
- Max pool size: we could build memory resource(s) in the future that allow for defining a maximum pool size but we don't currently have this support and it isn't currently planned.
- Multiple allocators: You can create multiple memory resource objects in RMM Python today, but cuDF Python only allows to set a single memory resource as the default resource and all allocations go via the default resource.

**Comment by harrism** [comment]
> Max pool size: we could build memory resource(s) in the future that allow for defining a maximum pool size but we don't currently have this support and it isn't currently planned.

`rmm::mr::pool_memory_allocator` (C++) absolutely supports this, it is an argument to the constructor.

**Comment by kkraus14** [comment]
@harrism he's looking for a pool without a growth policy so that you could specify say 8GB and it throws instead of growing past 8GB

**Comment by jrhemstad** [comment]
> @harrism he's looking for a pool without a growth policy so that you could specify say 8GB and it throws instead of growing past 8GB

Yeah, it already does that: https://github.com/rapidsai/rmm/blob/4110fa0e158e10c1d9db67428771d8dc2d79f6c4/include/rmm/mr/device/pool_memory_resource.hpp#L191

**Comment by kkraus14** [comment]
Got it. This is not yet exposed to Python via the normal APIs. Sounds like some extra motivation to rip out CNMem and move towards the new `pool_memory_resource`

**Comment by lmeyerov** [comment]
yeah we need some way, for cudf / dask_cudf, to cap task resource utilization, and ideally separately for CPU vs GPU consumption. 

Process/task killers seem ~ok for time, but unclear how to do for memory. As-is, best practice for predictability today seems to be 1 user <> nvidia-docker-per-entire-gpu, or slow start of a new cloud VM, which precludes much more interesting like limited bursts over multi-GPUs. RMM internals seem like the path for memory resources, but not yet exposed to python.

Working through TODO list here, still intending to sketch a 10min to RMM (from perspective of general python analyst + python architect usage, not rapids dev team internals.)

**Comment by harrism** [comment]
I think most of the questions here have been answered. I think they are a bit specific to put in a doc, and the README.md is now quite detailed. Closing. Please reopen if you disagree.
