### ISSUE TITLE
[FEA] Replace CFFI bindings with Cython

### ISSUE THREAD

**Issue by harrism** [rapidsai/rmm#40]
We should transition the current Python bindings API to Cython in order
 - to support promoting C++ exceptions up to Python exceptions for better error reporting
 - to match the approach cuDF is taking

**Comment by jakirkham** [comment]
Am curious if this would be implemented in such a way that other users could leverage the Cython API from other Cython libraries.

**Comment by harrism** [comment]
> Am curious if this would be implemented in such a way that other users could leverage the Cython API from other Cython libraries.

Not being a Cython expert, I'm not sure exactly what you mean. However, like CFFI, Cython will give RMM a Python interface alongside its C/C++ interface. Since other Cython libraries can call Python or C/C++ APIs, then yes, you could leverage RMM in other libraries just as you can today.

**Comment by jakirkham** [comment]
Sorry for the delay on following up on this.

Typically what this means is the `.pxd` files (basically Cython's equivalent of headers) are shipped alongside the `.so` (built from Cython's `.pyx` files). There's some useful information in [this doc]( https://cython.readthedocs.io/en/latest/src/userguide/sharing_declarations.html ).

There is a separate question of which functions might be exposed. For example, `cdef` functions (that are possibly declared `nogil`) might be attractive to other Cython developers. OTOH `cpdef` functions might be useful if a Cython interface is beneficial for some cases and a Python interface for others. Other cases may just use `def` functions as these are targeting Python developers, in which case there is no need for `.pxd` files as things just work via the usual `import` mechanisms.

**Comment by harrism** [comment]
I'm out of my depth here. This issue will serve as my introduction to Cython.
