### ISSUE TITLE
[FEA] Deprecate CNMeM

### ISSUE THREAD

**Issue by jrhemstad** [rapidsai/rmm#407]
**Is your feature request related to a problem? Please describe.**

CNMeM is not header-only and requires building a .so, which means RMM cannot be header-only. This could be resolved by just moving CNMeM's implementation to a header, but for all intents and purposes, @harrism's[ `pool_memory_resource`](https://github.com/rapidsai/rmm/blob/branch-0.15/include/rmm/mr/device/pool_memory_resource.hpp) supersedes CNMeM. 

**Describe the solution you'd like**

Deprecate usage of CNMeM in favor of using `pool_memory_resource`. 

**Additional context**
Once we drop CNMeM, RMM can go fully header-only.

**Comment by jakirkham** [comment]
cc @kkraus14 @shwina @quasiben @pentschev

**Comment by harrism** [comment]
We should file issues for any features cnmem supports that pool_memory_resource does not support, and implement them. For example: device-specific (and multidevice) implementation; PTDS (even if it works by synchronizing in cnmem). There may be others.

**Comment by jrhemstad** [comment]
> We should file issues for any features cnmem supports that pool_memory_resource does not support, and implement them. For example: device-specific (and multidevice) implementation; PTDS (even if it works by synchronizing in cnmem). There may be others.

https://github.com/rapidsai/rmm/issues/409 https://github.com/rapidsai/rmm/issues/410

**Comment by harrism** [comment]
Thanks Jake!

**Comment by jakirkham** [comment]
Also cc-ing @rongou
