### ISSUE TITLE
[BUG] RMM logging is slow.

### ISSUE THREAD

**Issue by harrism** [rapidsai/rmm#41]
**Describe the bug**
The RMM log is slow. It was written quickly to get something working but the overhead of using STL for a log is too high and therefore it is off by default.

**Steps/Code to reproduce bug**
Turn on logging in a big app with a lot of alloc/free (e.g. RAPIDS E2E workflow) and see how much it slows down. 

**Expected behavior**
Fast.

**Comment by jakirkham** [comment]
xref: https://github.com/rapidsai/rmm/issues/295
