### ISSUE TITLE
[FEA] Add per-thread default stream support to `pool_memory_resource`

### ISSUE THREAD

**Issue by jrhemstad** [rapidsai/rmm#410]
**Is your feature request related to a problem? Please describe.**

I would like to use `pool_memory_resource` with per-thread default stream. However, due to the fact that one thread cannot synchronize another thread's default stream in PTDS mode, this isn't currently possible with `pool_memory_resource`'s current implementation. 

**Describe the solution you'd like**

Modify `pool_memory_resource` to support PTDS. This is likely to cause a performance degradation due to needing to use events and pessimistically synchronizing. Therefore, it may make sense to create a new resource based on `pool_memory_resource` that adds PTDS support, but preserves the existing `pool_memory_resource` for those who want better performance and don't care about PTDS.

**Comment by harrism** [comment]
Since PTDS is a compile-time decision, I was planning to just compile-in PTDS support so that when it is turned off pool_memory_resource is just as fast as now.

**Comment by jrhemstad** [comment]
> Since PTDS is a compile-time decision, I was planning to just compile-in PTDS support so that when it is turned off pool_memory_resource is just as fast as now.

That's smart. That prevents proliferation of resources.

**Comment by harrism** [comment]
I think we will also need PTDS support in fixed_size_memory_resource / fixed_multisize_memory_resource

**Comment by rongou** [comment]
Are you guys actively working on this? Can I be of any help?

**Comment by jrhemstad** [comment]
> Are you guys actively working on this?

Yes, see https://github.com/rapidsai/rmm/pull/416

I'm sure we'll want someone to test it in a real workflow eventually, but I don't think it's at that point.

**Comment by harrism** [comment]
#425 replaces #416.
