### ISSUE TITLE
[FEA] Add a "tracking" resource adaptor

### ISSUE THREAD

**Issue by jrhemstad** [rapidsai/rmm#415]
**Is your feature request related to a problem? Please describe.**

Many users want to be able to query a resource for how much memory is "free" vs. in use.

In general, it is too onerous to expect _every_ resource to track and provide this exact information.

However, we can provide a pretty good estimate by creating a `tracking_resource_adaptor` that just keeps a running sum of the size of all `allocate` calls, minus all `deallocate` calls. This would not be an exact measure of how much memory is in use nor how big of an allocation you can make due to issues of bookkeeping, fragmentation, etc. 

**Describe the solution you'd like**

Similar to `logging_resource_adaptor`, make a `tracking_resource_adaptor` that implements the functionality described above that allows querying the sum of all `allocate`s minus all `deallocate`s.

**Comment by jrhemstad** [comment]
I want to be clear about what this adaptor would and would not tell you compared to `get_info()`.

`get_info` used to tell you `free` and `total` memory.

The tracking adaptor would simply tell you how much memory you've allocated that hasn't been freed yet. It doesn't tell you anything about the total memory available or how much is free (i.e., the maximum size of a new allocation).

**Comment by harrism** [comment]
For memory leak detection in testing I think the tracking resource adaptor should maintain a `map<ptr, size>` of allocations. Insert entries in allocate(), remove them in deallocate(), and provide a `report_leaks()` function that provides a list of all outstanding allocations. Then, unit tests, in the fixture we use this wrapper, and in the fixture's TearDown we call `report_leaks()`.

This way we get automatic per-unit-test leak checking, and we don't have to think about writing dedicated leak tests.

If this proves expensive, only enable it in nightly build tests.

**Comment by harrism** [comment]
Closed by #596
