### ISSUE TITLE
[FEA] Delete default constructor for device_buffer and device_uvector

### ISSUE THREAD

**Issue by jrhemstad** [rapidsai/rmm#422]
**Is your feature request related to a problem? Please describe.**

Similar to https://github.com/rapidsai/rmm/issues/418

The default constructor for `device_buffer` and `device_uvector` are problematic as they do not allow specifying a stream. This can lead to situations where the user isn't aware an operation is stream ordered:
```
device_buffer b{};
b.resize(100); // Defaults to using the default CUDA stream
```

**Describe the solution you'd like**

Delete the default ctor and force users to explicit specify a zero size and a stream.

**Comment by jakirkham** [comment]
I thought `device_buffer` used the default stream in this case. Or did that change?

**Comment by jrhemstad** [comment]
> I thought `device_buffer` used the default stream in this case. Or did that change?

It does, and that's precisely the problem. Due to the widespread misuse of the defaulted stream arguments with `device_buffer` in libcudf and elsewhere, we've decided to make stream arguments explicit and force users to specify a stream to reduce the chance of doing the wrong thing.

**Comment by jakirkham** [comment]
I think this will become challenging in Python as we don't have a good way to handle stream objects today. It will also requires other Python libraries that don't really know what streams are in use/available to think about them, which will make things challenging from an ecosystem perspective.

**Comment by jrhemstad** [comment]
> I think this will become challenging in Python as we don't have a good way to handle stream objects today. It will also requires other Python libraries that don't really know what streams are in use/available to think about them, which will make things challenging from an ecosystem perspective.

Nothing is stopping the Python side from still plugging in the default stream. The point is to make it explicit and force that behavior rather than defaulting the value.

**Comment by jakirkham** [comment]
Is this still an issue if we use PTDS ( https://github.com/rapidsai/rmm/pull/416 )?

**Comment by jrhemstad** [comment]
> Is this still an issue if we use PTDS ( #416 )?

It's orthogonal to PTDS. The point is, to use a `device_buffer` you always need to be explicit about what stream it's being used on, even if it's the CUDA default stream.

**Comment by harrism** [comment]
@jrhemstad still relevant?

**Comment by jrhemstad** [comment]
https://github.com/rapidsai/rmm/pull/424#issuecomment-702505537

Closing.
