### ISSUE TITLE
[FEA] Allow logging to be enabled/disabled directly on a MR instance in Python

### ISSUE THREAD

**Issue by rlratzel** [rapidsai/rmm#423]
The use case needing support is:
```
we want to use RMM logging for benchmarking, and don't want to have
each benchmark file have to worry about specifying logging and the right
path, etc. etc. by making them call RMM reinit() (ie. we don't want to couple
the dev's benchmark to specific benchmark infra), and we can't assume we
know what RMM settings they want to use.. Ideally, the infra would just
"add logging" on top of the existing settings prior to running the code, then
analyze the log file, disable logging, and report.
```
One proposal was to add an new API that returns the current "config" in python, which can be updated and applied directly to a `rmm.reinitialize()` call, like so:
```
c = rmm.get_current_config()
c.update(logging=True, log_file_name="foo")
rmm.reinitialize(**c)
```
as wonderfully elegant as this is, it should be rejected if it's not idiomatic with the direction of the API. Instead, a change to the `MemoryResource` class in Cython can be done instead:
```
cdef class MemoryResource:
    cdef shared_ptr[device_memory_resource_wrapper] c_obj
cdef class MemoryResource:  # the base class
     def enable_logging(self, log_file_name=None):
        # resets self.c_obj after wrapping it with a logging resource adaptor
     def disable_logging(self):
        # resets self.c_obj after getting its "upstream"
cdef class CudaMemoryResource(MemoryResource):
    pass
```
This would allow a python user to get the default MR and directly enable/disable logging on it.

**Comment by shwina** [comment]
>  Instead, a change to the MemoryResource class in Cython can be done instead:

```python
cdef class MemoryResource:
    cdef shared_ptr[device_memory_resource_wrapper] c_obj
cdef class MemoryResource:  # the base class
     def enable_logging(self, log_file_name=None):
        # resets self.c_obj after wrapping it with a logging resource adaptor
     def disable_logging(self):
        # resets self.c_obj after getting its "upstream"
cdef class CudaMemoryResource(MemoryResource):
    pass
```

For posterity, the issue I ran into with the above approach was the following:

When we change the underlying `shared_ptr[memory_resource]` to a `shared_ptr[logging_memory_resource]`, casting the underlying raw pointer, as is done [here](https://github.com/rapidsai/rmm/blob/1502058fa0c761bfab14711e7c9bf8a3d5569041/python/rmm/_lib/memory_resource.pyx#L211) breaks.

There's likely a way around this that I'm not seeing, but for now, I went with adding top-level `rmm.enable_logging()` and `rmm.disable_logging()` APIs.
