### ISSUE TITLE
[FEA] Memory resource to limit the total amount of memory that can be allocated

### ISSUE THREAD

**Issue by jlowe** [rapidsai/rmm#442]
**Is your feature request related to a problem? Please describe.**
Spark can run Pandas UDFs, and we would like to support Pandas UDFs that use cudf instead of Pandas.  That means we need the ability to share GPU resources between two processes, JVM and Python.  Eac process normally assumes it owns the entire GPU and potentially can allocate all GPU memory, preventing the other process from allocating sufficient GPU memory to succeed.

One way to support this is by artificially partitioning the GPU memory between the two processes.  If each process only allocates a configured amount then they could successfully share the same GPU.  For processes using RMM, it would be nice if RMM had a device memory resource that can be configured with a total amount of GPU memory it will allow to be allocated.

**Describe the solution you'd like**
A new device memory resource class that takes a constructor parameters of the parent memory resource to use for memory and a total number of bytes as a limit.  The memory resource would track the number of bytes allocated and return allocation failure for any allocation that would exceed the configured total number of bytes that can be allocated.

**Describe alternatives you've considered**
This also could be done with a total pool size config on the pool allocators, but this seems like a more general solution that isn't limited to a specific type of memory resource.  This resource could be stacked with other resources to add a total allocation limit to any type of memory resource.

**Comment by jrhemstad** [comment]
So an adaptor that caps the maximum size of allocations (i.e., (sum(do_allocate) - sum(do_deallocate)) < max_size)? 

What's the expected behavior if you go over `max_size`? Throw `rmm::bad_alloc`? A custom exception `rmm::max_overflow_error`?

**Comment by jrhemstad** [comment]
Note that `pool_memory_resource` already provides this functionality: https://github.com/rapidsai/rmm/blob/branch-0.15/include/rmm/mr/device/pool_memory_resource.hpp#L66

But as you say, this could be done in a reusable way with an adaptor.

**Comment by harrism** [comment]
I think it will be common for `pool_memory_resource` to be the top-level resource (i.e. cuda_memory_resource will be its upstream, and it will be upstream of everything else). So it's limit should be sufficient.

That said, a wrapper that limits could be useful because then you could apply the limit even to `cuda_memory_resource`.

And it could be combined with simple usage tracking (since it would be needed for limiting).

**Comment by harrism** [comment]
@jlowe is this needed for resources other than `pool_memory_resource`? If not, this can be closed. If so, then it can remain open.

**Comment by jlowe** [comment]
Yes, we would like to apply this to an arbitrary memory resource (e.g.: cuda_memory_resource), as there are still some use-cases that run without the RMM pool today, so the user can control whether the Spark plugin runs with or without the RMM pool.  Regardless of the underlying allocator, we want to limit to a user-specified amount when sharing the GPU or avoid taking all GPU memory when running alone and possibly preventing some required allocations at the CUDA driver/runtime level (e.g.: kernel launches or JIT kernel loads) from succeeding.

**Comment by harrism** [comment]
Good one for @hyperbolic2346 ?

I wonder if we should combine this with #415 (to add simple leak detection)?
