### ISSUE TITLE
[FEA] task parallelism friendly pool allocator

### ISSUE THREAD

**Issue by rongou** [rapidsai/rmm#448]
**Is your feature request related to a problem? Please describe.**
Note that at this point this is fairly speculative, so this is more of a discussion rather than strictly a feature request.

The spark-rapids plugin uses RMM to allocate GPU memory. In Spark, input is partitioned, and multiple tasks are launched to work on each partition. Typically a task is single-threaded, grabbing its thread from a thread pool. With per-thread default stream enabled, each task also operates in its own CUDA stream. During execution, tasks are fairly insulated from each other. Streams also don't interact, except in some cases (e.g. shuffle) one task hands off some allocations to another task which uses a different stream.

The current `pool_memory_resource` supports PTDS using CUDA events, which can be expensive if `cudaEventRecord` is done on every deallocation. Considering Spark's coarse-grained task parallelism, it may be possible to support PTDS without relying on CUDA events.

**Describe the solution you'd like**
I don't have a full solution, this is just a high level sketch.

Borrowing ideas from `jemalloc`, perhaps we can have an "arena" to allocate memory for each thread/stream.
* At the top level is a shared pool that pre-allocates a bunch of memory from cudaMalloc (for Spark the default is 90%). This pool is not aware of streams, but is thread safe.
* Each arena starts out empty.
* When an allocation request comes in, the arena first looks in its own list of free blocks and allocate from there if possible. If there is not enough memory, request a large chunk (say, 4MB) from the shared pool.
* Once in a while (perhaps when a full chunk becomes free), synchronize the stream and return the chunk to the pool.

The arena can potentially cache frequently used blocks regardless of size. For example, a job may allocate a bunch of 64MB buffers.

The tricky part is when memory is allocated in one thread but freed in another. I don't have a good answer yet, perhaps it involves some queuing and stream synchronization, but this doesn't happen too often.

**Describe alternatives you've considered**
We may be able to take advantage of the coarse-grained task parallelism used in Spark to allocate memory more efficiently, even if it performs worse in other usage scenarios.

**Additional context**
The jemalloc website (http://jemalloc.net/) has some information about its design, especially the paper (https://people.freebsd.org/~jasone/jemalloc/bsdcan2006/jemalloc.pdf), although the information may be quite out of date.

**Comment by jrhemstad** [comment]
Do you have any benchmarks showing that the existing `pool_memory_resource` implementation is a bottleneck?

**Comment by harrism** [comment]
I agree with Jake that before we do anything we should understand the bottlenecks. If it's not allocation, move on. If it is, that's exciting, we can improve RMM! :)

Regarding cudaEventRecord being a bottleneck: I had already planned to revisit if and when this becomes a problem.

> When an allocation request comes in, the arena first looks in its own list of free blocks and allocate from there if possible. If there is not enough memory, request a large chunk (say, 4MB) from the shared pool.

Pool allocators can have pool allocators as upstreams. I can imagine having a pool allocator that only supports a single stream, and therefore only needs synchronization when it needs to grow from upstream. This is one of the reasons I'm currently decoupling stream ordering logic from free list logic (PR in the works). I want to make it easy to build custom allocators from these pieces.

**Comment by rongou** [comment]
I'm running some benchmarks now. With so many factors in play, it's probably hard to pinpoint the exact performance bottlenecks. Might be worth playing around with different approaches to see if they make any difference.

**Comment by harrism** [comment]
It should be easy to determine if allocation/deallocation is a bottleneck at all without having to implement any new allocation features.

**Comment by rongou** [comment]
I've been running some benchmarks on a DGX-2. Here are a couple of things I've observed:
* Holding everything else constant, running with PTDS enabled is more likely to cause GPU out-of-memory errors. I had to increase the number of shuffle partitions in Spark to make a given query work both with and without PTDS. 
* Enabling PTDS doesn't improve the performance much. In fact, it's actually worse in some cases.

I have created traces with nsys for both, but I haven't been able to make sense of them.

**Comment by harrism** [comment]
I think there will always be a tradeoff between device synchronization and memory fragmentation.

**Comment by rongou** [comment]
I don't know if this is causing any real issues, but the `cudaEventRecord` calls seem pretty expensive:
```bash
CUDA API Statistics (nanoseconds)

Time(%)      Total Time       Calls         Average         Minimum         Maximum  Name
-------  --------------  ----------  --------------  --------------  --------------  -------------------------
   42.8    117891044007       21461       5493268.9            6621       594793890  cudaMemcpy_ptds
   29.3     80830599444         403     200572207.1            5238      1662958430  cudaHostAlloc
    9.8     26914042708       35168        765299.2            5052      1671037338  cudaLaunchKernel_ptsz
    8.2     22599537446       63830        354058.2            2253       197796376  cudaStreamSynchronize_ptsz
    4.2     11482242584      100808        113902.1             534       510879369  cudaEventRecord_ptsz
    3.4      9279525662       69541        133439.6             232       184835038  cudaMemcpyAsync_ptsz
    1.1      2931195717        8278        354094.7            2533        41190405  cudaDeviceSynchronize
    0.6      1660700762         403       4120845.6            7798        77846143  cudaFreeHost
    0.6      1609870793       27941         57616.8             244        46089736  cudaMemsetAsync_ptsz
    0.1       200061829        2716         73660.5            5611         7411954  cuLaunchKernel_ptsz
    0.0        65559786         161        407203.6          111214        10627786  cuModuleLoadDataEx
    0.0        47689702          96        496767.7            1732        42115837  cudaEventCreateWithFlags
    0.0        35167844        4261          8253.4            1001         1715869  cudaStreamWaitEvent_ptsz
    0.0         5778247          16        361140.4           41704         2855912  cudaMemcpyToSymbol_ptds
    0.0         1033526          96         10765.9            3401           30235  cudaFree
```

**Comment by harrism** [comment]
cudaEventRecord is definitely expensive, but that profile shows it as about 450x times more expensive on average than my standalone benchmarks here: https://github.com/harrism/cuda_event_benchmark

**Comment by harrism** [comment]
@rongou do you have the same profile without PTDS so we can compare?

**Comment by rongou** [comment]
This is the one using legacy default stream:
```bash
CUDA API Statistics (nanoseconds)

Time(%)      Total Time       Calls         Average         Minimum         Maximum  Name                                                                            
-------  --------------  ----------  --------------  --------------  --------------  --------------------------------------------------------------------------------
   43.2    134715257922       21461       6277212.5            6780       681600187  cudaMemcpy                                                                      
   25.1     78393809158         403     194525581.0            5270      1696424064  cudaHostAlloc                                                                   
   11.7     36549466087       34904       1047142.6            4851      1742680334  cudaLaunchKernel                                                                
   10.3     31988488690       63718        502032.2            2350       246424582  cudaStreamSynchronize                                                           
    6.5     20393140816       69429        293726.6             240       346268379  cudaMemcpyAsync                                                                 
    1.5      4532249942         403      11246277.8            7350       205280280  cudaFreeHost                                                                    
    0.9      2949922358       27829        106001.7             242        91121736  cudaMemsetAsync                                                                 
    0.6      1912936997        8126        235409.4            2421        46775405  cudaDeviceSynchronize                                                           
    0.1       420635684        2716        154873.2            5970        31960797  cuLaunchKernel                                                                  
    0.0        77110875         161        478949.5          106739         7534798  cuModuleLoadDataEx                                                              
    0.0         3970129          16        248133.1           47489         1660542  cudaMemcpyToSymbol                                                              
    0.0         1326147          96         13814.0            2851           58142  cudaFree
```

**Comment by harrism** [comment]
@rongou did you ever come up with data demonstrating the need?

**Comment by rongou** [comment]
As I reported initially, we keep running out of memory with PTDS, which makes it hard to compare performance with legacy default streams, and it's a blocker for releasing spark-rapids with PTDS.

Profiling still shows fairly expensive `cudaEventRecord` calls, and even running the custom CUDA driver didn't help. But I do agree allocation speed is of secondary concern compared to memory fragmentation.
