### ISSUE TITLE
[FEA] Extend `logging_resource_adaptor` to optionally include backtrace

### ISSUE THREAD

**Issue by jrhemstad** [rapidsai/rmm#452]
**Is your feature request related to a problem? Please describe.**

I would like it if I could optionally enable the `logging_resource_adaptor` to capture a stacktrace for (de)allocations.

**Describe the solution you'd like**

Linux has [`backtrace`](https://man7.org/linux/man-pages/man3/backtrace.3.html) which is a low-level C API for capturing this info. 

I'd prefer to use an existing high-level wrapper like [`boost::stracktrace`](https://www.boost.org/doc/libs/1_65_1/doc/html/stacktrace.html) which is header-only.

**Comment by harrism** [comment]
Is it possible to depend on only the boost::stack trace header? Or does that require fetching all of boost?

**Comment by jrhemstad** [comment]
> Is it possible to depend on only the boost::stack trace header? Or does that require fetching all of boost?

Nothing in Boost requires you to use all of Boost. Pretty much every component is independent and is usually available as a built library or header-only.

**Comment by harrism** [comment]
Looks like spdlog has built-in backtrace support: 
https://github.com/gabime/spdlog#backtrace-support

**Comment by jrhemstad** [comment]
> Looks like spdlog has built-in backtrace support:
> https://github.com/gabime/spdlog#backtrace-support

I looked into this, and that's not the same kind of backtrace. `spdlog` is talking about a ring buffer of log messages that allow you to dump the last `N` logged messages, not getting the stacktrace of function calls.

**Comment by harrism** [comment]
Oh, hah!  yes very different.

**Comment by harrism** [comment]
@jrhemstad a backtrace was added to `tracking_resource_adaptor` #596 . I think that is sufficient. But if you think it is needed in `logging_resource_adaptor` please reopen.
