### ISSUE TITLE
[BUG] Deprecate `get/set_default_resource` in favor of `get/set_current_device_resource`

### ISSUE THREAD

**Issue by jrhemstad** [rapidsai/rmm#459]
**Describe the bug**

As seen in https://github.com/rapidsai/cudf/issues/5839, `get/set_default_resource` is flawed for use-cases where more than one GPU is used per process. This stems from the fact that `get/set_default_resource` are not device aware.  

We could just make `get/set_default_resource` be device aware, but I do not like this solution as the function naming does not reflect the fact that it is device specific. 

Instead, we should deprecate/remove `get/set_default_resource` in favor of using `get/set_current_device_resource` from https://github.com/rapidsai/rmm/pull/458.

**Comment by harrism** [comment]
To avoid having to change all client code, what do you think of just keeping the name `get/set_default_resource` and just changing the behavior, or keeping the old APIs as wrappers around the new APIs?

I know it's not ideal, but nothing ever is.

**Comment by jrhemstad** [comment]
> To avoid having to change all client code, what do you think of just keeping the name `get/set_default_resource` and just changing the behavior, or keeping the old APIs as wrappers around the new APIs?
> 
> I know it's not ideal, but nothing ever is.

I think it makes sense to do that for a release or two, but the `get/set_default` APIs should be marked deprecated and eventually removed.

It's a pretty easy find/replace kind of change, so I don't think it will be too painful to update.
