### ISSUE TITLE
[BUG] cub isn't being used?

### ISSUE THREAD

**Issue by germasch** [rapidsai/rmm#460]
Not sure this really should be called a "bug", but anyway.

**Describe the bug**
The build vendors cub into `_deps/cub-src`. But while it's added to the include path it isn't really being used directly by rmm.

Since build also vendors thrust, which itself includes cub, one ends up with two versions of cub. It seems to me that at best, one ends up with two identical versions of cub, at worst with two incompatible versions where one has to hope that the right one gets picked. Currently, at least they appear to both be exactly identical, both 10.9.10.

At this point, I'm just cleaning up some cmake stuff, so at the very least I'd like to remove the include path to the separate standalone cub. Though at this point it'll be entirely unused, so I might as well remove it?

**Comment by harrism** [comment]
Hmmm, this must have been added when @jrhemstad was exploring adding a memory_resource for the CUB caching allocator #291 or #430.  No longer needed, though, so I agree it should be removed. Thanks!
