### ISSUE TITLE
[FEA] Move `cudf._cuda` module into rmm

### ISSUE THREAD

**Issue by galipremsagar** [rapidsai/rmm#488]
**Is your feature request related to a problem? Please describe.**
To be able to import rmm on a machine with no GPU and print informative error messages regarding any improper setup, we will need `cudf._cuda` module and it would be easier to do so by moving `cudf._cuda` under rmm from `cudf`

**Describe the solution you'd like**
Move `cudf._cuda` and make use of the utility functions as currently being used by cudf.

**Comment by kkraus14** [comment]
@galipremsagar can you tackle this for 0.15? Hopefully it should be relatively straightforward.

**Comment by galipremsagar** [comment]
Sure @kkraus14
