### ISSUE TITLE
[FEA] Create a process so RMM can live as a global memory manager for multiple processes

### ISSUE THREAD

**Issue by felipeblazing** [rapidsai/rmm#50]
**Is your feature request related to a problem? Please describe.**
As more and more people start using the ecosystem and building workloads using rapids.ai they will start spawning processes that are triggered by real time events, by a clock, by user interaction etc. We don't have a way of estimating usage of all of our algorithms (e.g. group by and join) but we DO know each time that cudf requests and allocation from rmm. Because the execution of these different workloads using rapids.ai is both unpredictable in terms of scheduling and memory consumption we can run into situations where we run out of resources not because any of the particular jobs requires more memory than can be provided but because the jobs can't be run at the same time. 

**Describe the solution you'd like**
1. To make a distinction between allocations which are in a temporary state (e.g. being used for calculations in a short term process (something that lives in seconds not minutes) and those which are long living (e.g. stuff we hand back to the user, things that we decide to store for longer than its just being processed on)
2. To understand whether or not a job can begin and proceed according to if there is either enough memory available right now or will be soon because free the allocations in a temporary state would grant enough memory to make the allocation.
3. To have all allocations originate in a single process which is able to keep track of how much has been allocated and in what state so that we can be able to fulfill requests even when perhaps enough memory is not available the moment the initial request was made so long as it can be fulfilled very soon when the memory is available.
4. To hopefully maybe or maybe not allow allocations to be non blocking and and belong to a group of allocations which we can syncrhonize together and as a group. This would handle cases where an algorithm is going to make 4 allocations at one point and those allocations all need to exist at the same time. They can succeed or fail as a group and we can back out any allocations that were made if any in the group did not succeed. 
 
**Describe alternatives you've considered**
Tracking allocations within our uses of cudf and adding a wrapper to the cudf python library that keeps track of memory as it comes in and out but I don't think this would really work.

**Additional context**
The code we currently have works great for demos and workloads that you are running one time. As people develop their toolsets they will run and run more workloads and it will not be possible to assume that these workloads are being queued to be run nor shoudl they be. I really think we should start considering possibilities for managing allocations across multiple processes. This could also allow us to be more aggressive with the size of the pool. Last piece of context is that I have not thought this through at length and this is just some stream of conscience ideas to help get a discussion going.

**Comment by harrism** [comment]
We may support global memory management in the future, but we won't do it by creating a separate process, so closing this for now.
