### ISSUE TITLE
[FEA] PyTorch and RMM sharing memory pool

### ISSUE THREAD

**Issue by brhodes10** [rapidsai/rmm#501]
**Is your feature request related to a problem? Please describe.**
Currently I'm running a streamz workflow that uses pytorch. I notice that I continue to encounter errors like below where pytorch is not able to allocate enough memory.
```
RuntimeError: CUDA out of memory. Tried to allocate 376.00 MiB (GPU 0; 31.72 GiB total capacity; 29.02 GiB already allocated; 244.88 MiB free; 29.80 GiB reserved in total by PyTorch)
```

I'm wondering if pytorch and rmm are competing for memory and if so if there's a recommended way to manage 
**Describe the solution you'd like**
If possible, for pytorch and rmm to potentially use the same memory pool. Or a recommended method to resolve this type of memory issue

**Describe alternatives you've considered**
None

**Additional context**
The streamz workflow end-to-end can be found [here](https://github.com/rapidsai/clx/blob/60d5b50470c301455d1d01205dbf3ea4a0045be8/examples/streamz/python/cybert.py). In short summary, it first initializes a streamz worklfow that uses dask to read in data from kafka. Then processes that data using cyBERT inferencing which can be found [here](https://github.com/rapidsai/clx/blob/8f574a6f8f10632e704d289629d5d58a6ce3d0b0/python/clx/analytics/cybert.py). cyBERT uses `cudf` for data pre-processing steps and a [BERT](https://huggingface.co/transformers/model_doc/bert.html) model for inferencing. Then the processed data is published back to kafka.

**Comment by VibhuJawa** [comment]
There was some [internal discussion](https://nvidia.slack.com/archives/CGLPWR4HJ/p1596565295229000) about a related  issue that plagued [27 HF implimentation](https://github.com/rapidsai/tpcx-bb/pull/84)  and it was suggested that a path forward can be: 

- We create a PyTorch memory resource for RMM to allow RMM to use the same memory pool as PyTorch.

**Comment by jakirkham** [comment]
Another idea that came up was using RMM within PyTorch possibly using an external memory allocator (as was done with CuPy and Numba) or possibly even direct usage (as has recently been done with XGBoost). Have filed this as issue ( https://github.com/pytorch/pytorch/issues/43144 ).

**Comment by jakirkham** [comment]
> We create a PyTorch memory resource for RMM to allow RMM to use the same memory pool as PyTorch.

On this usage pattern it's worth looking at how CuPy did something similar.

xref: https://github.com/pytorch/pytorch/pull/33860
xref: https://github.com/cupy/cupy/pull/3126

**Comment by VibhuJawa** [comment]
This was closed by: https://github.com/rapidsai/rmm/pull/1168 ,  Can we close this ?
