### ISSUE TITLE
[FEA] Provide operator for bit-wise or of allocation modes

### ISSUE THREAD

**Issue by muellren** [rapidsai/rmm#51]
Problem: Bit-wise or-ing yields int not enum. 

The API documentation implies that the allocation mode enums can bit bit-ored. 
Example:
```c++
rmmOptions_t rmm_option {
  .allocation_mode = PoolAllocation | CudaManagedMemory,
  .initial_pool_size = free_memory / 2,
  .enable_logging = true };
```

gives a compiler error: `error: a value of type "int" cannot be used to initialize an entity of type "rmmAllocationMode_t"`

Suggestions:
a) Implement operator:
```c++
inline rmmAllocationMode_t operator|(rmmAllocationMode_t left, rmmAllocationMode_t right) {
   return static_cast<rmmAllocationMode_t>(
     static_cast<int>(left) | static_cast<int>(right));
}
```
or 

b) add member `PoolAllocationCudaManagedMemory = 3` to struct without bitwise or-ing.

**Comment by jrhemstad** [comment]
I'm more in favor of option 2.

**Comment by harrism** [comment]
If we implement #302, this will no longer be necessary.

**Comment by harrism** [comment]
This is stale, closing.
