### ISSUE TITLE
[FEA] add arg to Python API reinitialize() to set max pool size (and enforce usage when managed_memory=True?)

### ISSUE THREAD

**Issue by rlratzel** [rapidsai/rmm#519]
Because the default maximum pool size is all memory for the device, setting `managed_memory=True` in the RMM Python `reinitialize()` API still does not allow for oversubscribing GPU memory.  This makes sense (what would the new default max pool size be?) but is still unexpected, since in most cases the caller is expecting UVM features like oversubscribing when setting `managed_memory=True`, and instead that aspect is silently ignored by default.

This issue proposes an additional argument to `rmm.reinitialize()` to allow the caller to set a new maximum pool size from the same call that allows them to enable managed_memory in the first place.

In addition to the new arg, it might make sense to enforce that setting a new max pool size is done when enabling `managed_memory` for the reason mentioned above (ie. enabling UVM implies the ability to oversubscribe, so make the user aware that a new max pool size would be needed). However, for the case of a user enabling UVM in order to have a single address space across devices (is this done from Python?), then perhaps forcing them to also set a new max pool size might not be the best UX.

**Comment by harrism** [comment]
I think we should provide reasonable defaults wherever possible, rather than raising an error if someone fails to set a maximum managed pool size. What would a reasonable default be? It would be nice if the CUDA runtime could tell you the amount of virtual memory available...

**Comment by rlratzel** [comment]
@harrism mentioned that there's valid use cases for using managed mem without increasing the max pool size, so enforcing that the user (re)set the max pool size wouldn't be appropriate for everyone.
