### ISSUE TITLE
[FEA] I need pool_memory_resource to support get_mem_info()

### ISSUE THREAD

**Issue by JustPlay** [rapidsai/rmm#533]
**Is your feature request related to a problem? Please describe.**
I need pool_memory_resource to support get_mem_info()
So, does this will be impled soon (by nvidia)? if not i think i can try to impl it but I don't know how long it will take

**Comment by harrism** [comment]
Can you describe your use case in more detail? `get_mem_info` may not be an ideal interface so we are not sure we will require it of memory resources in the future. For example the free memory of a resource may be meaningless if fragmentations makes the largest allocatable size much smaller than that.  And the largest allocatable size in a pool where multiple streams have deallocated may actually not be computable without synchronizing all the streams and merging all the free lists of those streams to eliminate fragmentation. This would make `get_mem_info` a very expensive call.

**Comment by JustPlay** [comment]
> Can you describe your use case in more detail? `get_mem_info` may not be an ideal interface so we are not sure we will require it of memory resources in the future. For example the free memory of a resource may be meaningless if fragmentations makes the largest allocatable size much smaller than that. And the largest allocatable size in a pool where multiple streams have deallocated may actually not be computable without synchronizing all the streams and merging all the free lists of those streams to eliminate fragmentation. This would make `get_mem_info` a very expensive call.

please refer to this   https://github.com/NVIDIA/spark-rapids/issues/635

Thanks
