### ISSUE TITLE
[BUG] Even CUDA_API_PER_THREAD_DEFAULT_STREAM is not set，@stream may still equal to cudaStreamPerThread

### ISSUE THREAD

**Issue by JustPlay** [rapidsai/rmm#535]
https://github.com/rapidsai/rmm/blob/9bb169430d42feb0e999ba0543ec1b0144471643/include/rmm/mr/device/detail/stream_ordered_memory_resource.hpp#L269

Even CUDA_API_PER_THREAD_DEFAULT_STREAM is not set，@stream may still equal to cudaStreamPerThread (i remember the user can use  cudaStreamPerThread explicitly)

https://developer.nvidia.com/blog/gpu-pro-tip-cuda-7-streams-simplify-concurrency/
Starting in CUDA 7 you can also explicitly access the per-thread default stream using the handle cudaStreamPerThread, and you can access the legacy default stream using the handle cudaStreamLegacy

**Comment by harrism** [comment]
Good observation, @JustPlay I'll take a look. At a minimum, I should add a test for that case.
