### ISSUE TITLE
[FEA] Add a 4th step: reclaim free blocks from the per-stream freelist(s) and merge them when possible to form bigger free block(s)

### ISSUE THREAD

**Issue by JustPlay** [rapidsai/rmm#536]
https://github.com/rapidsai/rmm/blob/9bb169430d42feb0e999ba0543ec1b0144471643/include/rmm/mr/device/detail/stream_ordered_memory_resource.hpp#L305

In the current impl:
1. find free blocks in the freelist associated with the @stream arguments
2. find free blocks from freelist  associated with other stream(s)
3. expand the pool

We need a fourth step, in this step, we reclaim free blocks from all the child per-stream freelist, the reclaimed free block(s) shoud be merged when possiable. By this way, we can reduce fragmentation and lower the risc of OOM

Because `pool_memory_resource`  commonly take `cuda_memory_resource` as the upstream, the `expand_pool` in step3 will call cudaMalloc(), which need device sync, incuring high overhead, so the overhead introduced by the fourth step(sync with multiple stream) should no bigger then step3

**Comment by JustPlay** [comment]
https://github.com/NVIDIA/spark-rapids/issues/635

**Comment by jrhemstad** [comment]
That's precisely what is being done in https://github.com/rapidsai/rmm/pull/532.

**Comment by JustPlay** [comment]
> That's precisely what is being done in #532.

great work；rely need this feature

**Comment by harrism** [comment]
Fixed by #532

**Comment by JustPlay** [comment]
https://github.com/rapidsai/rmm/pull/532 do not satisfy my need well, still OOM with exactly the same config with PTDS=OFF

**Comment by harrism** [comment]
That's not true. It merges free lists until either the request is satisfied or it fails, at which point it tries to allocate from upstream.

If you are OOMing in Spark it is likely due to fragmentation. There are efforts in progress to alleviate fragmentation pressure, please be patient.

In general I think spark has high fragmentation because it chops up the available work into small pieces to get more concurrent workers (good for CPUs, worse for GPUs).

**Comment by JustPlay** [comment]
> It merges free lists until either the request is satisfied or it fails,

i am a little thoughtless, in the call to `get_block_from_other_stream(.., merge_first=true), it will merge until succ or all other list had been merged.


but why PTDS=on OOM will PTDS=OFF not? all the other free list can be merged, what the difference between one stream and multi stream? （gpu concurrent, batch size are all the same）

**Comment by JustPlay** [comment]
> There are efforts in progress to alleviate fragmentation pressure, please be patient

can you tell me where to find more info? and when it will be ready?

**Comment by harrism** [comment]
More streams results in higher fragmentation because we favor allocating within a stream first.  There is an open PR for an arena allocator and I am also experimenting with other ways to separate large and small allocations.
