### ISSUE TITLE
[FEA] Allow RMM to Handle Using Conda Compilers

### ISSUE THREAD

**Issue by aleksficek** [rapidsai/rmm#539]
**Is your feature request related to a problem? Please describe.**
Currently using conda compilers with RMM results in breakages. RAPIDS is posed to take advantage of anaconda compiler versions of `gcc` and `g++` (https://docs.conda.io/projects/conda-build/en/latest/resources/compiler-tools.html) in the future. This is part of an overarching effort in project [scout](https://github.com/rapidsai/scout) where developers will be able to one day install the scout conda package which includes `gcc`, `g++` and `nvcc` conda compilers at [specific versions](https://github.com/rapidsai/scout/blob/branch-0.15/conda/recipe/scout/conda_build_config.yaml) with ccache hooked up for fast compilation.

**Describe the solution you'd like**
This is similar to the issue and fix as part of https://github.com/rapidsai/rmm/issues/315 but based on my own testing in RMM a similar failure has since resurfaced.

**Steps to simulate failure**
Conda install conda compilers `gcc_linux-64` and `gxx_linux-64` to conda environment. Then build the repo and see failures. If this does not simulate the error then the error can be reproduced by first pulling the `gpuci/rapidsai:0.15-cuda10.2-devel-ubuntu16.04-py3.7` docker image, cloning the rmm repo, installing conda compilers and then building it.

**Additional context**
After this is solved, the general plan of attack will be to integrate conda compilers into cuDF and then distribute the requests outwards to each other repo.

**Comment by jrhemstad** [comment]
What are the breakages?

**Comment by aleksficek** [comment]
It used to be breaking exactly like https://github.com/rapidsai/rmm/issues/315 but as I just tested it, the `cmake` command worked but the process is now failing at `make -j`. There's a chance I'm just setting my environment wrong but in that case, all that's needed is a verification that conda compilers are working in rmm.

[rmm error.txt](https://github.com/rapidsai/rmm/files/5172119/rmm.error.txt)

**Comment by aleksficek** [comment]
Looks like I used an incorrect version of the conda's gcc. I'll offload this debugging to one of the members on ops I did a knowledge transfer with and they'll take it from here.

**Comment by harrism** [comment]
@kkraus14 @aleksficek @mike-wendt is this still relevant?

**Comment by kkraus14** [comment]
Yes, still relevant

**Comment by mike-wendt** [comment]
The current plan is to adopt conda compilers for the RAPIDS libraries in 0.20 when CUDA 10.X support is dropped

**Comment by jakirkham** [comment]
Thanks for the update Mike! 😄

**Comment by harrism** [comment]
@beckernick I saw you closed the cuDF equivalent of this issue. Is this issue still relevant or can it be closed?

**Comment by beckernick** [comment]
cuDF can build with the conda compilers, but I don't know if RMM can currently. We may want to leave this open until we verify.

**Comment by kkraus14** [comment]
I can confirm that building RMM CUDA / C++ tests and building the RMM Cython extensions works as expected with the conda compilers with version 9.3.0.

**Comment by jakirkham** [comment]
This is also how I've built RMM in the past (though haven't done this recently).

Given the C++ side of RMM is header only, suspect this is a non-issue from that side.

**Comment by harrism** [comment]
Thanks @kkraus14 and @jakirkham . Closing.
