### ISSUE TITLE
[FEA] Host Doxygen HTML

### ISSUE THREAD

**Issue by jrhemstad** [rapidsai/rmm#54]
***Is your feature request related to a problem? Please describe.***
The libcudf Doxygen documentation HTML page should be accessible without requiring someone to clone the repo and build with make doc.

***Describe the solution you'd like***
Doxygen HTML should be hosted and accessible via github or dev docs page.

**Comment by harrism** [comment]
Doxygen HTML is here: http://docs.rapids.ai/api/rmm/stable/

It needs a LOT of work -- clearly we don't know how to use doxygen, because none of the public API shows up (or it is buried)!
