### ISSUE TITLE
[BUG] PRs without changelog-worthy but necessary changes cannot be merged

### ISSUE THREAD

**Issue by gonzalobg** [rapidsai/rmm#552]
**Describe the bug**
See https://github.com/rapidsai/rmm/pull/547. Some PR changes are not changelog worthy. 

It is currently not possible to merge those PRs.

**Steps/Code to reproduce bug**
Open a PR with a change that's not changelog worth it. Test won't run until the changelog is modified.

**Expected behavior**
Tests should be able to run even if the changelog is not modified.

**Environment details (please complete the following information):**
Not relevant

**Additional context**
Possible fix: the bots should accept a command to run the tests and merge even if the change log is not modified.

**Comment by harrism** [comment]
This is a RAPIDS-level policy and is not specific to RMM. Please see docs.rapids.ai

**Comment by gonzalobg** [comment]
Shall I re-open this bug somewhere else? 

AFAICT: such PRs clearly exist, and it should be possible to merge them, so this might just be that the required feature is not implemented in the github bot that handles PRs.

**Comment by gonzalobg** [comment]
Apparently the bot already implements this feature. One only needs to rename the PR to `[skip ci changelog]`.
