### ISSUE TITLE
[BUG] github thinks latest rmm release is v0.5.0

### ISSUE THREAD

**Issue by germasch** [rapidsai/rmm#554]
On the main rmm github page, it shows a link to the latest release, but it goes to v0.5.0, which is also marked "latest release" when going through the list of releases.

I believe this happens because the later releases have been made by adding a git tag, but github doesn't have any further information, and it seems that one might be able to edit the tag and add a release title and then (hopefully) 0.15 would show up as the latest.

**Comment by raydouglass** [comment]
I have updated the release to the most recent.
