### ISSUE TITLE
[BUG] get_event() will create a new event rather than reuse on each call to it in PTDS mode

### ISSUE THREAD

**Issue by JustPlay** [rapidsai/rmm#558]
https://github.com/rapidsai/rmm/blob/6a3a62fce9c002c8390561566a71f544d7a017c7/include/rmm/mr/device/detail/stream_ordered_memory_resource.hpp#L285

```
  stream_event_pair get_event(cudaStream_t stream)
  {
#ifdef CUDA_API_PER_THREAD_DEFAULT_STREAM
    if (cudaStreamDefault == stream || cudaStreamPerThread == stream) {
      // Create a thread-local shared event wrapper. Shared pointers in the thread and in each MR
      // instance ensures it is destroyed cleaned up only after all are finished with it.
      thread_local auto event_tls = std::make_shared<event_wrapper>();
      default_stream_events.insert(event_tls);
      return stream_event_pair{stream, event_tls.get()->event};
    }
#else

....

```

I think the above code will create a new thread-local event on each call to get_event() in ptds mode, so the do_allocate(), do_deallocate() will use different event even in the same thread.

I think this is not OK.  According to other code snippets in the same cpp file, one stream should exactly have just one event

BTW: the code may still work, but it will get_block_from_other_stream very frequently

@harrism  @jrhemstad @kkraus14 @rongou

**Comment by rongou** [comment]
`thread_local` is static (or more precisely, specifies "thread storage duration" since C++11 https://en.cppreference.com/w/cpp/language/storage_duration), so the event will only get created once per thread. But it does get inserted into `default_stream_events` over and over.

**Comment by harrism** [comment]
Insertion of value into a `std::set` that already contains the value does not insert anything. https://en.cppreference.com/w/cpp/container/set/insert

I could check that the event is not already in the set before inserting, but that would be the same thing that the set does itself, so there would be no savings.  I believe this code is working as designed.

**Comment by JustPlay** [comment]
> `thread_local` is static (or more precisely, specifies "thread storage duration" since C++11 https://en.cppreference.com/w/cpp/language/storage_duration), so the event will only get created once per thread. But it does get inserted into `default_stream_events` over and over.



> Insertion of value into a `std::set` that already contains the value does not insert anything. https://en.cppreference.com/w/cpp/container/set/insert
> 
> I could check that the event is not already in the set before inserting, but that would be the same thing that the set does itself, so there would be no savings. I believe this code is working as designed.

Yes, the code is OK; thanks very much
