### ISSUE TITLE
[DOC] Document logging

### ISSUE THREAD

**Issue by harrism** [rapidsai/rmm#56]
## Report incorrect documentation

**Location of incorrect documentation**
README.md has not explanation of logging and how to use it from C++ or Python

**Describe the problems or issues found in the documentation**
README.md has not explanation of logging and how to use it from C++ or Python

**Suggested fix for documentation**
Add explanation and usage examples of logging to README.md

**Comment by jrhemstad** [comment]
https://github.com/rapidsai/rmm/issues/42 duplicate?

**Comment by harrism** [comment]
Yes, sorry.
