### ISSUE TITLE
[FEA]RMM should not only logging `allocated info` but also logging `allocating info` to help locate OOM

### ISSUE THREAD

**Issue by JustPlay** [rapidsai/rmm#562]
**Is your feature request related to a problem? Please describe.**

RMM should not only logging `allocated info` but also logging `allocating info`

In spark-rapids, we we turned on `spark.rapids.memory.gpu.debug`, the rmm log only has `allocated info`,  but, what we need to know is `which task (OR cuda stream) want to allocate and how much memory it need`

By using the `allocating info`, we can better analysis the OOM problem

https://github.com/rapidsai/rmm/blob/f59143645f0237c8f069b87f8bcfa6369559cee6/include/rmm/mr/device/logging_resource_adaptor.hpp#L200
https://github.com/rapidsai/rmm/blob/f59143645f0237c8f069b87f8bcfa6369559cee6/include/rmm/mr/device/logging_resource_adaptor.hpp#L231

In the above impl，i think，when the upstream failed to allocate memory，we will not know which allocation cause the OOM error

**Comment by JustPlay** [comment]
![image](https://user-images.githubusercontent.com/5866501/93555580-ec26a900-f9a8-11ea-83c5-f59d6e02ca37.png)

**Comment by harrism** [comment]
This is a log from `logging_resource_adapter`. It's intended for use with REPLAY_BENCHMARK, not for debugging.

There is a new debug logging feature. There are only log messages output by `pool_memory_resource` currently, but more can be added as needed. Details here: 
https://github.com/rapidsai/rmm#debug-logging

**Comment by JustPlay** [comment]
> This is a log from `logging_resource_adapter`. It's intended for use with REPLAY_BENCHMARK, not for debugging.

but， the output format by spark-rapids is just the same as `logging_resource_adapter`, so I think, in rapids, the debug feature is depended on `logging_resource_adapter`

**Comment by harrism** [comment]
No, it is as documented. Feel free to file a bug against spark-rapids.

**Comment by JustPlay** [comment]
> No, it is as documented. Feel free to file a bug against spark-rapids.

`logging_resource_adapter` is just what we need.

I  will see whether rmm::logger satisfy our need

**Comment by JustPlay** [comment]
> No, it is as documented. Feel free to file a bug against spark-rapids.

cuDF is using `logging_resource_adaptor`, so rapids use it too

https://github.com/rapidsai/cudf/blob/c39e9168c6d08236f36e5c3203b3ba8d145e86ed/java/src/main/native/src/RmmJni.cpp#L24
https://github.com/rapidsai/cudf/blob/c39e9168c6d08236f36e5c3203b3ba8d145e86ed/java/src/main/native/src/RmmJni.cpp#L34
https://github.com/rapidsai/cudf/blob/c39e9168c6d08236f36e5c3203b3ba8d145e86ed/java/src/main/native/src/RmmJni.cpp#L353
https://github.com/rapidsai/cudf/blob/c39e9168c6d08236f36e5c3203b3ba8d145e86ed/java/src/main/native/src/RmmJni.cpp#L393

https://github.com/rapidsai/cudf/blob/c39e9168c6d08236f36e5c3203b3ba8d145e86ed/java/src/main/java/ai/rapids/cudf/Rmm.java#L169
https://github.com/rapidsai/cudf/blob/c39e9168c6d08236f36e5c3203b3ba8d145e86ed/java/src/main/java/ai/rapids/cudf/Rmm.java#L192
