### ISSUE TITLE
[FEA] Improved RMM internal logging control

### ISSUE THREAD

**Issue by jlowe** [rapidsai/rmm#564]
**Is your feature request related to a problem? Please describe.**
Recently RMM has started emitting an `rmm_log.txt` file that logs internal RMM messages such as this (which occurred in an application that can recover from many RMM OOM situations and continue):
```
[ 32522][09:32:03:171617][info  ] ----- RMM LOG BEGIN [PTDS DISABLED] -----
[ 32522][09:32:03:171645][error ] [A][Stream 0x1][Upstream 3458764513820540928B][FAILURE max pool size exceeded]
```

There are cases where either the current working directory may not be writable or will not persist past the application lifetime, and thus the user would never see the logs.  Therefore we need to be able to control where these logging messages are written, including the possibility of using existing file descriptors (e.g.; stdout or stderr).

**Describe the solution you'd like**
RMM could provide an API to set where internal log messages will be written.  The initial implementation could just take a file descriptor to use.  Being able to provide a spdlog sink or something similar would provide the most flexibility, as the application could implement some dynamic control behavior during logging if desired.

**Describe alternatives you've considered**
Compile-time flags would be less ideal since there is no flexibility.  For example, if we need to compute the appropriate logging path at runtime, compile-time flags aren't going to work.

**Comment by jrhemstad** [comment]
Similar to `logging_resource_adaptor`, we can just add an optional spdlog sink to the `pool_memory_resource` ctor.

**Comment by harrism** [comment]
> Similar to `logging_resource_adaptor`, we can just add an optional spdlog sink to the `pool_memory_resource` ctor.

The log is not specific to `pool_memory_resource`, so that won't be sufficient.

**Comment by rongou** [comment]
@jlowe can this be considered fixed now?

**Comment by jlowe** [comment]
While we can workaround the undesired `rmm_log.txt` file by forcing RMM logging off during the build, I think it would be more ideal to not completely suppress these messages but instead direct them to a more appropriate location (e.g.: stdout, stderr, or some application-specific handling).  Being able to provide a custom spdlog sink for RMM's internal logging should cover those cases and hopefully not be burdensome to implement.

**Comment by harrism** [comment]
Yeah planning to add config options in 0.17

**Comment by jlowe** [comment]
This is still desired. It was originally targeted for 0.17, but I do not think it was implemented.

**Comment by jlowe** [comment]
Still desired.

**Comment by jlowe** [comment]
Still desired.

**Comment by harrism** [comment]
@jlowe spdlog provides a way to add and remove sinks from already running loggers. We could provide an RMM specific way of specifying a new sink, but it would be less general than the [API that spdlog already provides](https://github.com/gabime/spdlog/wiki/4.-Sinks#adding-sinks-to-the-logger-after-creation). Currently you can do this (not thread safe):

```
auto sinks_vector = rmm::logger()->sinks();
sinks_vector.erase(sinks_vector.begin()); // remove the first sink (assuming it is the default
sinks_vector.push_back(std::make_shared<new_sink>(...));
```

You can also add new sinks without deleting the existing sink(s).  See https://github.com/gabime/spdlog/issues/820

Is this sufficient, or do you think we need to provide RMM-specific wrappers for this functionality?

**Comment by jlowe** [comment]
Thanks, @harrism! I didn't realize we could replace a sink on an existing log.  I think that should be sufficient to do what we need.

**Comment by harrism** [comment]
> Thanks, @harrism! I didn't realize we could replace a sink on an existing log. I think that should be sufficient to do what we need.

I didn't either, but when I started to look at fixing this, I discovered it.
