### ISSUE TITLE
[FEA] Refactor `device_scalar` in terms of `device_uvector` and fix asynchrony 

### ISSUE THREAD

**Issue by jrhemstad** [rapidsai/rmm#570]
**Is your feature request related to a problem? Please describe.**

`device_scalar` is a convenience type to represent a single value in device memory. Anywhere a `device_scalar` is used, a single element `device_uvector` could be used.

`device_scalar` was implemented before `device_uvector` existed, and therefore there is a lot of redundancy between the two. 

Furthermore, the asynchrony of `device_scalar` is incongrous with `device_uvector`. The `device_scalar::set_value` is asynchronous, but it's name does not tell you that. 

We've iterated on this quite a bit, and I feel `device_uvector` demonstrates the ideal design. If a function is asynchronous (doesn't synchronize the stream) it should be suffixed with `_async`. Otherwise it is synchronous and syncs the stream. 

**Describe the solution you'd like**

Refactor `device_scalar`s implementation to be implemented in terms of a single element `device_uvector`. Furthermore, reimplement functions like `set_value` in terms of `device_uvector::set_element`.

Likewise, `device_scalar::set_value` should be made synchronous and `device_scalar::set_value_async` should be added as an asynchronous variant.

**Comment by JustPlay** [comment]
https://github.com/rapidsai/rmm/issues/557
