### ISSUE TITLE
[BUG] documentation example doesn't compile

### ISSUE THREAD

**Issue by germasch** [rapidsai/rmm#593]
**Describe the bug**

In the `README.md` of current `branch-0.16`, it gives this example

```cxx
rmm::mr::device_memory_resource* mr = rmm::mr::get_current_device_resource(); // Points to `cuda_memory_resource`
// Construct a resource that uses a coalescing best-fit pool allocator
rmm::mr::pool_memory_resource<rmm::mr::cuda_memory_resource>> pool_mr{mr}; 
rmm::mr::set_current_device_resource(&pool_mr); // Updates the current device resource pointer to `pool_mr`
rmm::mr::device_memory_resource* mr = rmm::mr::get_current_device_resource(); // Points to `pool_mr`
```

This doesn't compile, because the `pool_mr` ctor expects its argument to be `rmm::mr::cuda_memory_resource *`. I'm not quite sure what the best way of fixing this, I suppose one way would be to use `rmm::mr::device_memory_resource` as template arg for `pool_mr`, though that hides the actual type of the underlying allocator.

**Comment by harrism** [comment]
Good catch. I think this is just an artifact of legacy behavior. I think the example should explicitly construct a `cuda_memory_resource` as we typically do, rather than using the current resource.
