### ISSUE TITLE
[FEA] Add `polymorphic_allocator` 

### ISSUE THREAD

**Issue by jrhemstad** [rapidsai/rmm#605]
**Is your feature request related to a problem? Please describe.**

I would like to be able to use a `rmm::mr::device_memory_resource` with an interface that expects a `std::allocator` interface, e.g., https://github.com/NVIDIA/cuCollections/pull/57.

We already have [`thrust_allocator_adaptor`](https://github.com/rapidsai/rmm/blob/branch-0.16/include/rmm/mr/device/thrust_allocator_adaptor.hpp), but that only works in situations that expect the strongly typed `device_ptr<T>` type returned from the allocator. 

**Describe the solution you'd like**

An `rmm::mr::polymorphic_allocator` class similar to [`std::pmr::polymorphic_allocator`](https://en.cppreference.com/w/cpp/memory/polymorphic_allocator) whose allocate/deallocate operate on raw pointers.

What I'm still unsure about is where the `stream` should be inserted. We could make it an argument to the `polymorphic_allocator` constructor and then `allocate/deallocate` just always use that stream. Or, `allocate/deallocate` would be made to take a stream argument. Or we could do both and provide overloads for `allocate/deallocate` that do/do not take a stream, and the variant that doesn't take a stream uses the stored stream.

**Comment by harrism** [comment]
As you know, storing a stream is generally dangerous.

**Comment by harrism** [comment]
Fixed by #609. https://github.com/rapidsai/rmm/pull/609
