### ISSUE TITLE
[BUG] import-time exception on non-GPU systems rather than upon use

### ISSUE THREAD

**Issue by lmeyerov** [rapidsai/rmm#616]
**Describe the bug**

On an OS X docker, `import cudf` triggers `ImportError: libcuda.so.1: cannot open shared object file: No such file or directory` on `rmm/_lib/__init__.py`  . We expect the error to only occur upon calling a `cudf` method, not `import`, to simplify cross-platform activities like CPU CI for non-GPU portions.

**Steps/Code to reproduce bug**

```
 sudo docker run --rm -it --entrypoint=/bin/bash graphistry/graphistry-forge-base:v2.33.2 -c "source activate rapids && python3 -c 'import cudf'"
```

**Expected behavior**

Import to proceed as usual, potentially initializing RMM if a GPU is available

**Environment overview (please complete the following information)**

OS X -> docker -> nvidia base docker -> conda RAPIDS 0.16a nightly --- see above docker image w/ in-the-clear install steps

**Additional context**

There was an earlier issue around something similar. I could not find, but I was under the impression that the above was intended to work. AFAICT, issue is on cudf->rmm handoff, and historically, these get punted back to cudf.

**Comment by kkraus14** [comment]
Transferred to RMM this is coming from RMM code as opposed to cudf code.

@lmeyerov this comes from us using the CUDA Driver API in certain places in the RMM Cython code, for which we link against `libcuda.so` in order to do. You should be able to install the driver library component in the docker image / container which would resolve the problem, which is what we do in our CPU CI jobs.

For importing on non-GPU systems, what functionality are you looking for / hoping to work? I'd like to understand if we dynamically loaded the driver library instead of linked it if that would work for you.

**Comment by lmeyerov** [comment]
Thanks @kkraus14!

For an interim workaround, we ended up wrapping all our `cupy` / `cudf` / etc. imports (`import wrapped_cudf as cudf` -> `if GPU_MODE: from cudf export *`), but that's a PITA for normal people, prevents type analysis, etc.


---

RE: "install the driver library component", any pointers on that?

We currently do @ https://hub.docker.com/layers/graphistry/graphistry-nvidia/v2.32.0/images/sha256-d95f9ff5c77f27482788bc53b380a79dcf9d1e0e09ee4a30bcda59e992848b14?context=explore :

```
FROM nvidia/cuda:${CUDA_SHORT_VERSION}-runtime-ubuntu18.04
...
  && /conda/bin/conda install \
        --yes --freeze-installed \
        -c $RAPIDS_CHANNEL -c nvidia -c conda-forge -c defaults \
        python=$PYTHON_VERSION \
        rapids=$RAPIDS_VERSION \
        cudatoolkit=$CUDA_SHORT_VERSION
```

So something like, a CPU-flavor release that does some sort of additional lib install?

--

Non-GPU systems, if this helps:

Use cases:
 
* Local dev on non-GPU boxes, such as on CPU portions of shared code. Ideally can get type hinting and run local CPU unit test. We run in docker which should ease things. Re-export stubbing worked for local CPU testing but not hinting, and imo better to solve at cudf/infra level like you're thinking, vs. global user code transform. 

* Local CPU data science backed by a remote GPU cluster: Figuring out a way to install cudf locally for type hinting etc. would be pretty awesome, esp. when actual exec is remote (e.g., dask). This is something we're thinking about for graphistry users in fact, as often they don't want to think about the GPU servers, are sitting on CPU notebooks, and want ~infinite remote exec for the GPU stuff.

* CI: Some CPU path tests within RAPIDS-sharing code, or integration tests involving CPU-paths of RAPIDS-containing code. So docker-on-CPU-host CI's should work somehow. Right now, we have an env var to specify whether to load our stub or actual GPU libs, and the test suites are configured to run the right tests.


Put together, our ideal is cudf imports fine, including enough info for type hinting, and only blows up if used with no actual GPUs. We're ok with undefined behavior on that, though a hygienic Exception type would be nice.

* Blocking that, it seems there is an cudf->RMM init issue that can be a friendlier exception
* Likewise, I'm unclear on what the concrete fix for libcuda.so is for CPU+GPU containers are for currently recommended use

Hope that helps!

**Comment by kkraus14** [comment]
> Blocking that, it seems there is an cudf->RMM init issue that can be a friendlier exception

We don't have much control over this unless we wrapped the import of every GPU library in a try except and caught the exception(s) when specific shared libraries failed to be found. I don't think we really want to take this on now as it would be pretty intrusive and error prone.

> RE: "install the driver library component", any pointers on that?

In our containers we currently do this: https://github.com/rapidsai/gpuci-build-environment/blob/branch-0.17/miniconda-cuda-driver/Dockerfile#L23-L29

You could also download the **driver** installation runfile from the driver download page (https://www.nvidia.com/Download/index.aspx) and then run it with `--no-kernel-module --no-drm` which would install only the driver library as far as I know, which allows the library to load successfully but will throw errors on trying to use any functions.

**Comment by kkraus14** [comment]
> In our containers we currently do this: https://github.com/rapidsai/gpuci-build-environment/blob/branch-0.17/miniconda-cuda-driver/Dockerfile#L23-L29
> 
> You could also download the **driver** installation runfile from the driver download page (https://www.nvidia.com/Download/index.aspx) and then run it with `--no-kernel-module --no-drm` which would install only the driver library as far as I know, which allows the library to load successfully but will throw errors on trying to use any functions.

Alternatively, you could symlink the `libcuda.so` stub library from `/usr/local/cuda/lib64/stubs/libcuda.so` to somewhere either in the `LD_LIBRARY_PATH` or in the standard search path to a `libcuda.so.1` symlink. This would guarantee the versioning of the CUDA driver is correct, but there's strong guarantees of backwards compatibility in the CUDA driver API.

**Comment by harrism** [comment]
@lmeyerov @kkraus14 is this still relevant?

**Comment by kkraus14** [comment]
Provided a sufficient workaround previously, closing this.
