### ISSUE TITLE
Use rmm pool memory allocation/deallocation inside a kernel

### ISSUE THREAD

**Issue by ivandrodri** [rapidsai/rmm#617]
Hello,

I would like to use a heap device memory pool in my project to speed up dynamical allocation/deallocation operations. 
I would like to know if it is possible to allocate/deallocate memory inside the kernels with rmm.

I have in my code a struct like this:

struct Obj{
unsigned int* bitMap;
}

and I create objects like the one below on the device:

Obj* obj;
size_t dimObj = 30 * 30 * 30;
cudaMalloc( (void**)&obj, dimObj*sizeof(Obj));

the bitMap pointers in obj are created and destroyed dynamically inside the kernels and their could be large like 40 * 40 * 40, for instance.

Is it possible to use rmm in my project? If not, do you know if is there a pool memory that allows me to allocate/deallocate memory inside a CUDA kernel?

Thanks for any help!

**Comment by jrhemstad** [comment]
RMM is a _host_-side allocator and cannot be used from inside device code. 

You're looking for a _device_-side pool allocator. There's a few examples of these out there:
- https://github.com/canonizer/halloc
- https://github.com/owensgroup/SlabAlloc

**Comment by ivandrodri** [comment]
Thank you very much!

**Comment by jakirkham** [comment]
Would it work to preallocate memory to pass into the kernel (via an argument)?

**Comment by ivandrodri** [comment]
@jakirkham: do you mean to pass a memory block into the kernel in order to use it as a memory pool? I am not sure if that could work as I need to allocate and deallocate the bitmap pointers at runtime and keep track of the deallocated ones.

**Comment by jakirkham** [comment]
Yeah

Gotcha. I'm just wondering if doing all that allocating/deallocating within the kernel makes things slow. Maybe just allocating a big enough block of memory as a workspace beforehand might help. Though I don't know your usage pattern well so YMMV.

**Comment by leofang** [comment]
Manual memory management like what John said is also the strategy I heard for addressing such needs. The downside is a good memory manager (like rmm) can't be used, and likely doing it by oneself is better than using 3rd party solutions, as usually this need is application-specific...

**Comment by harrism** [comment]
Hybrid host-side/device-side device memory pool management is definitely something I'm interested in long term, but it's a hard problem, especially with respect to concurrency...
