### ISSUE TITLE
[FEA] Simplify rmm::exec_policy

### ISSUE THREAD

**Issue by jrhemstad** [rapidsai/rmm#620]
**Is your feature request related to a problem? Please describe.**

RMM currently provides [an `rmm::exec_policy` convenience function](https://github.com/rapidsai/rmm/blob/ae915ea3b0fe733525a0085d571fc05fab001cc2/include/rmm/thrust_rmm_allocator.h#L56-L66) for creating a Thrust execution policy using a custom `rmm::thrust_allocator` that executes on a stream. Because of eccentricities of Thrust at the time I wrote `exec_policy`, usage ended up looking like:
```
thrust::sort(exec_policy(stream)->on(stream), ...);
```
`exec_policy(stream)` returned a `unique_ptr` to a Thrust execution policy where you had to invoke `on(stream)`. 

Not only is this annoying (because you have to pass `stream` twice), it's also error prone because users frequently attempt to do:
```
auto policy = exec_policy(stream)->on(stream);
thrust::sort(policy, ...);
```
This is invalid code as it leaves a dangling pointer.

**Describe the solution you'd like**

Thrust in 10.2 added new functionality to execution policies to allow passing an [allocator as an r-value ](https://github.com/NVIDIA/thrust/blob/bc7412a6275c641da0e5207ad671531100eaf694/thrust/detail/allocator_aware_execution_policy.h#L77-L82). We used to have to support older versions of CUDA and we also didn't used to use CPM to fetch the latest version of Thrust from GitHub. Now that we can rely on having the latest version of Thrust, we can simplify `rmm::exec_policy` significantly.

The implementation can now become:
```
inline auto exec_policy(cuda_stream_view const &stream = cuda_stream_view{})
{
   return thrust::cuda::par(rmm::mr::thrust_allocator<char>(stream)).on(stream);
}
```

What's more, the usage of `exec_policy` can now be simplified to:
```
thrust::sort(rmm::exec_policy(stream), ...);
```

There's no fear of dangling pointers anymore either, you can safely do:
```
auto policy = rmm::exec_policy(stream);
thrust::sort(policy, ...);
```

**Comment by germasch** [comment]
👍  up from me, since I've run into exactly that dangling pointer problem before (at least I think that's what it was).
