### ISSUE TITLE
[BUG] Memory Event Logging doesn't file standard time format

### ISSUE THREAD

**Issue by felipeblazing** [rapidsai/rmm#624]
**Describe the bug**
This is what allocator log Time column looks like in rmm
```
Thread,Time,Action,Pointer,Size,Stream
24171,17:00:05:157977,allocate,0x7fd940000000,672,0x0
24171,17:00:05:231763,allocate,0x7fd940000300,132151840,0x0
```

If `17:00:05:231763` were to be `17:00:05.231763` or even better if it included the date as well we could easily read these values in as csv. As it currently stands cudf and pandas cannot parse this date because it uses the ":" instead of the "."  to seperate the seconds from its decimal component. 

Right now to read this in cudf. I am reading Time as a string. Seperating it out into the components on the left and right side of the final right column. Recomposing the time and adding that to some date while praying that the tests were not launched shortly before midnight.

**Expected behavior**
I would expect to be able to consume the logs that are generated by the allocator with pandas and cudf.

**Comment by jrhemstad** [comment]
Easy enough to change, just change this line:
https://github.com/rapidsai/rmm/blob/b1ac4459b30f0c2063ea85996b2f0375f1d9df33/include/rmm/mr/device/logging_resource_adaptor.hpp#L184

to:
```
logger_->set_pattern("%t,%H:%M:%S.%f,%v"); 
```

**Comment by harrism** [comment]
This is still relevant.
