### ISSUE TITLE
[BUG] Targeting multiple devices in Python

### ISSUE THREAD

**Issue by pentschev** [rapidsai/rmm#628]
Today it's possible to replace CuPy's and Numba's memory manager with RMM. Things work well when we have multiple processes where device 0 points to a specific device when using `CUDA_VISIBLE_DEVICES`. However, it seems that this isn't the case if we try to address multiple devices in a single process, consider the following example:

```
import numba.cuda
import rmm

# Initialize a 1GB RMM pool on device 0
rmm.reinitialize(initial_pool_size=int(1e9), pool_allocator=True)

# Create a context and switch to device 1
numba.cuda.select_device(1)

# Reinitialize the RMM pool on device 0 to 2GB.
# It was expected that this would initialize a memory pool on device 1 instead.
rmm.reinitialize(initial_pool_size=int(2e9), pool_allocator=True)
```

As suggested by @jrhemstad in an offline conversation, it seems that RMM may be implicitly setting device index always to 0. Is this a bug or could there be any other reason why this wouldn't work?

**Comment by harrism** [comment]
`rmm.reinitialize()` takes a list of devices. It iterates over that list and creates a new memory resource for each device, and sets it as the per-device resource for that device.

Did you try this?

**Comment by pentschev** [comment]
Sorry @harrism , I did indeed miss that initially, thanks for pointing this out. What I was trying to do is to rely on the current device, as that is what CuPy and Numba do, probably for that reason it slipped my mind to consider the `devices` argument. Anyway, the original question is answered so I'm closing this, apologies for the noise.

Maybe at some point it would be worth considering whether the CUDA device currently set should be respected, but I don't really have any concrete reasons to think this is really necessary, so we can skip this for the future, should it indeed be required.

**Comment by harrism** [comment]
I think we indeed should consider that. @shwina @kkraus14 what do you think, should passing `None` for the `devices` parameter of `rmm::reinitialize` use the current device rather than device 0? That would match typical CUDA behavior better IMO, but you may have a reason for choosing device zero.
