### ISSUE TITLE
[FEA] Stream invalidation API

### ISSUE THREAD

**Issue by mzient** [rapidsai/rmm#649]
**Is your feature request related to a problem? Please describe.**
Stream handles are reused aggressively by CUDA driver. It's possible to get the same handle value for a new stream immediately after calling `cudaEventDestroy` on a stream which still has some outstanding work.
The problem: passing the new-old handle to the stream ordered allocator can immediately return a block that's still in use by the old stream.

**Describe the solution you'd like**
Add a function to device_memory_resource that would indicate that the caller is about to lose control of the stream's lifetime. This is potentially the last call to the resource in which this handle still refers to the same stream as was passed to previous calls. This would prevent memory deallocated on this stream from being reused with the same handle value (at least before we know that the memory is not used any more).
```C++
  /**
   * @brief Prevents the resource from immediately reusing the memory freed on that stream.
   */
  virtual void invalidate_stream(cudaStream_t stream) = 0;
```

A trivial implementation of the function would be to call `cudaStreamSyncrhonize`, effectively making sure that no memory freed on that stream is used any more.

**Describe alternatives you've considered**
Stack multiple resources and destroy the downstream one - seems inefficient and it would require changing streams between upstream and downstream resources.

**Additional context**
Let's consider a library function running on a user-provided stream. The library does some processing (which may involve allocation of memory), but after returning control to the caller, it can't be sure how long that stream is going to live. The pessimistic scenario is that the stream is destroyed and a new one is created with the same handle value. Subsequent calls to our library function should not attempt to reuse memory freed in the previous call, because it was done on a different stream.

**Comment by jrhemstad** [comment]
For reference, the currently documented requirements are that it is undefined behavior to destroy a stream that has been passed to [`device_memory_resource::deallocate`](https://github.com/rapidsai/rmm#stream-ordered-memory-allocation). So the situation you describe is expressly disallowed by the current requirements. However, I absolutely recognize that this is far from ideal, so I'm definitely open to exploring alternatives. 

> A trivial implementation of the function would be to call cudaStreamSyncrhonize

If the stream passed to `invalidate_stream` were dead/destroyed, then you couldn't call `cudaStreamSyncrhonize` on that stream as you'd be using a destroyed object.

**Comment by mzient** [comment]
> If the stream passed to invalidate_stream were dead/destroyed, then you couldn't call cudaStreamSyncrhonize on that stream as you'd be using a destroyed object.

OK, that's not what I mean, I'll update the description. The intention was: this is the last call to the resource with that stream still valid.

**Comment by jrhemstad** [comment]
> OK, that's not what I meant, I'll update the description. The intention was: this is the last call to the resource with that stream still valid.

Okay, I think I understand now. You would call `invalidate_stream` _before_ destroying the stream.

**Comment by mzient** [comment]
Unfortunately, it is. See the following example:
```C++
#include <cuda_runtime.h>
#include <stdio.h>

int main() {
    void *mem;
    size_t size = 1<<28;
    cudaEvent_t ev1, ev2;
    cudaEventCreateWithFlags(&ev1, cudaEventDisableTiming);
    cudaEventCreateWithFlags(&ev2, cudaEventDisableTiming);
    cudaMalloc(&mem, size);
    cudaMemset(mem, 0, size);
    cudaStream_t s1, s2;
    cudaStreamCreateWithFlags(&s1, cudaStreamNonBlocking);
    cudaMemsetAsync(mem, 0xcc, size, s1);
    cudaEventRecord(ev1, s1);
    cudaStreamDestroy(s1);
    cudaStreamCreateWithFlags(&s2, cudaStreamNonBlocking);
    cudaEventRecord(ev2, s2);
    int status2 = cudaEventQuery(ev2);
    int status1 = cudaEventQuery(ev1);

    int tmp = -1;
    cudaMemcpyAsync(&tmp, (char*)mem + size-4, 4, cudaMemcpyDeviceToHost, s2);
    printf("%i %i %p %p %u\n", status1, status2, s1, s2, tmp);
    cudaStreamDestroy(s2);
    cudaEventDestroy(ev1);
    cudaEventDestroy(ev2);
    cudaFree(mem);
    return 0;
}
```
The example result is:
`600 0 0x5594ef6cb880 0x5594ef6cb880 0`
Which means:
600 - event 1 is still not ready
0 - event 2 is ready
0x5594ef6cb880 0x5594ef6cb880 - handles for the streams are equal (both are 0x5594ef6cb880)
0 - the memory at the end of the region to `cudaMemset` is still 0 (not 0xcccccccc)

I've also tried to reverse-engineer what CUstream is - and dereferenced it as a void** pointer.
That value changes between s1 and s2. However, if I insert `cudaEventSyncrhonize(ev1)` before creating stream s2, the value pointed to by the stream handle doesn't change. Apparently there's some extra level of indirection and the user-facing handles are recycled immediately, because they do not describe actual GPU resource, but merely point to some intermediate structure.

**Comment by harrism** [comment]
Hrmmmm. This is frustrating. I modified your program to synchronize `s2` after the first event queries, and then query ev1 again in the hopes that they are actually the same stream.

```
#include <cuda_runtime.h>
#include <stdio.h>

int main() {
  void *mem;
  size_t size = 1 << 28;
  cudaEvent_t ev1, ev2;
  cudaEventCreateWithFlags(&ev1, cudaEventDisableTiming);
  cudaEventCreateWithFlags(&ev2, cudaEventDisableTiming);
  cudaMalloc(&mem, size);
  cudaMemset(mem, 0, size);
  cudaStream_t s1, s2;
  cudaStreamCreateWithFlags(&s1, cudaStreamNonBlocking);
  cudaMemsetAsync(mem, 0xcc, size, s1);
  cudaEventRecord(ev1, s1);
  cudaStreamDestroy(s1);
  cudaStreamCreateWithFlags(&s2, cudaStreamNonBlocking);
  cudaEventRecord(ev2, s2);
  int status2 = cudaEventQuery(ev2);
  int status1 = cudaEventQuery(ev1);

  cudaStreamSynchronize(s2);
  int status3 = cudaEventQuery(ev1);

  int tmp = -1;
  cudaMemcpyAsync(&tmp, (char *)mem + size - 4, 4, cudaMemcpyDeviceToHost, s2);
  printf("%i %i %i %p %p %x\n", status1, status2, status3, s1, s2, tmp);
  cudaStreamDestroy(s2);
  cudaEventDestroy(ev1);
  cudaEventDestroy(ev2);
  cudaFree(mem);
  return 0;
}
```

Alas, the output is `600 0 600 0x561c7f4175b0 0x561c7f4175b0 0`. `ev1` is still not ready (note second `600`).

**Comment by harrism** [comment]
We don't plan to implement this. We have other approaches for isolating streams within RMM, such as "substreams", and the stream pool.
