### ISSUE TITLE
[FEA] Decouple memory kind from allocation modality

### ISSUE THREAD

**Issue by harrism** [rapidsai/rmm#660]
RMM currently has two memory allocation interfaces: `device_memory_resource` and `host_memory_resource`. The former is stream-ordered, and the latter is synchronous. 

There are blurred lines for memory that is accessible from both host and device; for example pinned host memory or managed memory. One might like to have synchronous allocation if the main or first use of the memory will be from the host; or stream-ordered memory allocation if the memory will be mainly used from the device, or deallocated after being used on the device without synchronization.

@jrhemstad and I have discussed decoupling memory kind (host, device, pinned, managed) from allocation modality (stream-ordered, synchronous). This would allow constructing synchronous memory resources for allocating device memory, stream-ordered memory resources for allocating pinned host or managed memory, etc.

**Comment by jrhemstad** [comment]
Here is an initial idea of what this could look like: 

```
enum class MemoryKind {
 Host = 1
 Device = 2,
};
template <MemoryKind kind>
class memory_resource {
   // returned pointer is immediately available for use (either on host or on any stream)
   virtual void* allocate(std::size_t n, std::align_val_t alignment);
   virtual void deallocate(void *p, std::size_t n, std::align_val_t alignment);
};
template <MemoryKind kind>
class stream_memory_resource {
    virtual void* allocate(std::size_t n, std::align_val_t alignment, cuda_stream_view s);
    // this is provided for convenience so you can specify alignment/stream in either order
    void* allocate(std::size_t n, cuda_stream_view s, std::align_val_t alignment){
       return this->allocate(n, s, alignment); 
    }
    virtual void deallocate(void *p, std::size_t n, std::align_val_t alignment, cuda_stream_view s);
    // this is provided for convenience so you can specify alignment/stream in either order
    void deallocate(void* p, std::size_t n, cuda_stream_view s, std::align_val_t alignment){
       deallocate(p, n, alignment, s);
    }
};
// existing host and device_memory_resource types would become aliases
using host_memory_resource = memory_resource<MemoryKind::Host>;
using device_memory_resource = stream_memory_resource<MemoryKind::Device>;
```

Something we still need to figure out is support for @mzient's idea of a "stream bound resource", i.e., a resource that is bound to a particular stream at construction and only allocates on that stream. It would be similar to a `memory_resource`, but the returned pointer would only be safe to use on the bound stream. This would be a violation of the `memory_resource` interface as defined above. The goal is to be able to reuse pool resource machinery for both a `memory_resource` and `stream_bound_resource`.

**Comment by mzient** [comment]
One idea is to add one more enum parameter that specifies timing/order:

```c++
enum class memory_kind {
  host = 0, pinned, device, managed,
  count
};

enum class allocation_order {
  // allocation and deallocation is synchronized with the calling host thread
  host,
  // allocation and deallocation is synchronized with an associated stream
  stream
};

template <memory_kind kind, allocation_order order>
class memory_resource {
// ...
};

using host_memory_resource = memory_resource<memory_kind::host, allocation_order::host>;
using stream_bound_esource = memory_resource<memory_kind::device, allocation_order::stream>;
```

This allows one to use `memory_resource<kind, order>` to implement suballocators for all memory kinds and orderings while preventing mixing of interfaces.

**Comment by harrism** [comment]
This is being handled by https://github.com/NVIDIA/libcudacxx/pull/105
