### ISSUE TITLE
[FEA] Add Cython / Python wrappers for `rmm::cuda_stream_pool`

### ISSUE THREAD

**Issue by harrism** [rapidsai/rmm#664]
I refrained from doing the Python for the CUDA stream pool added in #659 myself because I'm not sure what the right approach is for Python.  But I think we should add a Python interface, so I'm opening this issue for discussion.

CC the usual suspects: @shwina @kkraus14 @pentschev @jakirkham

**Comment by harrism** [comment]
Also CC @teju85 @afender @cjnolet as potential users.

**Comment by jakirkham** [comment]
Thanks! Yeah checking with Peter when he's back from holiday sounds like the right approach 🙂

cc @quasiben (for vis)

**Comment by pentschev** [comment]
I think this is a very useful feature for Python too. I think a good initial approach is to treat it as we do for the memory pool, at `rmm.reinitialize` the user decides whether to use a stream pool or not, then asking for a new non-default `Stream` object will return a stream from the pool. I think I may be oversimplifying things in my head and overlooking potential pitfalls, but nevertheless I think we may want to try to simplify usability in Python.

**Comment by kkraus14** [comment]
@shwina is this done with the new Cython classes for owning / non-owning streams?

**Comment by shwina** [comment]
@isVoid and I are still investigating stream use in Python, and working on a stream pool abstraction.

In our initial work, we found it more convenient to just use a Python list of `Stream` objects to hold a stream pool. This is because a Stream object in Python can be backed by more than just an `rmm::cuda_stream_view`, including Numba or CuPy owned streams.

We can keep this issue open until we have an implementation finalized, but I think we can close it safely.

**Comment by kkraus14** [comment]
> In our initial work, we found it more convenient to just use a Python list of `Stream` objects to hold a stream pool. This is because a Stream object in Python can be backed by more than just an `rmm::cuda_stream`, including Numba or CuPy owned streams. Whereas `rmm::cuda_stream_pool` is strictly a wrapper around a vector of `rmm::cuda_stream` objects.

Yes, but if everyone is creating their own pool of streams, that's quite a bit of streams to create which is non-free. Ideally we could all share a reasonably sized pool of streams in the future 😄

**Comment by jakirkham** [comment]
PR ( https://github.com/rapidsai/rmm/pull/818 ) appears relevant

cc @divyegala (for awareness)

**Comment by divyegala** [comment]
@jakirkham my use-case only needs the cython extensions for `rmm::cuda_stream_pool`. Should I also write the python extended class for it?

**Comment by jakirkham** [comment]
Starting with Cython seems fine. Can always be extended for Python later as needed

**Comment by harrism** [comment]
Should we close this with #818, or do we need more Python?

**Comment by shwina** [comment]
There's no (immediate) need for a Python abstraction around a `cuda_stream_pool` in `cuDF`, but perhaps other libraries need it? @divyegala?

**Comment by divyegala** [comment]
@shwina there's no immediate need in RAFT/cuML/cuGraph either

**Comment by shwina** [comment]
Thanks! Closing this out then.
