### ISSUE TITLE
[BUG] RMM Python Docs use nonexistant rmm.to_device() method

### ISSUE THREAD

**Issue by lphan** [rapidsai/rmm#668]
**Describe the bug**
AttributeError: module 'rmm' has no attribute 'to_device'

**Steps/Code to reproduce bug**
Step 1: Install RAPIDS from RAPIDS.ai 
conda create -n rapids-0.17 -c rapidsai -c nvidia -c conda-forge  -c defaults rapids-blazing=0.17 python=3.7 cudatoolkit=10.2

Step 2: activate environment rapids-0.17
conda activate rapids-0.17

Step 3: 
import rmm
import numpy as np

### DeviceBuffer represents an untyped, uninitialized device memory allocation. DeviceBuffers can be created by providing the size of the allocation in bytes
buf = rmm.DeviceBuffer(size=100)
print("Buffer Size: ", buf.size, "Buffer Pointer: ", buf.ptr)

### DeviceBuffers can also be created by copying data from host memory
a = np.array([1, 2, 3], dtype='float64')
buf = rmm.to_device(a.tobytes())
print(buf.size)

### Source: https://docs.rapids.ai/api/rmm/stable/basics.html

**Expected behavior**
function to_device should exist or documentation should be updated.

or maybe do I miss something? 

Thank you for your work.
Best, Long Phan

**Comment by ysq151944** [comment]
maybe the api is rmm.DeviceBuffer.to_device?

**Comment by lphan** [comment]
Thanks, it worked.

**Comment by Wuppus** [comment]
Documentation still says rmm.to_device
from https://docs.rapids.ai/api/rmm/stable/basics.html#installation stable(21.10)

import rmm
import numpy as np
a = np.array([1, 2, 3], dtype='float64')
buf = rmm.to_device(a.tobytes())
buf.size

**Comment by harrism** [comment]
Reopening and changing to a doc bug.

**Comment by shwina** [comment]
The `to_device()` method was removed in a previous method of RMM. The solution today is to use CuPy directly to allocate device arrays. See [here](https://github.com/rapidsai/rmm#using-rmm-with-cupy) for how to use RMM with CuPy.

**Comment by Wuppus** [comment]
Ok thanks!
