### ISSUE TITLE
[BUG]failed to import the rapids. returns File "rmm/_cuda/gpu.pyx", line 134, in rmm._cuda.gpu.getDeviceCount

### ISSUE THREAD

**Issue by terryaic** [rapidsai/rmm#675]
I use the conda version of rapids-0.17, it works well earlier, but today, it just failed at import the cudf/cuxfilter, etc.
the steps to reproduce this issue

conda activate rapids-0.17
python
import cuxfilter

the logs are as following
(rapids-0.17) terry@terry-MS-7B94:~$ python
Python 3.8.5 (default, Sep  4 2020, 07:30:14)
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cuxfilter
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/terry/anaconda202011/envs/rapids-0.17/lib/python3.8/site-packages/cuxfilter/__init__.py", line 1, in <module>
    from .dataframe import DataFrame
  File "/home/terry/anaconda202011/envs/rapids-0.17/lib/python3.8/site-packages/cuxfilter/dataframe.py", line 1, in <module>
    import cudf
  File "/home/terry/anaconda202011/envs/rapids-0.17/lib/python3.8/site-packages/cudf/__init__.py", line 4, in <module>
    validate_setup()
  File "/home/terry/anaconda202011/envs/rapids-0.17/lib/python3.8/site-packages/cudf/utils/gpu_utils.py", line 63, in validate_setup
    raise e
  File "/home/terry/anaconda202011/envs/rapids-0.17/lib/python3.8/site-packages/cudf/utils/gpu_utils.py", line 60, in validate_setup
    gpus_count = getDeviceCount()
  File "rmm/_cuda/gpu.pyx", line 134, in rmm._cuda.gpu.getDeviceCount
rmm._cuda.gpu.CUDARuntimeError: cudaErrorUnknown: unknown error

I have tow GPU cards ,one is Titan RTX, and the other is RTX3090

**Comment by harrism** [comment]
Can you run `nvidia-smi` and report the output here?

**Comment by terryaic** [comment]
(rapids-0.17) terry@terry-MS-7B94:~$ nvidia-smi
Mon Jan 18 12:03:02 2021
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  TITAN RTX           Off  | 00000000:17:00.0 Off |                  N/A |
| 41%   28C    P8    14W / 280W |      5MiB / 24220MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  GeForce RTX 3090    Off  | 00000000:65:00.0 Off |                  N/A |
|  0%   34C    P8    11W / 350W |     23MiB / 24265MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      1401      G   /usr/lib/xorg/Xorg                  4MiB |
|    1   N/A  N/A      1401      G   /usr/lib/xorg/Xorg                  9MiB |
|    1   N/A  N/A      1728      G   /usr/bin/gnome-shell               12MiB |
+-----------------------------------------------------------------------------+

**Comment by harrism** [comment]
> I use the conda version of rapids-0.17, it works well earlier, but today, it just failed at import the cudf/cuxfilter, etc.
> the steps to reproduce this issue

If it worked earlier, and now fails, did something change between when it worked and now? Have you tried rebooting?

**Comment by terryaic** [comment]
no changes at all, but u are right, i reboot the machine, and it works now.

**Comment by harrism** [comment]
Great! Glad you got it working again! I'm going to close this. Please let us know if there are further problems.

**Comment by pkgandhi** [comment]
@harrism : I am facing the same issue. The only additional thing is that when I suspend my machine and turn back on, I get the same error as @terryaic. Is rebooting the only option? Thank you.

**Comment by kkraus14** [comment]
> @harrism : I am facing the same issue. The only additional thing is that when I suspend my machine and turn back on, I get the same error as @terryaic. Is rebooting the only option? Thank you.

This means something with the driver isn't working as expected when you suspend the machine. Unfortunately that's not something we can control in RAPIDS code.

**Comment by Hoxbro** [comment]
This also happens to me when I have a jupyter notebook open with a cuda related import like `cudf` when going to sleep. I have written a small script that kills all my `ipykernel`s and restarts `nvidia_uvm`, this way I don't need to restart my computer. 

``` bash
#!/usr/bin/env bash
pgrep -f ipykernel | xargs -r -l1 kill

sudo rmmod nvidia_uvm
sudo modprobe nvidia_uvm
```
