### ISSUE TITLE
[BUG]   AttributeError: module 'rmm' has no attribute 'rmm_cupy_allocator' when building from source

### ISSUE THREAD

**Issue by timothynest** [rapidsai/rmm#677]
**Describe the bug**
I've installed rmm from source (necessary for installation on my HPC cluster which prohibits use of conda), and am unable to use 
cupy.cuda.set_allocator(rmm.rmm_cupy_allocator) 

Calling this as described in the documentation returns: module 'rmm' has no attribute 'rmm_cupy_allocator'

**Steps/Code to reproduce bug**

Install rmm from source on HPC cluster (namely compute canada):

### Build on headnode start
module load StdEnv/2020
module load python/3.7 gcc/9.3.0 cuda/11.0 openmpi/4.0.3 hwloc/2.4.0 cmake/3.18.4
module load boost/1.72.0 arrow/2.0.0 hwloc cuda

virtualenv --no-download virtualenv/nvlink
source virtualenv/nvlink/bin/activate
pip install 'fsspec>=0.3.3'
pip install 'msgpack>=1.0.2'
pip install cupy cython dask dask-cuda pandas jupyter nbserverproxy

git clone https://github.com/rapidsai/ucx-py.git
cd ucx-py
git checkout branch-0.18
LIBDIR="$EBROOTUCX/lib:$EBROOTHWLOC/lib64" python setup.py build_ext --inplace
pip install .
cd ..

module load StdEnv/2020 gcc/9 python/3.8 cuda
git clone --recurse-submodules https://github.com/rapidsai/rmm.git -b branch-0.17 && cd
rmm
export RMM_ROOT=$HOME/rmm
export INSTALL_PREFIX=$PWD
bash build.sh
cd ..
### Build on headnode end

request node with 2 gpus:

 salloc --nodes=1 --ntasks=1 --cpus-per-task=2 --time=02:59:00 --gres=gpu:2 --mem-per-cpu=4000M

#jupyter notebook

import cupy as cp
import rmm

cp.cuda.set_allocator(rmm.rmm_cupy_allocator) throws:
AttributeError: module 'rmm' has no attribute 'rmm_cupy_allocator'

**Expected behavior**
With miniconda install this works fine.

**Comment by jakirkham** [comment]
Do you have CuPy installed?

**Comment by timothynest** [comment]
Yes. cupy and all other packages are working fine.

**Comment by timothynest** [comment]
Interestingly dir(rmm) returns:

['__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__']

(none of the expected methods)

**Comment by timothynest** [comment]
Hi @kkraus14 rmm.__file__ outputs "None"

**Comment by kkraus14** [comment]
What about `rmm.__path__`?

**Comment by timothynest** [comment]
@kkraus14 I get :  _NamespacePath(['/home/user/rmm'])

**Comment by kkraus14** [comment]
Is that the install location of your `rmm` Python package? I'm not clear on your environment but it looks like you're building on a head node and then running on worker nodes? What ships the RMM package that you installed via `bash build.sh` onto the worker nodes?

**Comment by timothynest** [comment]
That is the location of the package. I'm building from within a virtual environment which appears to allow me to "import" but of course the methods are still inaccessible.

**Comment by harrism** [comment]
> '/home/user/rmm'

Is your username `rmm`?

**Comment by timothynest** [comment]
no. "user" is my username

**Comment by kkraus14** [comment]
> That is the location of the package. I'm building (on head node) from within a virtual environment which appears to allow me to "import" (on head or workers in whatever directory) but of course the methods are still inaccessible.

Is that the location of the source package or the built package? Running `bash build.sh` under the hood runs a `python setup.py install` which I'd expect to install in a `site-packages` folder or something similar.

It's possible that running `bash build.sh` will override the virtualenv that you activated. Could you try replacing `bash build.sh` with `pip install .`?

**Comment by akagamy55** [comment]
Close:(https://github.com/rapidsai/rmm.git)

**Comment by akagamy55** [comment]
Close:(#677)

**Comment by akagamy55** [comment]
Close:(?-Nesesita tiraje)

**Comment by akagamy55** [comment]
Close:(Pitón)

**Comment by akagamy55** [comment]
Close:([bicho])

**Comment by akagamy55** [comment]
Close:([BUGS])

**Comment by akagamy55** [comment]
Close:(build.sh)

**Comment by akagamy55** [comment]
Close:(setup.py install)

**Comment by akagamy55** [comment]
Close:(site-packages)

**Comment by akagamy55** [comment]
Close:(rmm.__file__)

**Comment by akagamy55** [comment]
Close:([[' doc ', 
' archivo ', 
' cargador ', 
' nombre ', 
' paquete ', 
' ruta ', 
' especificación '])

**Comment by akagamy55** [comment]
Cerrar:([rmm])

**Comment by akagamy55** [comment]
Closw:(salloc --nodes = 1 --ntasks = 1 --cpus-per-task = 2 --time = 02: 59: 00 --gres = gpu: 2 --mem-per-cpu = 4000M

#jupyter cuaderno

import cupy como cp 
import rmm

cp.cuda.set_allocator (rmm.rmm_cupy_allocator) arroja: 
AttributeError: el módulo 'rmm' no tiene el atributo 'rmm_cupy_allocator')

**Comment by akagamy55** [comment]
close:(carga del módulo StdEnv / 2020 
carga del módulo python / 3.7 gcc / 9.3.0 cuda / 11.0 openmpi / 4.0.3 hwloc / 2.4.0 cmake / 3.18.4 
aumento de carga del módulo / 1.72.0 flecha / 2.0.0 hwloc cuda

virtualenv --no-download virtualenv / nvlink 
fuente virtualenv / nvlink / bin / activar 
pip install 'fsspec> = 0.3.3' 
pip install 'msgpack> = 1.0.2' 
pip install cupy cython dask dask-cuda pandas jupyter nbserverproxy

git clone https://github.com/rapidsai/ucx-py.git
cd ucx-py 
git checkout branch-0.18 
LIBDIR = "$ EBROOTUCX / lib: $ EBROOTHWLOC / lib64" python setup.py build_ext --inplace 
pip install. 
discos compactos ..

módulo de carga StdEnv / 2020 gcc / 9 python / 3.8 cuda 
git clone --recurse-submodules https://github.com/rapidsai/rmm.git -b branch-0.17 && cd 
rmm 
export RMM_ROOT = $ HOME / rmm 
export INSTALL_PREFIX = $ PWD 
bash build.sh 
cd ..)

**Comment by kkraus14** [comment]
Closing as there's been no response to this. Please let us know if we should reopen it.
