### ISSUE TITLE
[FEA] Add a non-circular stream pool accessor + pool size accessor

### ISSUE THREAD

**Issue by afender** [rapidsai/rmm#689]
**Is your feature request related to a problem? Please describe.**
We (cuGraph/cuML) are looking at adopting `rmm::cuda_stream_pool` to replace the pool we have in RAFT. 
One of the concern is the circular behaviour of `get_stream()` because implementations in cuML access streams by their IDs in the pool. We would also like to be able to query the pool for its size.
The circular behavior pushes stream workload management on the RMM user side (to prevent adding work to a stream already buzzy or to assign the next task to a specific stream for instance). This is challenging to do with the current UI.

**Describe the solution you'd like**
We propose adding a `rmm::cuda_stream_pool::get_stream(stream_id)` and  `rmm::cuda_stream_pool::get_pool_size()` accessors which would allow legacy compatibility in cuML and immediate adoption of `rmm::cuda_stream_pool` in RAFT and cuGraph. This could co-exist with the current features in `rmm::cuda_stream_pool`. This should be a quick update and we would be happy to contribute this to RMM if you are ok with that. 

**Describe alternatives you've considered**
We could think of other mechanisms such as a release stream API to notify the pool that a stream is available after using it. 
This is more advanced and not required for our usage.

**Additional context**
Current RAFT stream pool : 
https://github.com/rapidsai/raft/blob/b5d5044347ee8be8c95241b4f0f4388e055665f4/cpp/include/raft/handle.hpp#L129

CC: @teju85 @seunghwak @cjnolet @BradReesWork

**Comment by jrhemstad** [comment]
We already had plans to add the equivalent of `rmm::cuda_stream_pool::get_stream(stream_id)`. 

What's the purpose of needing to query the pool size? Are you okay with that value changing over time? Since it's very early days with the stream pool I want to avoid tying our hands as much as possible until we've had more chance to kick the tires.

**Comment by jrhemstad** [comment]
Closed by https://github.com/rapidsai/rmm/pull/696
