### ISSUE TITLE
[FEA][DISCUSSION] Require C++17

### ISSUE THREAD

**Issue by harrism** [rapidsai/rmm#736]
In 0.20, RAPIDS libraries including libcudf will beginning adopting C++17 features in their implementations and likely require C++17 for their interfaces. We would like to do the same in RMM; however, since RMM is header-only, there is no difference between requiring C++17 for interfaces vs. implementation.  (Note RAPIDS will deprecate CUDA 10.x starting with the 0.19 release and require CUDA 11.0 or higher starting with the 0.20 release.)

I'm opening this issue to discuss any concerns with moving to requiring minimum C++17 to compile RMM.  This should not affect users CuPy that only interface with the RMM Python API.  However, there are other users of RMM C++ outside of core RAPIDS libraries, such as 

- [x] https://github.com/BlazingDB/blazingsql (@williamBlazing @felipeblazing)
- [x] https://github.com/psc-code/psc (@germasch)
- [x] https://github.com/rapidsai/xgboost (@hcho3 @JohnZed @trivialfis)
- [x] RMM Cython (@shwina @jakirkham)

Can the people I've tagged above please comment on whether you are OK with RMM requiring C++17 starting in release 0.20?

**Comment by hcho3** [comment]
I'm okay with it, since RMM is strictly an optional dependency of XGBoost. Users who have an older compiler (GCC 5.x) will be able to build XGBoost without RMM support.

**Comment by kkraus14** [comment]
cc @shwina @jakirkham for Cython perspective

**Comment by shwina** [comment]
Not sure if this will affect any of the public APIs that e.g., Python interfaces with. If so, this could potentially be a problem for Cython. Cython does not support many (any?) C++17-specific features. That being said, in many cases, it is possible to write Cython definitions for missingC++17 types/features quite easily. We can explore that on a case-by-case basis (and of course, upstream to Cython if possible).

**Comment by jakirkham** [comment]
Agree with Ashwin

IIUC this would also be helpful for solving some issues like `host_buffer` support ( https://github.com/rapidsai/rmm/issues/260 )

**Comment by kkraus14** [comment]
One thing that comes to mind for public APIs would be moving from `thrust::optional` to `std::optional`, so that's something we'd presumably need to support on the Cython side. Ideally we could prevent leaking the Thrust dependency for RMM Cython.

**Comment by harrism** [comment]
`std::optional` is the only C++17 feature I'm aware of that impacts the APIs that Cython would interface with.

**Comment by harrism** [comment]
> IIUC this would also be helpful for solving some issues like host_buffer support ( #260 )

Correct using C++17 std::pmr::memory_resource as a base for host memory resources will help with things like `host_buffer`.

Also, I assume supporting C++17 will make it easier to depend on the `device_memory_resource` functionality we are in the process of upstreaming to libcu++, which expands on `std::pmr` functionality (CC @jrhemstad).

**Comment by harrism** [comment]
> Cython does not support many (any?) C++17-specific features. 

@shwina Does Cython support compiling with the `--std=c++17` option?

**Comment by jakirkham** [comment]
Looks like there is already a Cython issue about `std::optional` ( https://github.com/cython/cython/issues/3293 ) and the start of a PR ( https://github.com/cython/cython/pull/3294 )

**Comment by shwina** [comment]
Yes, we can compile with `--std=c++17` (or really, any compiler flags of our choosing).

**Comment by felipeblazing** [comment]
I don't foresee this being a problem for us though I am guessing some of the changes will require us to do some reworking. We already are going to have to use c++17 for cudf.

**Comment by harrism** [comment]
@germasch do you have an opinion on this for PSC?

**Comment by germasch** [comment]
It's not necessarily my preference (neither is requiring CUDA-11) -- in the HPC world, software environments aren't necessarily upgraded all that quickly -- but I can see the point from the perspective of RAPIDS' rapid development ;) I don't think it will cause me any real troubles, though (and if so, I could stick with an older RMM). Thanks for checking!

**Comment by harrism** [comment]
Totally understand. The RAPIDS team has been waiting for CUDA to support C++17 for a while now. Adoption 4 years after standardization is not super quick. :)

RMM is also trying to better align with C++17 `std::pmr::memory_resource`

**Comment by kkraus14** [comment]
This was changed in #741 to require C++17. Closing.
