### ISSUE TITLE
[DOC] device_buffer constructor with initial data does not mention required synchronization

### ISSUE THREAD

**Issue by jlowe** [rapidsai/rmm#766]
The documentation for the [device_buffer constructor with source data](https://github.com/rapidsai/rmm/blob/branch-0.20/include/rmm/device_buffer.hpp#L105-L127) should mention the caller is responsible for synchronizing on the stream before releasing the source data buffer if the source data is in host memory.  The implementation always copies the source data asynchronously.

**Comment by harrism** [comment]
Agree we should document this better. However I think we should also make the API more consistent with device_uvector, where the streams and asynchronicity are more explicit. See #418
