### ISSUE TITLE
[QST] Query "usage" of objects managed by an RMM pool

### ISSUE THREAD

**Issue by randerzander** [rapidsai/rmm#815]
It's common to monitor nvidia-smi during workflow execution to observe memory usage patterns.

When using an RMM pool, most memory is allocated at process/cluster startup, thus making nvidia-smi less informative, as allocated memory looks static right up until an OOM failure.

Is there an RMM API which exposes the amount of memory being used by, say, a DataFrame or Series during runtime?

**Comment by harrism** [comment]
RMM knows nothing about DataFrame or Series or any other types. It only knows pointers and sizes.  I would think that cuDF could provide you the size of a DataFrame or Series.

**Comment by kkraus14** [comment]
@randerzander for DataFrame and Series there's the `memory_usage` API: https://docs.rapids.ai/api/cudf/nightly/api.html?highlight=memory_usage#cudf.core.dataframe.DataFrame.memory_usage

You can sum that to get the total memory usage of a DataFrame.

**Comment by harrism** [comment]
Thanks @kkraus14. @randerzander is that sufficient for your needs?

**Comment by randerzander** [comment]
Yes! Thanks!
