### ISSUE TITLE
[FEA] smart pointers (unique_ptr and shared_ptr) with custom deleters and device_buffer.

### ISSUE THREAD

**Issue by seunghwak** [rapidsai/rmm#82]
**Is your feature request related to a problem? Please describe.**
std::unique_ptr and std::shared_ptr support safer programming, but to use those with RMM, I need to define custom deleters that invoke RMM_FREE instead of C++'s default delete. Currently, every project using RMM should define its own, and this requires duplicated works. 

Also, cudf currently has device_buffer and this provides a wrapper for an RMM memory block (similar to thrust::device_vector with RMM allocator but does not incur initialization overhead). Other projects can benefit from this as well, and I hope RMM provides this feature rather than every project reimplementing its own.

**Comment by jrhemstad** [comment]
`rmm::device_buffer` fills this need.
