### ISSUE TITLE
[FEA] RMM_TRY and RMM_TRY_CUDAERROR

### ISSUE THREAD

**Issue by seunghwak** [rapidsai/rmm#83]
**Is your feature request related to a problem? Please describe.**
cudf has RMM_TRY and RMM_TRY_CUDAERROR. Other projects using RMM often need to redefine RMM_TRY and RMM_TRY_CUDAERROR. It will be better if RMM provides these macros.

And we may need no throw version (e.g. something like RMM_TRY_NOTHROW) mainly for class destructors and for RMM_FREE; class destructors are noexcept by default and if RMM_FREE with an erroneous parameter results in undefined behavior similar to std::free (https://en.cppreference.com/w/cpp/memory/c/free), it's better to crash the program after printing error than continue execution with undefined behavior.

**Comment by harrism** [comment]
Stale. Closing.
