### ISSUE TITLE
[QST]The difference between `cuda_async_memory_resource` and `pool_memory_resource`.

### ISSUE THREAD

**Issue by ZhenshengLee** [rapidsai/rmm#844]
@harrism Hi, that's a great job and I have a question for this.

As [cuda programming guide](https://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__HIGHLEVEL.html#group__CUDART__HIGHLEVEL_1ga31efcffc48981621feddd98d71a0feb) said, `cudaMallocAsync` is to allocate memory from a pool, so what's the difference between `cuda_async_memory_resource` and `pool_memory_resource`, I think both of them are about the concept of [Stream Order Memory Allocator](https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#stream-ordered-memory-allocator).

we can see the definition of  `pool_memory_resource` from https://github.com/rapidsai/rmm/blob/branch-21.10/include/rmm/mr/device/pool_memory_resource.hpp  as

```cpp
// third_party/rmm/include/rmm/mr/device/pool_memory_resource.hpp
template <typename Upstream>
class pool_memory_resource final
  : public detail::stream_ordered_memory_resource<pool_memory_resource<Upstream>,
                                                  detail::coalescing_free_list> {

```

I checked the hpp files, may be `cuda_async_memory_resource` is the official pool, and `pool_memory_resource` is a rmm version memory pool?

Thanks.

_Originally posted by @ZhenshengLee in https://github.com/rapidsai/rmm/issues/671#issuecomment-900325148_

**Comment by harrism** [comment]
`pool_memory_resource` existed as a stream-ordered pool allocator before `cudaMallocAsync` existed (the latter is quite new).   `cuda_async_memory_resource` is a simple wrapper around `cudaMallocAsync`. It is not the official pool. In fact, RAPIDS cuDF uses `pool_memory_resource` as its primary pool memory resource. 

Last time I ran the RMM random allocation/free benchmark, `pool_memory_resource` and/or `hybrid_memory_resource` was a bit over 2x faster than `cuda_async_memory_resource`. However, the former can suffer worse fragmentation than the latter, and in multistream usage there may be oversynchronization that we will be working on reducing in the future. (See #841).

Note that memory resources are composable, so you can even use a `cuda_async_memory_resource` as the upstream resource for a `pool_memory_resource`.

I hope this answers your question.

**Comment by ZhenshengLee** [comment]
> `pool_memory_resource` existed as a stream-ordered pool allocator before `cudaMallocAsync` existed (the latter is quite new). `cuda_async_memory_resource` is a simple wrapper around `cudaMallocAsync`. It is not the official pool. In fact, RAPIDS cuDF uses `pool_memory_resource` as its primary pool memory resource.
> 
> Last time I ran the RMM random allocation/free benchmark, `pool_memory_resource` and/or `hybrid_memory_resource` was a bit over 2x faster than `cuda_async_memory_resource`. However, the former can suffer worse fragmentation than the latter, and in multistream usage there may be oversynchronization that we will be working on reducing in the future. (See #841).
> 
> Note that memory resources are composable, so you can even use a `cuda_async_memory_resource` as the upstream resource for a `pool_memory_resource`.
> 
> I hope this answers your question.

Thanks for your quick reply!

After reading [Nvidia Developer Blog of RMM](https://developer.nvidia.com/blog/fast-flexible-allocation-for-cuda-with-rapids-memory-manager/) I know that `pool_memory_resource` is of the concept of Suballocation. But the concept of `stream_order` and/or `pool_allocation` both exist in the context of suballocation and allocation. When I create memory resource following this. 
https://github.com/rapidsai/rmm/blob/0ab6ab1153b076703ff5dc45ac2551652048c790/tests/mr/device/mr_test.hpp#L232

```cpp
inline auto make_pool_async()
{
  return rmm::mr::make_owning_wrapper<rmm::mr::pool_memory_resource>(make_cuda_async());
}
```

Is the behavior acceptable when I do this? (memory pool in and out of gpu driver?)


> Note that memory resources are composable, so you can even use a `cuda_async_memory_resource` as the upstream resource for a `pool_memory_resource`.

I am willing to add pool_memory of managed memory resource and give it tests in rmm and in cupoch, see https://github.com/neka-nat/cupoch/pull/67

And would you agree that this memory allocation policy will be of good performance for CPU-iGPU devices like NVIDIA Jetson?

Thanks.

**Comment by harrism** [comment]
The `make_pool` factory functions are intended for use in our unit tests. Please don't try to call those from production code. You should not need to use the `owning_wrapper` outside of RMM unit tests either, instead you can just manage the lifetime of all the MRs you create.

> Is the behavior acceptable when I do this? (memory pool in and out of gpu driver?)

I don't understand this question.

RMM should work with any CUDA platform that satisfies the prerequisites, including Jetson.

**Comment by ZhenshengLee** [comment]
> The `make_pool` factory functions are intended for use in our unit tests. Please don't try to call those from production code. You should not need to use the `owning_wrapper` outside of RMM unit tests either, instead you can just manage the lifetime of all the MRs you create.
> 
> > Is the behavior acceptable when I do this? (memory pool in and out of gpu driver?)
> 
> I don't understand this question.
> 
> RMM should work with any CUDA platform that satisfies the prerequisites, including Jetson.

I will take a deeper look into code and theory, and adjust my question.

Thank you for your answer.

**Comment by harrism** [comment]
Hi @ZhenshengLee , I'm going to close this issue for now, but please don't hesitate to reopen it if you have further questions.
