### ISSUE TITLE
[QST] How to use pool_memory_resource with multiple devices

### ISSUE THREAD

**Issue by chenrui17** [rapidsai/rmm#856]
**What is your question?**
I want to use `read_parquet` C++ API and rmm `pool_memory_resource` to read parquet file from hdfs in multiDevice mode, but, when it report the error like this :
```
terminate called after throwing an instance of 'thrust::system::system_error'
  what():  scan failed to synchronize: cudaErrorIllegalAddress: an illegal memory access was encountered
```
cpp code is like this
```
  int num_devices;
  cudaGetDeviceCount(&num_devices);
  std::vector<std::unique_ptr<rmm::mr::pool_memory_resource<rmm::mr::cuda_memory_resource> > > per_device_pools;
  for (int i = 0; i < num_devices; i++) {
      cudaSetDevice(i);
      rmm::mr::cuda_memory_resource cuda_mr;
      per_device_pools.push_back(
          std::make_unique<rmm::mr::pool_memory_resource<rmm::mr::cuda_memory_resource> > (&cuda_mr));
      rmm::mr::set_per_device_resource(rmm::cuda_device_id{i}, per_device_pools.back().get());
  }
  ...
  // will use std::thread to create multithread and in subthread call `read_parquet`
  auto result = cudf::io::read_parquet(read_opts,rmm::mr::get_per_device_resource(rmm::cuda_device_id{thread_id % num_devices}));
```
The problem may be about rmm resource memory init. above code only successfuly inited device '7' ,  other device cannot use

**Comment by jrhemstad** [comment]
@chenrui17 I moved this issue from cuDF to RMM as it has more to do with RMM than cuDF.

**Comment by harrism** [comment]
Couldn't you lift the `cuda_mr` outside the loop? They can all use the same cuda_mr as their upstream.

**Comment by jrhemstad** [comment]
> Couldn't you lift the `cuda_mr` outside the loop? They can all use the same cuda_mr as their upstream.

That's exactly what I had at first, but that technically violates [the rule](https://github.com/rapidsai/rmm#multiple-devices) that a resource should only be used when the active CUDA device is the same as the device that was active when the object is constructed. Now obviously that doesn't matter for `cuda_memory_resource`, but that's an implementation detail and I wanted to keep the answer generic/above board.

**Comment by harrism** [comment]
Yes, my mistake.

**Comment by chenrui17** [comment]
thanks a lot, it works now . and finally problem is the thread which create the cuda resource is end, so my sub thread cannot use gpu resource.
