### ISSUE TITLE
[FEA] Delete `thread_safe_resource_adaptor`: it is untested and likely no longer used

### ISSUE THREAD

**Issue by harrism** [rapidsai/rmm#866]
**Is your feature request related to a problem? Please describe.**
`thread_safe_resource_adaptor` used to be used for `pool_memory_resource` to make it thread safe, but now this and other MRs are internally thread safe. 

**Describe the solution you'd like**
Delete this adaptor, as it is untested.

**Describe alternatives you've considered**
Write tests, which is more work.

**Comment by jrhemstad** [comment]
I'm not so sure. Talking with @abellina, we ran into a situation where they wanted to use [`limiting_resource_adapator`](https://github.com/rapidsai/rmm/blob/branch-21.10/include/rmm/mr/device/limiting_resource_adaptor.hpp), but it's not actually thread safe. The `thread_safe_resource_adaptor` would be a trivial solution.

**Comment by jrhemstad** [comment]
As far as testing goes, I think it's sufficient to just exercise that the allocation/deallocation work as expected. Trying to test thread safety is usually folly.

**Comment by harrism** [comment]
`limiting_resource_adaptor` is now thread-safe. #869

**Comment by harrism** [comment]
Since thread_safe_resource_adaptor is now tested, I'm closing this.
