### ISSUE TITLE
[BUG] Potentially undefined behavior of cuda_stream_pool::get_stream

### ISSUE THREAD

**Issue by achirkin** [rapidsai/rmm#871]
These functions seem to have the undefined behavior (remainder of zero division) for the case when the pool size is zero (which is the default in [raft::handle_t](https://github.com/rapidsai/raft/blob/f311247690437f669936217b38d62c606244621e/cpp/include/raft/handle.hpp#L51) and as such is rather dangerous):

https://github.com/rapidsai/rmm/blob/fe53a722ae97b7dcf7c6c6eeb2d4f9a3c2557614/include/rmm/cuda_stream_pool.hpp#L61-L64

https://github.com/rapidsai/rmm/blob/fe53a722ae97b7dcf7c6c6eeb2d4f9a3c2557614/include/rmm/cuda_stream_pool.hpp#L76-L79

**Comment by jrhemstad** [comment]
Hm, we should probably disallow constructing with a pool size of 0. I can't think of a sane behavior of `get_stream` when the pool is empty.
