### ISSUE TITLE
[FEA] Make CMake style check used in CI easy to run locally

### ISSUE THREAD

**Issue by vyasr** [rapidsai/rmm#903]
**Is your feature request related to a problem? Please describe.**
I'd like for it to be easy to run the CMake linters locally. The details of the request were originally posted in rapidsai/cudf#9396.

**Describe the solution you'd like**
A port of the solution from rapidsai/cudf#9484 would enable local cmake-format runs either via script or through pre-commit.

**Comment by vyasr** [comment]
CC @harrism

**Comment by harrism** [comment]
@vyasr  Thanks! Go for it if you have time.  I would love to be able to cmake-format my current PR...
