### ISSUE TITLE
[BUG] Cannot be built in an environment where fmt and spdlog are installed independently.

### ISSUE THREAD

**Issue by gdaisukesuzuki** [rapidsai/rmm#904]
**File bug happens**
arena.hpp
arena_memory_resource.hpp

**Issues to be fixed**
Both header files are assumed to be built on spdlog, where fmt is bundled, and not in an environment where fmt and spglog are installed separately.

**Suggested patch**
-----------------------------
```
*** rmm/include/rmm/mr/device/detail/arena.hpp-dist     2021-11-03 23:02:58.084936643 +0900
--- rmm/include/rmm/mr/device/detail/arena.hpp  2021-11-03 23:04:31.726165374 +0900
***************
*** 24,30 ****
  #include <cuda_runtime_api.h>
  
  #include <spdlog/common.h>
! #include <spdlog/fmt/bundled/ostream.h>
  
  #include <algorithm>
  #include <cstddef>
--- 24,35 ----
  #include <cuda_runtime_api.h>
  
  #include <spdlog/common.h>
! #if !defined(SPDLOG_FMT_EXTERNAL)
! #      include <spdlog/fmt/bundled/ostream.h>
! #else
! #      include <fmt/ostream.h>
! #endif
! 
  
  #include <algorithm>
  #include <cstddef>
*** rmm/include/rmm/mr/device/arena_memory_resource.hpp-dist    2021-11-03 23:53:12.040547640 +0900
--- rmm/include/rmm/mr/device/arena_memory_resource.hpp 2021-11-03 23:54:49.082345112 +0900
***************
*** 23,29 ****
  #include <cuda_runtime_api.h>
  
  #include <spdlog/common.h>
! #include <spdlog/fmt/bundled/ostream.h>
  
  #include <cstddef>
  #include <map>
--- 23,34 ----
  #include <cuda_runtime_api.h>
  
  #include <spdlog/common.h>
! #if !defined(SPDLOG_FMT_EXTERNAL)
! #      include <spdlog/fmt/bundled/ostream.h>
! #else
! #      include <fmt/ostream.h>
! #endif
! 
  
  #include <cstddef>
  #include <map>
```
-----------------------------

**Comment by harrism** [comment]
I think it would be nice to just be able to use the `#include <fmt/ostream.h>` always. So we should either depend on `fmt` directly, or add a `-I` compiler option pointing to the location of `spdlog`.

**Comment by harrism** [comment]
@robertmaynard given we get spdlog with cpm, is there a simple way in cmake to add `-I<spdlog_install_dir>/fmt` to the command line?

**Comment by harrism** [comment]
Just realized spdlog puts its bundled fmt in `spdlog/fmt/bundled`, not just in `spdlog/fmt`. So maybe that won't work.

**Comment by gdaisukesuzuki** [comment]
I think the way the 2 files should be modified  as the following file (which calls fmt) is written.

/usr/include/spdlog/fmt/fmt.h

**Comment by robertmaynard** [comment]
It looks like spdlog provides wrapper headers that should be used instead of directly including anything in the `bundled` directory.

For example for `ostream` we should be using `spdlog/fmt/osr.h` which computes the correct header based on `SPDLOG_FMT_EXTERNAL`

**Comment by robertmaynard** [comment]
https://github.com/rapidsai/rmm/pull/907 Should resolve this issue
