### ISSUE TITLE
[BUG] Improve C++ test coverage

### ISSUE THREAD

**Issue by harrism** [rapidsai/rmm#906]
With https://github.com/rapidsai/rmm/pull/905 we now have C++ code coverage analysis for RMM. Coverage is not bad in a lot of places, but can be improved (we're at about 77%).  

It shouldn't be hard to close the gaps, they are mostly tests of simple infrequently used methods on memory resources and containers.

**Comment by harrism** [comment]
Currently only arena_mr and arena.hpp need coverage improved. As of #920 coverage of most files is 100%.

**Comment by harrism** [comment]
We also need to look at getting coverage testing into CI.

**Comment by harrism** [comment]
@rongou have you checked test coverage with your latest arena testing improvements in #916 ?

**Comment by rongou** [comment]
With the latest code it shows `mr/device/detail/arena.hpp` at 94.1%. I'll see if I can improve it further.

**Comment by rongou** [comment]
At 100% now.
