### ISSUE TITLE
[FEA] Add ssize() members to device_buffer/device_uvector that returns a signed integer

### ISSUE THREAD

**Issue by jrhemstad** [rapidsai/rmm#927]
Mixing signed and unsigned types cause annoying compiler warnings necessitating a lot of casts. A common source of this problem is from the fact that `size()` functions return `size_t` which is unsigned. 

C++20 addressed this by adding a signed size function `ssize`.

See https://stackoverflow.com/questions/56217283/why-is-stdssize-introduced-in-c20

We should add 
```
int64_t ssize() const noexcept{
   return static_cast<int64_t>(size());
}
```
to `device_buffer` and `device_uvector

**Comment by jrhemstad** [comment]
We could maybe add an assert in there for debugging potential overflows. 

```
assert(size() < std::numeric_limits<int64_t>::max());
```

**Comment by jakirkham** [comment]
This is also relevant for Python where `Py_ssize_t` is used a lot for sizes, but is also a signed integer
