### ISSUE TITLE
[BUG] TRACKING_TEST only works with RMM_LOGGING_LEVEL=DEBUG

### ISSUE THREAD

**Issue by rongou** [rapidsai/rmm#928]
**Describe the bug**
After #920 is merged, running tests from head fails:
```console
[ RUN      ] TrackingTest.LogOutstandingAllocations
/home/rou/src/rmm/tests/mr/device/tracking_mr_tests.cpp:217: Failure
Expected: (oss.str().find("Outstanding Allocations")) != (std::string::npos), actual: 18446744073709551615 vs 18446744073709551615
```

**Steps/Code to reproduce bug**
Sync to head, run cmake and ninja, invoke `./gtests/TRACKING_TEST`.

**Expected behavior**
Tests should pass with the default configuration.

**Environment details (please complete the following information):**
 - Environment location: Bare-metal
 - Method of RMM install: from source

**Additional context**
Seems like the logging level is determined at compile time, while the test is trying to modify it at runtime. The only way to get the test to pass is to run `cmake .. -DRMM_LOGGING_LEVEL=DEBUG`.

**Comment by harrism** [comment]
oops, looking.
