### ISSUE TITLE
[FEA] Function to get info on what's the largest chunk that can be safely allocated

### ISSUE THREAD

**Issue by teju85** [rapidsai/rmm#93]
**Is your feature request related to a problem? Please describe.**
`rmmGetInfo` gives information about the amount of free memory available. However, that can be an incorrect information in the light of fragmentation of the memory regions.

**Describe the solution you'd like**
`rmmGetInfo` should also give another variable as output which tells us what is the largest contiguous memory region available for allocation.

**Describe alternatives you've considered**
There are no alternatives to this. The way we have worked-around this issue is to expose a 'max-mem' parameter to our users and hope that they'll decide and pass the right amount that'll not cause OOM error down the line. This code can be seen [here](https://github.com/rapidsai/cuml/blob/branch-0.8/cpp/src/dbscan/dbscan.hpp#L31)

**Additional context**
Since RMM wraps around cnmem, maybe this change should be done in cnmem itself. But I've filed this issue inside RMM, atleast to get the conversation started. Tagging cuML folks, JFYI: @JohnZed @dantegd @cjnolet

**Comment by harrism** [comment]
We've discussed this multiple times and there doesn't seem to be a good way to expose this in the base interface, so we would rather not provide it. Closing, but please reopen if it is a big problem.
