### ISSUE TITLE
[BUG] Segfault when a `device_buffer` is released as its memory resource has already been released

### ISSUE THREAD

**Issue by viclafargue** [rapidsai/rmm#943]
**Describe the bug**
A segfault is triggered when a `device_buffer` is released as its memory resource has already been released.

**Steps/Code to reproduce bug**
1) Enable logging (or any `UpstreamResourceAdaptor`)
2) Allocate some memory through native code.
3) Disable logging (or remove the `UpstreamResourceAdaptor`)

Explanation :
A pointer to the `logging_resource_adaptor` will be saved in the `device_buffer` instance. However, whereas RMM's Python classes retain a reference to the memory resource preventing its deletion, the native code doesn't. Because of this, the `logging_resource_adaptor` can be released before the `device_buffer` is, making its proper release impossible.

**Expected behavior**
No segfault should be observed.

**Note:**
Collecting the garbage collector before disabling the RMM logging seems to fix the issue. However, it doesn't look like a very good long term solution.

**Comment by shwina** [comment]
Sync'd offline, and it looks like this issue arises for a custom extension type that holds a reference to a C++ type, which in turn holds a reference to a `rmm::device_uvector`. That `device_uvector` depends on the memory resource being alive at the time of deallocation. The simplest solution here is for the custom extension type to hold a reference to the current memory resource,[ in the same way that `rmm.DeviceBuffer` does](https://github.com/rapidsai/rmm/blob/branch-22.02/python/rmm/_lib/device_buffer.pxd#L42).

**Comment by harrism** [comment]
So is this a bug that needs to be fixed in RMM, or in @viclafargue 's code?

**Comment by jakirkham** [comment]
I thought this was fixed with PR ( https://github.com/rapidsai/rmm/pull/931 )?

**Comment by harrism** [comment]
@shwina can you confirm?

**Comment by shwina** [comment]
@viclafargue does the solution I posted above work for your use case? #931 fixed a somewhat different issue than this one.

**Comment by viclafargue** [comment]
Yes, #931 is a different issue. As discussed offline, the lifetime of the memory resource should be the responsibility of the user. Holding a reference to the current memory resource in the same way the `rmm.DeviceBuffer` does should indeed solve the issue. Thank you for the answers. Closing the issue.
