### ISSUE TITLE
Fetch runtime version with cuda-python instead of numba.

### ISSUE THREAD

**Issue by bdice** [rapidsai/rmm#948]
PR #946 introduces a workaround for an issue in cuda-python that fetches a hardcoded CUDA runtime version. https://github.com/NVIDIA/cuda-python/issues/16

Once that upstream issue is resolved, we should update the implementation in RMM to use `cuda.cudart.cudaRuntimeGetVersion()` instead of `numba.cuda.runtime.get_version()`.

_Originally posted by @jakirkham in https://github.com/rapidsai/rmm/pull/946#discussion_r788126573_

**Comment by wence-** [comment]
Just to note, this will likely be possible with cuda 12.3, so we should revisit then.

**Comment by bdice** [comment]
An API for getting the local CUDA runtime version was added in cuda-python 12.3, as `cudart.getLocalRuntimeVersion()`.

12.3.0 release notes: https://nvidia.github.io/cuda-python/release/12.3.0-notes.html

It was also backported to cuda-python 11.8.3: https://nvidia.github.io/cuda-python/release/11.8.3-notes.html

To resolve this issue, we should switch to using that API and update the minimum version requirements. However, we may not be able to update to cuda-python 12.3 yet. I'm not sure. I don't think it was backported to cuda-python 12.2.1.

**Comment by bdice** [comment]
Done in #1756.

**Comment by jakirkham** [comment]
Huzzah! 🥳

Thanks Bradley! 🙏
