### ISSUE TITLE
[FEA] RMM memory log events include percent of pool and pool size

### ISSUE THREAD

**Issue by kevingerman** [rapidsai/rmm#956]
It would be helpful if RMM memory logs included a field that showed either the current pool size or percentage of pool in use at each event.

**Comment by randerzander** [comment]
This request is based on many analyses of RAPIDS workflows centering on needing to know "peak memory" used by each worker during job execution.

With the RMM pool enabled, nvidia-smi shows what looks like static memory usage right up until the pool needs to grow.

Thus, it would be useful for logs to indicate the size of the pool and the portion in use.

**Comment by harrism** [comment]
RMM has multiple pool implementations, and is intended to be an interface that supports many pool implementations. Therefore it's not possible to make our generic logs report this information for every pool implementation. The generic logs can only report the information that is common to all memory resources -- calls to allocate and deallocate.

Instead, I would suggest using a [`statistics_resource_adaptor`](https://github.com/rapidsai/rmm/blob/branch-22.04/include/rmm/mr/device/statistics_resource_adaptor.hpp) and querying the information you need when you need it.

**Comment by shwina** [comment]
Reopening to ask a related question: could the specific pool implementation `pool_memory_resource` expose its [`pool_size`](https://github.com/rapidsai/rmm/blob/e61e85b44437e1d7f786a5ad81a2c7e5a6f99d35/include/rmm/mr/device/pool_memory_resource.hpp#L348) member instead?

It seems useful to know how much memory RMM has "to itself" at any given time, and there isn't a way to do that AFAICT.

**Comment by harrism** [comment]
That should be easy enough to add. Do you mean an accessor, or do you mean to log its pool size in every message?

**Comment by shwina** [comment]
I'm requesting an accessor, specifically to enable determining the RMM allocated memory v/s "externally" allocated memory at any given time.

**Comment by harrism** [comment]
Got it. Maybe a more directly named issue would be a better place for that request.

**Comment by harrism** [comment]
Now that I'm in front of my computer, I can see that [`pool_memory_resource::pool_size()` already exists](https://github.com/rapidsai/rmm/blob/3e1721d65c79a07b62c4c7682ff349f3b48efa90/include/rmm/mr/device/pool_memory_resource.hpp#L348).

**Comment by harrism** [comment]
@shwina I'm going to close this now that you made `pool_size()` public. The name of this issue doesn't reflect that feature request anyway.
