### ISSUE TITLE
[DOC] Host Doxygen HTML again

### ISSUE THREAD

**Issue by gmarkall** [rapidsai/rmm#957]
## Report incorrect documentation

**Location of incorrect documentation**

https://docs.rapids.ai/api/rmm/stable/

**Describe the problems or issues found in the documentation**

In #54 the location of the Doxygen documentation is given as the above URL, which I recall was correct at some point in the past - it did hold the Doxygen documentation. However, I think that Python docs for RMM have since been added and replaced the Doxygen docs at that URL.

**Steps taken to verify documentation is incorrect**

- Viewed the documentation at https://docs.rapids.ai/api/rmm/stable/
- Clicked through every link in the contents and indices and tables list.

**Suggested fix for documentation**

- Host the doxygen documentation on https://docs.rapids.ai somewhere, or
- if it is already hosted somewhere, link to it from https://docs.rapids.ai/api/rmm/stable/

**Comment by harrism** [comment]
@gmarkall the doxygen docs are under `librmm`, not `rmm`. 

https://docs.rapids.ai/api/librmm/stable/

Those docs need a non-blank main_page, but they do exist.

**Comment by gmarkall** [comment]
Following up on the stale notice - looking over this again I see that I'd not understood that the C++ docs for all the RAPIDS libraries are linked under lib<library> on https://docs.rapids.ai/api - many thanks for the clarification @harrism, and apologies for the inconvenience.
