### ISSUE TITLE
Please help with the process how to make conda package available

### ISSUE THREAD

**Issue by alhad-deshpande** [rapidsai/rmm#967]
**What is your question?**
@harrism 

I have raised a PR yesterday (Link: https://github.com/rapidsai/rmm/pull/964) to add yml file for cudatoolkit version which got merged. I have locally built RMM v21.12.00 on POWER (ppc64le) with cuda toolkit 11.6 version successfully and also ran test cases which are also passing. Now I want to make RMM version v21.12.00 for POWER (ppc64le) architecture with cudatoolkit version 11.6 available as conda package on anaconda (https://anaconda.org/rapidsai/rmm/), 

Can you please let me know the process for the same?

**Comment by harrism** [comment]
Hi @alhad-deshpande, we are not equipped to create conda packages for POWER. I'm glad you were able to do so for yourself. We can't host third-party conda packages on the rapidsai Conda channel, so I would recommend that you create your own channel if you need the package hosted.

**Comment by leofang** [comment]
Would this work for you?
```
conda install -c conda-forge librmm=21.12
```

**Comment by alhad-deshpande** [comment]
> Would this work for you?
> 
> ```
> conda install -c conda-forge librmm=21.12
> ```

**Comment by alhad-deshpande** [comment]
> 



> Would this work for you?
> 
> ```
> conda install -c conda-forge librmm=21.12
> ```

**Comment by alhad-deshpande** [comment]
> > 
> 
> > Would this work for you?
> > ```
> > conda install -c conda-forge librmm=21.12
> > ```

Yes. Also need rmm=21.12 for Python package. But it should be for POWER arch (ppc64le). Is this possible?

**Comment by leofang** [comment]
@alhad-deshpande Please open an issue in https://github.com/conda-forge/librmm-feedstock or https://github.com/conda-forge/staged-recipes to discuss. The official stand here from the RMM team is that they would not support ppc64le builds. It's likely that you will need to create and maintain a conda recipe yourself.
